### PR TITLE
cmd: send version info to stdout

### LINKED ISSUE #1648: Bee prints version to the stderr
#### Summary

I was trying to set the output of the `bee version` to a variable , when I noticed I don't get anything on the `stdout` .
[I've solved the issue](https://github.com/ethersphere/bee-factory/blob/7d0a179a503e1ba112bb20d1d600bb3677b32d1b/scripts/bee-docker-build.sh#L37) by redirecting the `stderr` to the `stdout`, but I don't think it is the intentional behaviour of the command.

#### Steps to reproduce

```sh
BEE_VERSION=$(bee version)
# Empty string
echo $BEE_VERSION
BEE_VERSION=$(bee version 2>&1)
# Actual Bee version
echo $BEE_VERSION
```

#### Expected behavior

I can get back the result on the `stdout`

### PR DESCRIPTION
**Pull request by acud**
This PR sends the `bee version` command output to stdout. `cobra` defaults to `stderr` if output is not explicitly set.

fixes #1648

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1660)

### CODE REVIEW

**Review by mrekucci — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1660#-:-MZwrfHr0V8EbrWDdFpg:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @aloknerurkar and @esadakar)

**Review by esadakar — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1660)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aloknerurkar)

**Review by esadakar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1660)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aloknerurkar)

**Review by mrekucci — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1660)* status: all files reviewed, 1 unresolved discussion (waiting on @acud and @aloknerurkar)

___
*[cmd/bee/cmd/version.go, line 23 at r1](https://reviewable.io/reviews/ethersphere/bee/1660#-MZx1KlEDr-egRaMwLJB:-MZx1KlEDr-egRaMwLJC:bnms85g) ([raw file](https://github.com/ethersphere/bee/blob/681b483803f1fa0eed948ad960d9387e28d3c390/cmd/bee/cmd/version.go#L23)):*
> ```Go
> 		},
> 	}
> 	v.SetOut(os.Stdout)
> ```

Replace `os.Stdout` with `c.root.OutOrStdout()` and this will fix also the failing `TestVersionCmd` test.

**Review by mrekucci — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1660)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @aloknerurkar and @esadakar)

**Review by mrekucci — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1660)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aloknerurkar)

**Review by anatollupacescu — APPROVED** [review]

**Pull request merged**
