### PR TITLE
feat(kademlia): add prometheus metrics

### PR DESCRIPTION
**Pull request by mrekucci**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1960)

### CODE REVIEW

**Review by esadakar — APPROVED** [review]

**Review by acud — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1960)* status: all files reviewed, 1 unresolved discussion (waiting on @anatollupacescu and @mrekucci)

___
*[pkg/topology/kademlia/metrics.go, line 13 at r1](https://reviewable.io/reviews/ethersphere/bee/1960#-MbD-BHU-0oQJZplEuy9:-MbD-BHU-0oQJZplEuyA:b52sxvi) ([raw file](https://github.com/ethersphere/bee/blob/d4af3360e27c5d0557f2b4dc3798d3868bcb9dde/pkg/topology/kademlia/metrics.go#L13)):*
> ```Go
> 
> // metrics groups kademlia related prometheus counters.
> type metrics struct {
> ```

I would also add here:
- `ConnectedPeers` as a gauge and update it periodically (or every time an event happens) with the value of `connectedPeers.Length()`
- `KnownPeers` in a similar manner
- `MetricsFlushTime` as a counter that counts total nanoseconds spent flushing the metrics about peers to the statestore
- `Depth` as gauge and update it every time we recalculate and set depth
- `Radius` likewise
- `BootnodeConnectionAttempts` for every time we try to connect to a bootnode

**Review by zelig — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1960)* status: all files reviewed, 1 unresolved discussion (waiting on @anatollupacescu and @mrekucci)

**Review by acud — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1960)* status: all files reviewed, 1 unresolved discussion (waiting on @anatollupacescu and @mrekucci)

___
*[pkg/topology/kademlia/metrics.go, line 13 at r1](https://reviewable.io/reviews/ethersphere/bee/1960#-MbD-BHU-0oQJZplEuy9:-MbFUExf6ESsH9gtSdLJ:bt6mp6b) ([raw file](https://github.com/ethersphere/bee/blob/d4af3360e27c5d0557f2b4dc3798d3868bcb9dde/pkg/topology/kademlia/metrics.go#L13)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

I would also add here:
- `ConnectedPeers` as a gauge and update it periodically (or every time an event happens) with the value of `connectedPeers.Length()`
- `KnownPeers` in a similar manner
- `MetricsFlushTime` as a counter that counts total nanoseconds spent flushing the metrics about peers to the statestore
- `Depth` as gauge and update it every time we recalculate and set depth
- `Radius` likewise
- `BootnodeConnectionAttempts` for every time we try to connect to a bootnode

</blockquote></details>

I would also add a metric for
- `PickCounter` for how many times pick was called
- `DontPickCounter` for how many times we returned `false` for `Pick`

**Review by acud — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1960)* status: all files reviewed, 1 unresolved discussion (waiting on @anatollupacescu and @mrekucci)

___
*[pkg/topology/kademlia/metrics.go, line 13 at r1](https://reviewable.io/reviews/ethersphere/bee/1960#-MbD-BHU-0oQJZplEuy9:-MbFeugh5HT730idZEyT:b-bpjh5g) ([raw file](https://github.com/ethersphere/bee/blob/d4af3360e27c5d0557f2b4dc3798d3868bcb9dde/pkg/topology/kademlia/metrics.go#L13)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

I would also add a metric for
- `PickCounter` for how many times pick was called
- `DontPickCounter` for how many times we returned `false` for `Pick`
</blockquote></details>

also, we need to have information about how many light nodes we know and are connected to. since this is decoupled from kademlia, we need to add these metrics either inside the light node container or inside `libp2p` package:
- `LightNodeConnectedPeers`
- `LightNodeKnownPeers`
- `LightnodeKickedCount` for every time we kick a light node to accommodate another

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1960)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @acud, @anatollupacescu, and @zelig)

___
*[pkg/topology/kademlia/metrics.go, line 13 at r1](https://reviewable.io/reviews/ethersphere/bee/1960#-MbD-BHU-0oQJZplEuy9:-MbGd6Lp4AKE5FP7wnns:b-tgg5ao) ([raw file](https://github.com/ethersphere/bee/blob/d4af3360e27c5d0557f2b4dc3798d3868bcb9dde/pkg/topology/kademlia/metrics.go#L13)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

also, we need to have information about how many light nodes we know and are connected to. since this is decoupled from kademlia, we need to add these metrics either inside the light node container or inside `libp2p` package:
- `LightNodeConnectedPeers`
- `LightNodeKnownPeers`
- `LightnodeKickedCount` for every time we kick a light node to accommodate another
</blockquote></details>

I'll address the light node metrics in a separate PR.

**Review by acud — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1960#-:-MbHFLBg8RdPru1miBLA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @anatollupacescu and @mrekucci)

___
*[pkg/topology/kademlia/kademlia.go, line 464 at r2](https://reviewable.io/reviews/ethersphere/bee/1960#-MbGwpc10RRHaaokwmqZ:-MbGwpc28op4W384kwOe:b-439xrg) ([raw file](https://github.com/ethersphere/bee/blob/1cdec2b4bc0ceeed8627b25eaa7751fdd367ca05/pkg/topology/kademlia/kademlia.go#L464)):*
> ```Go
> 			start := time.Now()
> 			if err := k.collector.Flush(); err != nil {
> 				k.logger.Debugf("kademlia: unable to flush metrics counters to the persistent store: %v", err)
> ```

maybe increment an error counter here too? `FlushErrors`?

**Review by acud — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1960#-:-MbID6IJ2XSCZokAxH25:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatollupacescu)

**Pull request merged**
