### PR TITLE
fix: bucket depth size expectation

### PR DESCRIPTION
**Pull request by anatollupacescu**
Fixing the precondition to be aligned with contract check:

https://github.com/ethersphere/storage-incentives/blob/master/src/PostageStamp.sol#L100

This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2099)

### CODE REVIEW

**Review by ralph-pichler — APPROVED** [review]

**Review by zelig — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2099)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatollupacescu)

**Review by Eknir — APPROVED** [review]
lgtm

**Review by Eknir — CHANGES_REQUESTED** [review]
Need to update the test

**Review by Eknir — APPROVED** [review]
lgtm. Thank you for updating the tests!

**Review by Eknir — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2099)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatollupacescu)

**Pull request merged**
