### PR TITLE
refactor(postage): enable parallel test

### LINKED ISSUE #3831: enable paralleltest lint check in `pkg/postage`
Currently `pkg/postage` has disabled `paralleltest` lint check (see `golangci.yaml` file). This check should be enabled for this package and tests should be corrected to use `t.Parallel()`.

Acceptance criteria:
- enable `paralleltest` lint check in  `pkg/postage`
  - all tests should use `t.Parallel()`; if tests for some reason could not use `t.Parallel()` then it disabling lint check per tests case should be alright
- all tests should pass 
- there should be no lint errors

### PR DESCRIPTION
**Pull request by emekaokoli19**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description
Enables parallel testing to be done on pkg/postage by adding t.parallel() to test functions

### Related Issue (Optional)
closes #3831 

### Screenshots (if appropriate):

- - -
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/3839)

### CODE REVIEW

**Comment by notanatol** [comment]
nice one, thanks.

just update the title to something that would follow the rules, like: `refactor(postage): enable parallel test`

**Comment by notanatol** [comment]
> nice one, thanks.
> 
> just update the title to something that would follow the rules, like: `refactor(postage): enable parallel test`

it's not enough to change the PR's title, you also have to amend the commit message:

- `git commit --amend`
- set the message to `refactor(postage): enable parallel test`
- force push the branch: `git push --force`

**Comment by vladopajic** [comment]
@emekaokoli19 how is it going? are you finding your way around?

**Comment by emekaokoli19** [comment]
> @emekaokoli19 how is it going? are you finding your way around?

Yea, I can't seem to run **make lint** and **make test** locally on single folders or files. It always runs through the whole repository

**Comment by vladopajic** [comment]
> Yea, I can't seem to run **make lint** and **make test** locally on single folders or files. It always runs through the whole repository

`make lint` and `make test` are helpers (shortcuts) for testing and linting. you can always run native commands eg. `go test ./pkg/postage/...` . 

you can also modify `Makefile` if you temporally want make commands to have different role (but do not commit that change).  also, consider it a good practice to always run commands on entire repo

**Comment by vladopajic** [comment]
@emekaokoli19  Closing this PR due to inactivity. Feel free to reopen PR if you decide to continue working on this issue. Thanks!

**Pull request closed without merging**
