### PR TITLE
Revert reversing the iteration order from pushsync

### PR DESCRIPTION
**Pull request by zbiljic**
* Revert "Reverse the order of the queue for push sync index (#827)"

relates to #843

### CODE REVIEW

**Review by janos — APPROVED** [review]

**Comment by Eknir** [comment]
Hi @zbiljic, could you connect this one to an issue, please?

**Comment by acud** [comment]
when the PR will now be closed, the issue too. I thought you wanted the issues to be open @Eknir

**Review by acud — APPROVED** [review]

**Comment by Eknir** [comment]
> when the PR will now be closed, the issue too. I thought you wanted the issues to be open @Eknir

Which automation is responsible for that? I'm not aware of this.

**Comment by acud** [comment]
look up
> @zbiljic zbiljic linked an issue that may be closed by this pull request 3 hours ago

**Comment by zbiljic** [comment]
> > when the PR will now be closed, the issue too. I thought you wanted the issues to be open @Eknir
> 
> Which automation is responsible for that? I'm not aware of this.

As I mentioned before, GitHub internal system will close linked issue when this PR is closed.

**Pull request merged**
