### PR TITLE
feat: move debug endpoints to api

### LINKED ISSUE #2940: Debug flag with restricted endpoints is confusing
Historically the `debug` config variable turned the Debug API on or off. Now that the endpoints from the Debug API moved to the Bee API the behavior of this variable has changed:
- `true` means that the Debug API is turned on (as it was before). The endpoints of the Debug API are not available on the Bee API.
- `false` means that the Debug API is turned off. The endpoints of the Debug API are available as restricted endpoints on the Bee API.

I would argue that this is confusing, especially considering that the Debug API will be deprecated and removed in the future. It would be good to come up with a solution for this problem in a way that is also future-proof.
So far three alternatives were considered:
1. We acknowledge that this is the case and we don't do anything.
2. We use another flag to control this behavior or find a better way to do this
3. We deprecate the `debug` flag over time

Please note that the solutions has a certain overlap. I think it would be good to find a better way (alternative nr. 2) because it will be confusing for people who used the product before or during the deprecation period (which can be undeterministically long potentially).

### PR DESCRIPTION
**Pull request by notanatol**
### Checklist

- [X] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md)
- [x] My change requires a updates to the OpenAPI
- [ ] My change requires a documentation update and I have done it

### Description
In order to have a better UX the debug API endpoints are moved to the main API.
In the first phase (the scope of this PR) they will be duplicated on both ports.
After the desktop app is updated to transition to using the API endpoints, the `debug` endpoints will be decommissioned.

Closes #2940 

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2846)

### CODE REVIEW

**Review by mrekucci — COMMENTED** [review]
> Reviewed 38 of 45 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @notanatol)

___
*[`openapi/Swarm.yaml` line 4 at r2](https://reviewable.io/reviews/ethersphere/bee/2846#-N0kFQI78MiG6rJ9_aGx:-N0kFQI78MiG6rJ9_aGy:b4lnfl3) ([raw file](https://github.com/ethersphere/bee/blob/48e723f2c91819bcf7c0cf4b723a32c0a36915b4/openapi/Swarm.yaml#L4)):*
> ```YAML
> 
> info:
>   version: 3.0.1
> ```

The version should be also changed.
___
*[`pkg/api/status.go` line 1 at r2](https://reviewable.io/reviews/ethersphere/bee/2846#-N0kGSfh2CJBFHpN2sBg:-N0kGSfh2CJBFHpN2sBh:b-zhdpvi) ([raw file](https://github.com/ethersphere/bee/blob/48e723f2c91819bcf7c0cf4b723a32c0a36915b4/pkg/api/status.go#L1)):*
> ```Go
> package api
> ```

Missing header.

**Review by notanatol — COMMENTED** [review]
> Reviewed 34 of 45 files at r1, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @notanatol)

**Review by mrekucci — APPROVED** [review]
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @aloknerurkar, @istae, @mrekucci, and @notanatol)

___
*[`pkg/api/wallet.go` line 27 at r3](https://reviewable.io/reviews/ethersphere/bee/2846#-N13pTkb9sQqMfAt1BhG:-N13pTkb9sQqMfAt1BhH:bgn7318) ([raw file](https://github.com/ethersphere/bee/blob/83400db6d7ec4d97a1f4fff30a09f876226d1dbf/pkg/api/wallet.go#L27)):*
> ```Go
> 	if err != nil {
> 		s.logger.Debugf("wallet: unable to acquire balance from the chain backend: %v", err)
> 		s.logger.Errorf("wallet: unable to acquire balance from the chain backend")
> ```

Change `Errorf` to `Error`, also below.

**Review by notanatol — COMMENTED** [review]
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @aloknerurkar, @istae, and @mrekucci)

___
*[`pkg/api/wallet.go` line 27 at r3](https://reviewable.io/reviews/ethersphere/bee/2846#-N13pTkb9sQqMfAt1BhG:-N14GdG0826AUxQs9b3b:b-7ql1td) ([raw file](https://github.com/ethersphere/bee/blob/83400db6d7ec4d97a1f4fff30a09f876226d1dbf/pkg/api/wallet.go#L27)):*
<details><summary><i>Previously, mrekucci wrote…</i></summary><blockquote>

Change `Errorf` to `Error`, also below.
</blockquote></details>

fixed

**Review by notanatol — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @aloknerurkar, @istae, and @mrekucci)

**Review by notanatol — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @aloknerurkar, @istae, and @mrekucci)

**Review by notanatol — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @aloknerurkar, @istae, and @mrekucci)

**Review by notanatol — COMMENTED** [review]
> Reviewed 58 of 58 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @aloknerurkar, @istae, and @mrekucci)

**Review by notanatol — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @aloknerurkar, @istae, and @mrekucci)

**Review by mrekucci — APPROVED** [review]
> Reviewed 10 of 12 files at r4, 2 of 3 files at r5, 2 of 4 files at r6, 57 of 58 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @aloknerurkar, and @istae)

**Review by acud — APPROVED** [review]
looks great @notanatol. thanks for this. it would be good to double check that all CORS headers were migrated correctly when merging the APIs (this issue usually bites us...). otherwise LGTM!

**Review by aloknerurkar — APPROVED** [review]
LGTM. I have merged the subdomain support PR so you may need to resolve some conflicts. Let me know if you need any help there.

**Review by notanatol — COMMENTED** [review]
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @istae)

**Comment by agazso** [comment]
Thanks @notanatol, nice work!

**Pull request merged**
