### PR TITLE
fix(puller): delete cursors on disconnect

### PR DESCRIPTION
**Pull request by acud**
Removes outdated cursors on peer disconnect.

This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2630)

### CODE REVIEW

**Comment by acud** [comment]
can do it with some TTL and delete it only if the last time we've seen the cursors was for example >= 1 day

**Review by aloknerurkar — APPROVED** [review]

**Review by mrekucci — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2630)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldeffenb)

___
*[pkg/puller/puller.go, line 571 at r3](https://reviewable.io/reviews/ethersphere/bee/2630#-MoEeqmhDjqQopaJzlIT:-MoEeqmjCnMVEt1XgeIX:b-2y1esz) ([raw file](https://github.com/ethersphere/bee/blob/dc3d671d3d2a7bcde0051cd8348dba7d4f13664d/pkg/puller/puller.go#L571)):*
> ```Go
> 
> type peerCursors struct {
> 	timestamp time.Time
> ```

Just a nitpick, timestamp is usually an integer and this is `time.Time` so I'd rename it to `created`.

**Review by ldeffenb — APPROVED** [review]
"If it builds without errors, ship it!".  No seriously, this looks good.  The first time I saw this change going through, I missed seeing where the new timestamp was getting set.  I see it now and am glad that we're not just dropping the cursors on every disconnect.  As a node operator with cursors that take literally minutes of 100% CPU to generate when requested, I appreciate my peers not asking me for them more than necessary.

**Comment by acud** [comment]
Thanks for the input about the problem that led to this PR @ldeffenb. About the inefficiencies of generating cursors, we'll hopefully have a solution for this very soon :)

**Pull request merged**
