### PR TITLE
Log ethereum address on bee init/start

### LINKED ISSUE #969: Print Ethereum address with Bee init command
# User story

## Story

As a user, I want to know my Ethereum address after running Bee init, such that I can fund my Ethereum address 

## Background

- Issue arose during testing session.
- Completion by printing logging the key to the terminal
- Suggestion to return the initialized parameters (including Ethereum address)

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

### PR DESCRIPTION
**Pull request by paxthemax**
Inform the user about her generated Ethereum address as soon as possible when calling `bee init` or `bee start`. Fixes #969

### CODE REVIEW

**Review by ralph-pichler — APPROVED** [review]

**Comment by Eknir** [comment]
I start reviewing

**Review by janos — APPROVED** [review]

**Comment by Eknir** [comment]
Hi Pavle,
I just checked out your branch and ran `bee init`. Just to ensure with @vandot that this also works with CLEF. Additionally, I would suggest that the `init` command not only logs the keys, but also returns them, so other programs can interface with the init command easily. 
@janos , wdyt?

**Comment by paxthemax** [comment]
@Eknir Yes, I saw the comment in the issue regarding this, but I wasn't sure where to take it. Should we return it to `stdout`?

**Comment by janos** [comment]
@Eknir returning complete keys would mean printing them to stdout. Would that help in some cases @vandot?

**Comment by Eknir** [comment]
LGTM!
We can do a follow-up PR to also print to stdout

**Review by Eknir — APPROVED** [review]

**Pull request merged**
