### PR TITLE
bump bee version

### PR DESCRIPTION
**Pull request by acud**

### CODE REVIEW

**Review by janos — APPROVED** [review]

**Review by svetomir — COMMENTED** [review]
What do you think about setting it to 0.2.1 so we can have new tag (0.2.1) with it?

**Comment by acud** [comment]
@svetomir i was actually thinking to change it to 0.3.0 since we are technically now already on `0.3.0-unstable`

**Comment by svetomir** [comment]
> @svetomir i was actually thinking to change it to 0.3.0 since we are technically now already on `0.3.0-unstable`

That works, too :) @janos @vandot What do you think about it?

**Comment by janos** [comment]
@svetomir @acud makes sense. I had the same thought.

**Comment by acud** [comment]
pushed to `0.3.0`. ok to merge?

**Review by svetomir — APPROVED** [review]

**Review by janos — APPROVED** [review]

**Pull request merged**
