### PR TITLE
sign checksums.txt with gpg key

### PR DESCRIPTION
**Pull request by vandot**
Releases are signed using the project GPG key with key-ID `65207E638F11F36B` and fingerprint `C07E 8D0F CC74 221F 2C24  1EEE 6520 7E63 8F11 F36B`. The key can be fetched from most keyservers.
```
gpg --recv-keys 65207E638F11F36B
```
Set trust for the key
```
$ gpg --edit-key 65207E638F11F36B
gpg> trust
pub  rsa4096/65207E638F11F36B
     created: 2021-04-19  expires: 2022-04-19  usage: C
     trust: ultimate      validity: ultimate
sub  rsa4096/60760BAEEDEFB3E6
     created: 2021-04-19  expires: 2022-04-19  usage: S
[ultimate] (1). ethersphere-bee (github.com/ethersphere/bee project key) <security@ethswarm.org>

Please decide how far you trust this user to correctly verify other users' keys
(by looking at passports, checking fingerprints from different sources, etc.)

  1 = I don't know or won't say
  2 = I do NOT trust
  3 = I trust marginally
  4 = I trust fully
  5 = I trust ultimately
  m = back to the main menu

Your decision? 5
Do you really want to set this key to ultimate trust? (y/N) y
gpg> quit
```
Download and verify the signature on the checksum file:
```
gpg --verify bee_v0.6.0_checksums.txt.sig bee_v0.6.0_checksums.txt
```
After verifying the checksum file signature use `shasum` to verify the checksums of the release artifacts:
```
shasum --check bee_v0.6.0_checksums.txt
```

### CODE REVIEW

**Review by acud — APPROVED** [review]
very cool

**Review by svetomir — APPROVED** [review]

**Comment by attila-lendvai** [comment]
my gpg refuses to import it:

```
$ gpg --recv-keys 65207E638F11F36B
gpg: key 65207E638F11F36B: no user ID
gpg: Total number processed: 1
```

**Comment by vandot** [comment]
@attila-lendvai I agree with you, this was initial implementation, there is an idea to improve it

**Comment by vandot** [comment]
Key is updated, now use `gpg --keyserver keyserver.ubuntu.com --recv-keys 79F204E0D9394EC6` to fetch it
Later `gpg --edit-key 79F204E0D9394EC6` to set the trust

**Pull request merged**
