### PR TITLE
update modules

### PR DESCRIPTION
**Pull request by janos**
This PR updates dependencies to new versions. It is done all in one bunch for simplicity, but in the future we should keep our dependencies updated in more granular matter.

### CODE REVIEW

**Comment by janos** [comment]
Test failed with:

```
=== RUN   TestTags/tag-counters
##[error]    TestTags/tag-counters: tag_test.go:217: Invalid counters
```

https://github.com/ethersphere/bee/runs/742516278#step:12:76

This PR does not change this part of the code. We would need to investigate if `TestTags/tag-counters` is flaky.

**Comment by acud** [comment]
I also have this flaking on my PR

**Comment by acud** [comment]
@janos i retriggerred the tests after the initial failure and it failed again.
now rebased and forced pushed the branch to see if the PR i merged gives more info

**Comment by acud** [comment]
hm. now more fun stuff coming up:
```
=== RUN   TestConnectDisconnectOnAllAddresses
##[error]    TestConnectDisconnectOnAllAddresses: connections_test.go:174: failed to dial QmfUTGpHQ8PipwffAngbn46u1pdER9y5L51ePePbFHHSjv: all dials failed
          * [/ip4/10.79.1.181/udp/51912/quic] context deadline exceeded
--- FAIL: TestConnectDisconnectOnAllAddresses (9.26s)
=== RUN   TestDoubleConnectOnAllAddresses
##[error]    TestDoubleConnectOnAllAddresses: connections_test.go:203: failed to dial QmbkE5Q3AGutStpf2xwrbEAV84teh1ZT64KpWMhq6Aikfy: all dials failed
          * [/ip4/10.79.1.181/udp/51155/quic] context ...
```

**Comment by acud** [comment]
connection tests are failing persistently.
linter now too on windows:
```
which golangci-lint || ( cd /tmp && GO111MODULE=on go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@v1.24.0 )
/c/Users/runneradmin/go/bin/golangci-lint
golangci-lint run
runtime: VirtualAlloc of 8192 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw(0x10676c6, 0xd)
	C:/hostedtoolcache/windows/go/1.14.4/x64/src/runtime/panic.go:1116 +0x79
runtime.sysUsed(0xc1afd68000, 0x2000)
	C:/hostedtoolcache/windows/go/1.14.4/x64/src/runtime/mem_windows.go:83 +0x230
runtime.(*mheap).allocSpan(0x1aab980, 0x1, 0x288a1e00, 0x1ac08e8, 0x44857af8)
	C:/hostedtoolcache/windows/go/1.14.4/x64/src/runtime/mheap.go:1229 +0x3cb
runtime.(*mheap).alloc.func1()
	C:/hostedtoolcache/windows/go/1.14.4/x64/src/runtime/mheap.go:871 +0x6b
runtime.systemstack(0x0)
	C:/hostedtoolcache/windows/go/1.14.4/x64/src/runtime/asm_amd64.s:370 +0x6b
runtime.mstart()
	C:/hostedtoolcache/windows/go/1.14.4/x64/src/runtime/proc.go:1041
```

**Comment by janos** [comment]
Let's put this PR **on hold** until the alpha is released as some behaviours are changed even libp2p APIs are mostly the same.

**Comment by acud** [comment]
cool :+1:

**Comment by janos** [comment]
This PR has been tested on private integration cluster using beekeeper and also manually on the public cluster.

**Pull request merged**
