### PR TITLE
Correct gc_size metric value

### PR DESCRIPTION
**Pull request by ldeffenb**
As described in #1411 This fixes the bee_localstore_gc_size metric to track the actual gcSize rather than just an incrementing mirror of bee_localstore_gc_count.

### CODE REVIEW

**Comment by ldeffenb** [comment]
Looks like I'm zero for 2 on my PR.  But on this one, I don't know what "`gofmt`-ed with `-s` (gofmt)" means, but apparently it doesn't like my simple typecast?

**Review by acud — APPROVED** [review]
:+1:

**Comment by acud** [comment]
> Looks like I'm zero for 2 on my PRs. But on this one, I don't know what "`gofmt`-ed with `-s` (gofmt)" means, but apparently it doesn't like my simple typecast?

You need to use the `gofmt` utility. It cleans up the code, usually it's about a tab or an excess space EOL. Use `gofmt` or `goimports`

**Comment by ldeffenb** [comment]
This is superseded by #1417 .  Still learning my way around git and github and managed to do this PR against my master instead of the branch.  The new one will hopefully fly.

**Pull request closed without merging**
