### PR TITLE
fix(pusher): dont increment missing tags

### PR DESCRIPTION
**Pull request by acud**
This fixes a spurious error that is incorrectly logged when pushing chunks that were uploaded through the chunks api without a tag. This is visible in the integration tests since some of the tests use the chunks api directly, and therefore the pusher incorrectly logs that an error has occurred, since no tag is associated with the chunk.

This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2081)

### CODE REVIEW

**Review by mrekucci — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2081#-:-Mc9gcoz5HIwWb1fguli:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud)

**Review by zelig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2081)* status: all files reviewed, 1 unresolved discussion (waiting on @acud)

___
*[pkg/pusher/pusher.go, line 209 at r1](https://reviewable.io/reviews/ethersphere/bee/2081#-McDSfea9NQExnxvT4M9:-McDSfea9NQExnxvT4MA:bu22cgv) ([raw file](https://github.com/ethersphere/bee/blob/93590a6b2ac50cc08eee0326d8476f5b316f542e/pkg/pusher/pusher.go#L209)):*
> ```Go
> 					return
> 				}
> 				if ch.TagID() > 0 {
> ```

why not at other places when tags are incremented?

**Review by acud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2081)* status: all files reviewed, 1 unresolved discussion (waiting on @zelig)

___
*[pkg/pusher/pusher.go, line 209 at r1](https://reviewable.io/reviews/ethersphere/bee/2081#-McDSfea9NQExnxvT4M9:-McDa60yCMZRI3oNGkWw:bw765w5) ([raw file](https://github.com/ethersphere/bee/blob/93590a6b2ac50cc08eee0326d8476f5b316f542e/pkg/pusher/pusher.go#L209)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

why not at other places when tags are incremented?
</blockquote></details>

because I cannot find this same problem elsewhere

**Review by zelig — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2081)* status: all files reviewed, 1 unresolved discussion (waiting on @zelig)

**Pull request merged**
