### PR TITLE
feat: node warmup time for pull/pushsync protocols

### PR DESCRIPTION
**Pull request by istae**
Node warmup delay for pull/pushsync protocols #2048

Depends on https://github.com/ethersphere/beekeeper/pull/155

This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2050)

### CODE REVIEW

**Review by acud — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2050)* status: all files reviewed, 5 unresolved discussions (waiting on @esadakar and @zelig)

___
*[pkg/node/node.go, line 182 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-Mbr4D8G0OYxYrceA2yV:-Mbr4D8H5sMwz-c3Rb7c:bqjjewf) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/node/node.go#L182)):*
> ```Go
> 		warmupTime = time.Hour
> 	}
> ```

maybe we should move `time.Hour` to a `const maxWarmupTime` and return an error here?
___
*[pkg/puller/puller.go, line 76 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-Mbr4PVR3uS8RVPpAPgx:-Mbr4PVR3uS8RVPpAPgy:bbkfz0w) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/puller/puller.go#L76)):*
> ```Go
> 
> 		bins:       bins,
> 		warmupTime: warmupTime,
> ```

no need for the extra field, you can simply call `go p.manage(warmupTime)`
___
*[pkg/pusher/pusher.go, line 64 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-Mbr5CUO8tX5mez10UQF:-Mbr5CUO8tX5mez10UQG:bps1s89) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/pusher/pusher.go#L64)):*
> ```Go
> 		quit:              make(chan struct{}),
> 		chunksWorkerQuitC: make(chan struct{}),
> 		warmupTime:        warmupTime,
> ```

here too
___
*[pkg/pushsync/pushsync.go, line 48 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-Mbr5NGB9grD108M0fEK:-Mbr5NGB9grD108M0fEL:bd5fcz) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/pushsync/pushsync.go#L48)):*
> ```Go
> 	ErrOutOfDepthReplication = errors.New("replication outside of the neighborhood")
> 	ErrNoPush                = errors.New("could not push chunk")
> 	ErrWarmup                = errors.New("could not push chunk")
> ```

error description should be changed
___
*[pkg/pushsync/pushsync.go, line 205 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-Mbr5esF6LsbpWY6M_yC:-Mbr5esF6LsbpWY6M_yD:b-qws6fd) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/pushsync/pushsync.go#L205)):*
> ```Go
> 
> 			if time.Now().Before(ps.warmupPeriod) {
> 				_ = stream.Reset()
> ```

since the stream will be reset anyway when the defer statement at the beginning of the `handler` executes, it is enough to just `return ErrWarmup`

**Review by zelig — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2050)* status: all files reviewed, 8 unresolved discussions (waiting on @acud and @esadakar)

___
*[pkg/node/node.go, line 178 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-MbsIo006guwtVqx1EOI:-MbsIo006guwtVqx1EOJ:b-6o3in0) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/node/node.go#L178)):*
> ```Go
> 
> 	// upperbound on warmupTime for push/pullsync protocols
> 	warmupTime := o.WarmupTime
> ```

why need this complexity, if some set it long its their problem
___
*[pkg/puller/puller.go, line 76 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-Mbr4PVR3uS8RVPpAPgx:-MbsJ0519jF2hAtGW9Wb:b2ngthx) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/puller/puller.go#L76)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

no need for the extra field, you can simply call `go p.manage(warmupTime)`
</blockquote></details>

+1 
___
*[pkg/puller/puller.go, line 103 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-MbsJ6UdAVWf7xRpe3xy:-MbsJ6UdAVWf7xRpe3xz:bwlqx61) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/puller/puller.go#L103)):*
> ```Go
> 	}()
> 
> 	// wait for warmup duration to complete
> ```

this should only apply to storer nodes.  lightnodes do not need to wait to push
___
*[pkg/pusher/pusher.go, line 94 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-MbsJcD89aY8tZrnoxjO:-MbsJcD89aY8tZrnoxjP:bg5ksco) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/pusher/pusher.go#L94)):*
> ```Go
> 	}()
> 
> 	// wait for warmup duration to complete
> ```

only for storer nodes

**Review by esadakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2050)* status: 5 of 9 files reviewed, 8 unresolved discussions (waiting on @acud and @zelig)

___
*[pkg/node/node.go, line 178 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-MbsIo006guwtVqx1EOI:-Mbu70V59ltBsEJvfgGn:b5xf54c) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/node/node.go#L178)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

why need this complexity, if some set it long its their problem
</blockquote></details>

Fair enough. Thanks.
___
*[pkg/node/node.go, line 182 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-Mbr4D8G0OYxYrceA2yV:-Mbu72eKDRD9SBHJqjpa:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/node/node.go#L182)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

maybe we should move `time.Hour` to a `const maxWarmupTime` and return an error here?
</blockquote></details>

Done.
___
*[pkg/puller/puller.go, line 76 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-Mbr4PVR3uS8RVPpAPgx:-Mbu73Pq2lt-wMBxdBCl:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/puller/puller.go#L76)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

+1 
</blockquote></details>

Done.
___
*[pkg/puller/puller.go, line 103 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-MbsJ6UdAVWf7xRpe3xy:-Mbu73zK1gSAI4g21hy6:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/puller/puller.go#L103)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

this should only apply to storer nodes.  lightnodes do not need to wait to push
</blockquote></details>

Done.
___
*[pkg/pusher/pusher.go, line 64 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-Mbr5CUO8tX5mez10UQF:-Mbu762qA4chG73xyyqq:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/pusher/pusher.go#L64)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

here too
</blockquote></details>

Done.
___
*[pkg/pusher/pusher.go, line 94 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-MbsJcD89aY8tZrnoxjO:-Mbu77IJ5iSUaeo8FtTd:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/pusher/pusher.go#L94)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

only for storer nodes
</blockquote></details>

Done.
___
*[pkg/pushsync/pushsync.go, line 48 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-Mbr5NGB9grD108M0fEK:-Mbu783ECj1QJBeB5uuN:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/pushsync/pushsync.go#L48)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

error description should be changed
</blockquote></details>

Done.
___
*[pkg/pushsync/pushsync.go, line 205 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-Mbr5esF6LsbpWY6M_yC:-Mbu7mJhDmcsqOo3ym_r:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/pushsync/pushsync.go#L205)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

since the stream will be reset anyway when the defer statement at the beginning of the `handler` executes, it is enough to just `return ErrWarmup`
</blockquote></details>

Done.

**Review by acud — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2050#-:-MbuD5I59yBKtFk1gR8L:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @zelig)

**Review by zelig — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2050)* status: all files reviewed, 3 unresolved discussions (waiting on @zelig)

**Review by zelig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2050)* status: all files reviewed, 3 unresolved discussions (waiting on @esadakar and @zelig)

___
*[pkg/node/node.go, line 178 at r1](https://reviewable.io/reviews/ethersphere/bee/2050#-MbsIo006guwtVqx1EOI:-Mbur9ix1RN9wjxdgp4E:br4ltok) ([raw file](https://github.com/ethersphere/bee/blob/853713201ca48d74d7d379735c73970338e5a5d1/pkg/node/node.go#L178)):*
<details><summary><i>Previously, esadakar (Esad Akar) wrote…</i></summary><blockquote>

Fair enough. Thanks.
</blockquote></details>

cool now

**Comment by acud** [comment]
@esadakar I think the integration tests are failing because of this right?

**Pull request merged**
