### PR TITLE
set chunk as synced only by push sync

### PR DESCRIPTION
**Pull request by janos**
This PR addresses the problem of data integrity with relation to setting chunk as synced by both pull and push syncing while garbage collection can remove a chunk from retrieval index (as synced by push sync) and leave its address in push index.

As discussed with @zelig and @acud, the chunk should be set as synced only by push sync.

### CODE REVIEW

**Comment by janos** [comment]
This PR is ready for a review bit it is blocked by issues with the gc integration test https://github.com/ethersphere/bee/runs/1357493088?check_suite_focus=true#step:29:11, not to interfere with the progress on fixing that test.

**Comment by acud** [comment]
@janos i looked at the link you posted and it seemed to have passed eventually right? i remember tinkering around with it a few days ago and it eventually came back into life after a few restarts. i guess this is a flake regarding the amount of data we put into the cluster with the gc test. it is true that currently on `master`, having an item in gc index depends on the fact that we must sync the data (or at least offer it). are the slash commands failing now repeatedly?

**Comment by zelig** [comment]
this should sort out https://github.com/ethersphere/bee/issues/819 and #894

**Review by zelig — APPROVED** [review]
LGTM 
this needs to be complemented by renewing accessTimestamp for newly  synced chunks

**Review by acud — APPROVED** [review]
Looks good :+1:

**Comment by janos** [comment]
> LGTM
> this needs to be complemented by renewing accessTimestamp for newly synced chunks

Thanks. This is actually already the case in the master https://github.com/ethersphere/bee/blob/master/pkg/localstore/mode_set.go#L277. We are setting new time on every sync.

**Comment by janos** [comment]
@acud it is still failing on the run command, also failed and succeeded once on the master branch.

I am not sure if this PR should be merged in regards the gc integration test. It seems still flaky.

**Comment by acud** [comment]
@janos i think https://github.com/ethersphere/beekeeper/pull/64 should improve this

**Comment by janos** [comment]
Beekeeper tests re now passing. Thanks @acud.

**Pull request merged**
