### PR TITLE
feat: p2p disconnect with reason

### PR DESCRIPTION
**Pull request by aloknerurkar**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2471)

### CODE REVIEW

**Comment by acud** [comment]
@aloknerurkar could we also have the signature change on the `Blocklist` method on the `Disconnecter` interface? (in the `p2p.go` file)

**Comment by aloknerurkar** [comment]
@acud The sonar cloud check is complaining about code duplication in the `accounting_test.go` file. These don't seem as straightforward. Not sure if we should address this.

**Review by acud — CHANGES_REQUESTED** [review]
nice! i have a few comments

> Reviewed 7 of 11 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2471#-:-Mj3fPQ11HkFxC9H51s_:b-8vkznp)* status: all files reviewed, 7 unresolved discussions (waiting on @aloknerurkar and @metacertain)

___
*[pkg/debugapi/peer.go, line 39 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3dPOW2MLvcZuwKGJP:-Mj3dPOW2MLvcZuwKGJQ:b-8msohs) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/debugapi/peer.go#L39)):*
> ```Go
> 
> 	if err := s.topologyDriver.Connected(r.Context(), p2p.Peer{Address: bzzAddr.Overlay}, true); err != nil {
> 		_ = s.p2p.Disconnect(bzzAddr.Overlay, "failed to process connection notification")
> ```

failed to notify topology?
___
*[pkg/p2p/libp2p/libp2p.go, line 353 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3eIea0eeuPY9g_mX0:-Mj3eIea0eeuPY9g_mX1:b-2wuity) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/p2p/libp2p/libp2p.go#L353)):*
> ```Go
> 		s.logger.Debugf("stream handler: could not close stream %s: %v", overlay, err)
> 		s.logger.Errorf("stream handler: unable to handshake with peer %v", overlay)
> 		_ = s.Disconnect(overlay, "unable to handshake")
> ```

here maybe it would be good to disambiguate this error message from the line above, so maybe `could not fully close stream on handshake`
___
*[pkg/p2p/libp2p/libp2p.go, line 516 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3ezv93lWVuL5AHPFJ:-Mj3ezvACzYbdLK8udJb:b-rila8r) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/p2p/libp2p/libp2p.go#L516)):*
> ```Go
> 						logger.Errorf("unable to blocklist peer %v", peerID)
> 					}
> 					logger.Tracef("handler(%s): blocklisted %s reason %s", p.Name, overlay.String(), bpe.Error())
> ```

wherever we have "reason" maybe it would be nice to add a colon like, `reason: %v`
___
*[pkg/p2p/libp2p/libp2p.go, line 559 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3f4nL5AndLTCpHOMF:-Mj3f4nL5AndLTCpHOMG:bps1s89) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/p2p/libp2p/libp2p.go#L559)):*
> ```Go
> 
> func (s *Service) Blocklist(overlay swarm.Address, duration time.Duration, reason string) error {
> 	s.logger.Tracef("libp2p blocklist: peer %s for %v reason %s", overlay.String(), duration, reason)
> ```

here too
___
*[pkg/p2p/libp2p/libp2p.go, line 562 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3f6QZ-yVh1RnfTFPy:-Mj3f6QZ-yVh1RnfTFPz:b-kvr48k) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/p2p/libp2p/libp2p.go#L562)):*
> ```Go
> 	if err := s.blocklist.Add(overlay, duration); err != nil {
> 		s.metrics.BlocklistedPeerErrCount.Inc()
> 		_ = s.Disconnect(overlay, "blocklisting peer")
> ```

here it would be good to disambiguate the reason from the one below
___
*[pkg/p2p/libp2p/libp2p.go, line 655 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3fBSy4Rtw_ASUEDjr:-Mj3fBSzBlYKqmjWLReP:bps1s89) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/p2p/libp2p/libp2p.go#L655)):*
> ```Go
> 	if exists := s.peers.addIfNotExists(stream.Conn(), overlay, i.FullNode); exists {
> 		if err := handshakeStream.FullClose(); err != nil {
> 			_ = s.Disconnect(overlay, "failed closing handshake")
> ```

here too
___
*[pkg/p2p/libp2p/libp2p.go, line 705 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3fEghALMMgYm9L2j2:-Mj3fEghALMMgYm9L2j3:b-muzk0a) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/p2p/libp2p/libp2p.go#L705)):*
> ```Go
> 	s.metrics.DisconnectCount.Inc()
> 
> 	s.logger.Debugf("libp2p disconnect: disconnecting peer %s reason %s", overlay, reason)
> ```

here also, would be good to have a colon

**Review by aloknerurkar — COMMENTED** [review]
> Dismissed @acud from 7 discussions.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2471)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @acud and @metacertain)

___
*[pkg/debugapi/peer.go, line 39 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3dPOW2MLvcZuwKGJP:-Mj3ipuX-YjcHh8DQWVw:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/debugapi/peer.go#L39)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

failed to notify topology?
</blockquote></details>

Done.
___
*[pkg/p2p/libp2p/libp2p.go, line 353 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3eIea0eeuPY9g_mX0:-Mj3ir7G-O5jfwgaDFXm:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/p2p/libp2p/libp2p.go#L353)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

here maybe it would be good to disambiguate this error message from the line above, so maybe `could not fully close stream on handshake`
</blockquote></details>

Done.
___
*[pkg/p2p/libp2p/libp2p.go, line 516 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3ezv93lWVuL5AHPFJ:-Mj3jI3S6j_hO3mlKbnd:bllnrkp) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/p2p/libp2p/libp2p.go#L516)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

wherever we have "reason" maybe it would be nice to add a colon like, `reason: %v`
</blockquote></details>

This is actually duplicate. I added this before we added the reason to the function call. Now we log it inside the Blocklist function call.
___
*[pkg/p2p/libp2p/libp2p.go, line 559 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3f4nL5AndLTCpHOMF:-Mj3jT87AtAoMlkxCD40:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/p2p/libp2p/libp2p.go#L559)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

here too
</blockquote></details>

Done.
___
*[pkg/p2p/libp2p/libp2p.go, line 562 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3f6QZ-yVh1RnfTFPy:-Mj3jTwo4Gpwkr1E5hY1:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/p2p/libp2p/libp2p.go#L562)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

here it would be good to disambiguate the reason from the one below
</blockquote></details>

Done.
___
*[pkg/p2p/libp2p/libp2p.go, line 655 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3fBSy4Rtw_ASUEDjr:-Mj3kxfeDVFymVoDDg__:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/p2p/libp2p/libp2p.go#L655)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

here too
</blockquote></details>

Done.
___
*[pkg/p2p/libp2p/libp2p.go, line 705 at r3](https://reviewable.io/reviews/ethersphere/bee/2471#-Mj3fEghALMMgYm9L2j2:-Mj3l1bdCVNQGC6ds7DD:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/723e876b73b1a3d3b61edcfaa58838789723df9e/pkg/p2p/libp2p/libp2p.go#L705)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

here also, would be good to have a colon
</blockquote></details>

Done.

**Review by acud — APPROVED** [review]
thank you :pray: 

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2471#-:-Mj3sayv2pxViNoKa_S5:b-w5ck8y)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @metacertain)

**Review by metacertain — APPROVED** [review]
Great!

**Pull request merged**
