### PR TITLE
feat: threshold upgrades and request ahead-of-time

### PR DESCRIPTION
**Pull request by metacertain**
**Note: this is a semi-breaking change, making light nodes with old versions unable to connect to this version, as the old minimum payment threshold expectation wouldn't be met anymore by the threshold given by new full nodes. 
To be merged & released with more breaking changes**

Changes part 1

This PR introduces a mechanism, that favors long-standing connections by gradually upgrading payment thresholds after an amount of traffic is served for and settled by a peer.

The milestone for upgrading a payment threshold is after each 100 seconds worth of refreshment rate being settled (by either time based or monetary settlements).
The upgrade of the payment threshold is an increase of 1 second worth of refreshment rate per upgrade.
After the first 18 milestones the increase slows down to a logarithmic rate, by setting the next milestone at twice of the current milestones accumulated traffic settled.

When a peer is newly connected, it receives a default payment threshold once again, so that disconnections / reconnections are not incentivized.

The PR introduces individual payment thresholds given to peers.
The PR also includes relaying the information about whether a peer is a full node to accounting from pseudosettlements, in order to differentiate traffic milestones for threshold upgrades between light nodes and full nodes.
The PR introduces differentiation of initial payment thresholds given to light nodes and full nodes.

Changes part 2:

Decrease default payment thresholds to 10%

Changes part 3:

in order to counteract queue throttling effects of requests served with delays, increase reserve and disconnect limits from
payment threshold,
(1 + tolerance%) * payment threshold

to

payment threshold + ("seconds since last refreshment sent" * "refreshment rate" )
(1 + tolerance%) * payment threshold + ("seconds since last refreshment received" * "refreshment rate")

with "seconds since last refreshment" term capped at 1.

this intends to circumvent a situation where reserve is jammed by timing out requests, and no debt is formed, so no more requests could be queried regardless of refresh rate.

Changes part 4:

hotfix for NTP differences related problems resulting in recipient of a refreshment refusing refreshment as it is "too soon"

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2904)

### CODE REVIEW

**Review by mrekucci — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2904)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @metacertain)

___
*[`pkg/accounting/accounting_test.go` line 779 at r1](https://reviewable.io/reviews/ethersphere/bee/2904#-N0_rn-LBfIgqzTmITL8:-N0_rn-M7zsOgaFkwv6Q:bha06mj) ([raw file](https://github.com/ethersphere/bee/blob/56a0a51b72a23c6b601ab1a55344857a4b845e2f/pkg/accounting/accounting_test.go#L779)):*
> ```Go
> 			t.Fatalf("wrong peer address got %v wanted %v", call.peer, peer1Addr)
> 		}
> 	case <-time.After(3 * time.Second):
> ```

A comment would be nice why it is 3 seconds.

**Review by notanatol — APPROVED** [review]

**Review by acud — CHANGES_REQUESTED** [review]
looks good, but I find the time representations here confusing. They are represented with various types which makes a lot of overhead of reading but also interacting with the values. Not sure why the standard-library types (`time.Time`, `time.Duration`) weren't used and I think that leveraging them would make this much easier and nicer to read.

> Reviewed 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2904#-:-N2Qctd818RTCC-ERANd:b-fc5nle)* status: all files reviewed, 9 unresolved discussions (waiting on @metacertain)

___
*[`pkg/accounting/accounting.go` line 270 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2Q_RXpBXdLXQT541ll:-N2Q_RXpBXdLXQT541lm:bevbw7w) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L270)):*
> ```Go
> 	}
> 
> 	timeElapsed := (a.timeNow().UnixMilli() - accountingPeer.refreshTimestamp) / 1000
> ```

I find this a bit confusing and not particularly readable. There are the `time.Time` and `time.Duration` types, why not use them?
___
*[`pkg/accounting/accounting.go` line 275 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2Q_uek6Y37GAYfelJ9:-N2Q_uek6Y37GAYfelJA:b-jkoybj) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L275)):*
> ```Go
> 	}
> 
> 	refreshDue := new(big.Int).Mul(big.NewInt(timeElapsed), a.refreshRate)
> ```

is `big.Int` needed to represent time? I believe that even the standard library represents `time.Time` in nanoseconds unix epoch with `uint64`. Again using the standard library native types here would be more readable and clear
___
*[`pkg/accounting/accounting.go` line 417 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2Qb0SC8rXMMK62jLxB:-N2Qb0SC8rXMMK62jLxC:bw6y4v5) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L417)):*
> ```Go
> 	// Don't do anything if there is no actual debt or no time passed since last refreshment attempt
> 	// This might be the case if the peer owes us and the total reserve for a peer exceeds the payment threshold.
> 	if paymentAmount.Cmp(new(big.Int).Mul(a.refreshRate, big.NewInt(2))) >= 0 {
> ```

significant change here with no comment update
___
*[`pkg/accounting/accounting.go` line 418 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2Qb4ew8k9gtmw4AX8f:-N2Qb4ew8k9gtmw4AX8g:bi5vsad) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L418)):*
> ```Go
> 	// This might be the case if the peer owes us and the total reserve for a peer exceeds the payment threshold.
> 	if paymentAmount.Cmp(new(big.Int).Mul(a.refreshRate, big.NewInt(2))) >= 0 {
> 		if timeElapsed > 999 {
> ```

this is obscure and needs a comment on why it is necessary
___
*[`pkg/accounting/accounting.go` line 466 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2QbFlX6oBKcI629Gth:-N2QbFlX6oBKcI629Gti:b-dpz13i) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L466)):*
> ```Go
> 		if a.payFunction != nil && !balance.paymentOngoing {
> 
> 			difference := now/1000 - balance.lastSettlementFailureTimestamp
> ```

more complexity relating to time unit conversions. at this point it is getting repeated and unclear which units what expects, what are the tolerances, etc. using time primitives will improve this significantly
___
*[`pkg/accounting/accounting.go` line 467 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2QbZ5hE1O_545FdLJt:-N2QbZ5hE1O_545FdLJu:b-lcq3k1) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L467)):*
> ```Go
> 
> 			difference := now/1000 - balance.lastSettlementFailureTimestamp
> 			if difference > failedSettlementInterval {
> ```

more of the same soup....
___
*[`pkg/accounting/accounting.go` line 593 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2QbiER4PzBcdhEHHgO:-N2QbiER4PzBcdhEHHgP:b-b1gvwk) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L593)):*
> ```Go
> 			paymentThresholdForPeer: new(big.Int).Set(a.paymentThreshold),
> 			disconnectLimit:         new(big.Int).Set(a.disconnectLimit),
> 			thresholdGrowAt:         new(big.Int).Set(a.thresholdGrowStep),
> ```

don't understand if this signifies a point in time or a threshold size step increase. type confusion 
___
*[`pkg/node/node.go` line 174 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2QcWx17oKU6gUeC1He:-N2QcWx17oKU6gUeC1Hf:b4ucfiz) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/node/node.go#L174)):*
> ```Go
> const (
> 	refreshRate                   = int64(4500000)
> 	lightFactor                   = 10
> ```

a comment on what this means would be nice
___
*[`pkg/node/node.go` line 667 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2Qcako1zevU4_enxTH:-N2Qcako1zevU4_enxTI:bkhvuer) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/node/node.go#L667)):*
> ```Go
> 	}
> 
> 	minThreshold := big.NewInt(2 * refreshRate)
> ```

these are also quite obscure. having more comments that would explain what this means and what are the repercussions would be nice

**Comment by metacertain** [comment]
> looks good, but I find the time representations here confusing. They are represented with various types which makes a lot of overhead of reading but also interacting with the values. Not sure why the standard-library types (`time.Time`, `time.Duration`) weren't used and I think that leveraging them would make this much easier and nicer to read.
> 
> > Reviewed 23 of 23 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2904#-:-N2Qctd818RTCC-ERANd:b-fc5nle)_ status: all files reviewed, 9 unresolved discussions (waiting on @metacertain)
> 
> _[`pkg/accounting/accounting.go` line 270 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2Q_RXpBXdLXQT541ll:-N2Q_RXpBXdLXQT541lm:bevbw7w) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L270)):_
> 
> > ```go
> > 	}
> > 
> > 	timeElapsed := (a.timeNow().UnixMilli() - accountingPeer.refreshTimestamp) / 1000
> > ```
> 
> I find this a bit confusing and not particularly readable. There are the `time.Time` and `time.Duration` types, why not use them?
> 

attempted to disambiguate by naming

> _[`pkg/accounting/accounting.go` line 275 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2Q_uek6Y37GAYfelJ9:-N2Q_uek6Y37GAYfelJA:b-jkoybj) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L275)):_
> 
> > ```go
> > 	}
> > 
> > 	refreshDue := new(big.Int).Mul(big.NewInt(timeElapsed), a.refreshRate)
> > ```
> 
> is `big.Int` needed to represent time? I believe that even the standard library represents `time.Time` in nanoseconds unix epoch with `uint64`. Again using the standard library native types here would be more readable and clear

big int conversion is necessary for input for big int operations

> 
> _[`pkg/accounting/accounting.go` line 417 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2Qb0SC8rXMMK62jLxB:-N2Qb0SC8rXMMK62jLxC:bw6y4v5) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L417)):_
> 
> > ```go
> > 	// Don't do anything if there is no actual debt or no time passed since last refreshment attempt
> > 	// This might be the case if the peer owes us and the total reserve for a peer exceeds the payment threshold.
> > 	if paymentAmount.Cmp(new(big.Int).Mul(a.refreshRate, big.NewInt(2))) >= 0 {
> > ```
> 
> significant change here with no comment update

added comment

> 
> _[`pkg/accounting/accounting.go` line 418 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2Qb4ew8k9gtmw4AX8f:-N2Qb4ew8k9gtmw4AX8g:bi5vsad) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L418)):_
> 
> > ```go
> > 	// This might be the case if the peer owes us and the total reserve for a peer exceeds the payment threshold.
> > 	if paymentAmount.Cmp(new(big.Int).Mul(a.refreshRate, big.NewInt(2))) >= 0 {
> > 		if timeElapsed > 999 {
> > ```
> 
> this is obscure and needs a comment on why it is necessary

added comment

> 
> _[`pkg/accounting/accounting.go` line 466 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2QbFlX6oBKcI629Gth:-N2QbFlX6oBKcI629Gti:b-dpz13i) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L466)):_
> 
> > ```go
> > 		if a.payFunction != nil && !balance.paymentOngoing {
> > 
> > 			difference := now/1000 - balance.lastSettlementFailureTimestamp
> > ```
> 
> more complexity relating to time unit conversions. at this point it is getting repeated and unclear which units what expects, what are the tolerances, etc. using time primitives will improve this significantly
> 

attempted to disambiguate by naming

> _[`pkg/accounting/accounting.go` line 467 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2QbZ5hE1O_545FdLJt:-N2QbZ5hE1O_545FdLJu:b-lcq3k1) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L467)):_
> 
> > ```go
> > 			difference := now/1000 - balance.lastSettlementFailureTimestamp
> > 			if difference > failedSettlementInterval {
> > ```
> 
> more of the same soup....

attempted to disambiguate by naming

> 
> _[`pkg/accounting/accounting.go` line 593 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2QbiER4PzBcdhEHHgO:-N2QbiER4PzBcdhEHHgP:b-b1gvwk) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/accounting/accounting.go#L593)):_
> 
> > ```go
> > 			paymentThresholdForPeer: new(big.Int).Set(a.paymentThreshold),
> > 			disconnectLimit:         new(big.Int).Set(a.disconnectLimit),
> > 			thresholdGrowAt:         new(big.Int).Set(a.thresholdGrowStep),
> > ```
> 
> don't understand if this signifies a point in time or a threshold size step increase. type confusion

left as is for now

> 
> _[`pkg/node/node.go` line 174 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2QcWx17oKU6gUeC1He:-N2QcWx17oKU6gUeC1Hf:b4ucfiz) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/node/node.go#L174)):_
> 
> > ```go
> > const (
> > 	refreshRate                   = int64(4500000)
> > 	lightFactor                   = 10
> > ```
> 
> a comment on what this means would be nice

added comments

> 
> _[`pkg/node/node.go` line 667 at r2](https://reviewable.io/reviews/ethersphere/bee/2904#-N2Qcako1zevU4_enxTH:-N2Qcako1zevU4_enxTI:bkhvuer) ([raw file](https://github.com/ethersphere/bee/blob/7886b430f62a6da11989850d7cd586ffaedae8fc/pkg/node/node.go#L667)):_
> 
> > ```go
> > 	}
> > 
> > 	minThreshold := big.NewInt(2 * refreshRate)
> > ```
> 
> these are also quite obscure. having more comments that would explain what this means and what are the repercussions would be nice

yes this is not so obvious why necessary, also left as is now and to be cleaned up in a separate PR

**Review by notanatol — COMMENTED** [review]
> Reviewed 11 of 18 files at r3, 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2904)* status: 26 of 27 files reviewed, 9 unresolved discussions (waiting on @acud)

**Review by notanatol — APPROVED** [review]

**Pull request closed without merging**
