### PR TITLE
refactor: rename postage stamp response exists field to expired

### PR DESCRIPTION
**Pull request by mrekucci**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2371)

### CODE REVIEW

**Comment by acud** [comment]
The problem with this change is that there could be some time in which this will be a bit misleading.
When a batch is bought, the stamp issuer will be created, however until the listener picks up the batch from the chain, the postage package will not find the stamp, leading to an `Expired: true` here. So it might be a bit misleading. Not sure whether we should do the change as a result

**Comment by AuHau** [comment]
@acud hmm but during that time `usable` should be `false` right? So it could be indicating that if `usable = false` then `expired` is not really applicable?

**Comment by agazso** [comment]
> The problem with this change is that there could be some time in which this will be a bit misleading.
> When a batch is bought, the stamp issuer will be created, however until the listener picks up the batch from the chain, the postage package will not find the stamp, leading to an `Expired: true` here. So it might be a bit misleading. Not sure whether we should do the change as a result

To me this suggests that the logic for the `expired` property should include a `&& usable` so that it's not true when it's created. Otherwise this logic has to be done on the client side, and it will lead to very cryptic logic of `expired = !exists && usable` for every user of the postage stamps.

**Comment by acud** [comment]
@AuHau this is a debug endpoint and this specific field is needed to know whether a batch that we bought got evicted earlier than expected. since this is a debug endpoint i wouldn't try to cast everything into UX considerations and however higher-order presentation layers choose to interpret this field (if at all) is not really in scope for the endpoint to handle. on a later thought i might say it is just better to ignore this field and that we use it for internal debugging purposes only

**Comment by acud** [comment]
Using the `usable` field should suffice here, and we (the bee dev team) should take care that as long as usable is true, the `exists` shoud always be true too

**Review by notanatol — APPROVED** [review]

**Review by aloknerurkar — APPROVED** [review]

**Comment by AuHau** [comment]
Could we get this in before the release? Otherwise it will be breaking change later on...

**Comment by mrekucci** [comment]
After internal discussion, we came to the conclusion that the `expired` doesn't reflect the property of this field and that `Usable` field should be used for that case #2390

**Pull request closed without merging**
