### PR TITLE
feat: allow separate accounting store

### PR DESCRIPTION
**Pull request by ralph-pichler**
related to https://github.com/ethersphere/bee/issues/968

This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2109)

### CODE REVIEW

**Comment by Eknir** [comment]
Why would you want to do this?

**Comment by ralph-pichler** [comment]
@Eknir so you can reset statestore / localstore without resettting private key / chequebooks.

**Comment by Eknir** [comment]
that's useful :+1:

**Comment by ldeffenb** [comment]
> @Eknir so you can reset statestore / localstore without resettting private key / chequebooks.

But isn't the checkbook address stored in statestore?

**Review by acud — APPROVED** [review]

**Review by mrekucci — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ralph-pichler)

___
*[pkg/node/statestore.go, line 40 at r1](https://reviewable.io/reviews/ethersphere/bee/2109#-McTorJrBjKc1dt2iwf5:-McTorJrBjKc1dt2iwf6:b2gi3er) ([raw file](https://github.com/ethersphere/bee/blob/06bc65cc269196f98f5c639332ef8eb10b48139b/pkg/node/statestore.go#L40)):*
> ```Go
> 		return ret, nil
> 	}
> 	return leveldb.NewStateStore(filepath.Join(dataDir, "accountingstore"), log)
> ```

Would be nice to check the `dataDir` validity before passing it, e.g.:
```golang
dir, err := os.Stat(dataDir)
if err != nil {
	return fmt.Errorf("failed to open directory, error: %w", err)
}
if !dir.IsDir() {
	return fmt.Errorf("%q is not a directory", dir.Name())
}
```

**Pull request closed without merging**
