### PR TITLE
Export additional metrics

### PR DESCRIPTION
**Pull request by zbiljic**
While debugging "pushsync" package, I noticed that metrics are not exported. After including those to debug API, I also noticed some other seem to be missing from there. 

This change includes those missing metrics from other packages, and fixes names of metrics from `localstore` (discovered after metrics were added).

One remaining metric group that was not included here is from `shed` package. Since that is only internally used in `localstore`, different change would be needed to include it.
Since I am not totally sure about that package anyway, I have left it out. If someone thinks that it should be added, I can update this PR.

### CODE REVIEW

**Review by janos — APPROVED** [review]

**Comment by ldeffenb** [comment]
Still missing PushSyncPusher metrics unless I missed something?

**Comment by zbiljic** [comment]
> Still missing PushSyncPusher metrics unless I missed something?

You are correct.

**Review by acud — APPROVED** [review]
nice. shows to which extent we use metrics :D

**Comment by ldeffenb** [comment]
When we get to the backlog task in the roadmap, whoever gets assigned the following tasks should appreciate this:

create Bee specific dashboards in Grafana
create dashboards with Beekeeper metrics in Grafana

At least, I assume Grafana will be consuming the Prometheus metrics.

**Pull request merged**
