### PR TITLE
feat: extend information returned by GET /stamps

### PR DESCRIPTION
**Pull request by mrekucci**
On top of the current information, the returned data are
extended by: label, depth, amount, bucketDepth,
blockNumber, and immutableFlag.

#1971

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2051)

### CODE REVIEW

**Review by acud — APPROVED** [review]
Looks good!

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2051#-:-MbuE11P8luzxlduSKH3:b-vs1prh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrekucci)

**Comment by mrekucci** [comment]
@agazso

**Review by janos — APPROVED** [review]
👍

**Review by zelig — APPROVED** [review]
> Reviewed 19 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2051)* status: all files reviewed, 1 unresolved discussion (waiting on @aloknerurkar, @anatollupacescu, and @mrekucci)

___
*[openapi/SwarmCommon.yaml, line 322 at r2](https://reviewable.io/reviews/ethersphere/bee/2051#-Mbz9lv6Dipdtd78SuYQ:-Mbz9lv6Dipdtd78SuYR:bmjgcfg) ([raw file](https://github.com/ethersphere/bee/blob/f83040b427adc685b4cd97372d3e8e330eb9b46b/openapi/SwarmCommon.yaml#L322)):*
> ```YAML
>         utilization:
>           type: integer
>         label:
> ```

bucketDepth and timestamp needed too, once indexed stamps PR merged

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2051)* status: 2 of 19 files reviewed, 1 unresolved discussion (waiting on @aloknerurkar, @anatollupacescu, and @zelig)

___
*[openapi/SwarmCommon.yaml, line 322 at r2](https://reviewable.io/reviews/ethersphere/bee/2051#-Mbz9lv6Dipdtd78SuYQ:-Mc9CNYO9zUmogGh_fSU:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/f83040b427adc685b4cd97372d3e8e330eb9b46b/openapi/SwarmCommon.yaml#L322)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

bucketDepth and timestamp needed too, once indexed stamps PR merged
</blockquote></details>

Done.

**Review by zelig — APPROVED** [review]
> Reviewed 19 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2051)* status: all files reviewed, 2 unresolved discussions (waiting on @aloknerurkar, @anatollupacescu, @mrekucci, and @zelig)

___
*[pkg/api/postage.go, line 107 at r3](https://reviewable.io/reviews/ethersphere/bee/2051#-McBAiPx0W5XIdo3k-L6:-McBAiPyBMNTLleiuHn_:b-l5cu6q) ([raw file](https://github.com/ethersphere/bee/blob/29d9144793c7836da0a68f2a9de3371a08b5df1d/pkg/api/postage.go#L107)):*
> ```Go
> 	Depth       uint8          `json:"depth"`
> 	Amount      *bigint.BigInt `json:"amount"`
> 	BucketDepth uint8          `json:"bucketDepth"`
> ```

immutable flag stsill missing

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2051)* status: all files reviewed, 2 unresolved discussions (waiting on @aloknerurkar, @anatollupacescu, and @zelig)

___
*[pkg/api/postage.go, line 107 at r3](https://reviewable.io/reviews/ethersphere/bee/2051#-McBAiPx0W5XIdo3k-L6:-McDJpKr9YkTixJIWGMx:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/29d9144793c7836da0a68f2a9de3371a08b5df1d/pkg/api/postage.go#L107)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

immutable flag stsill missing
</blockquote></details>

Done.

**Pull request merged**
