### PR TITLE
feat: rate limit hive broadcast calls

### PR DESCRIPTION
**Pull request by esadakar**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2235)

### CODE REVIEW

**Review by acud — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2235)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @esadakar and @janos)

___
*[pkg/hive/hive_test.go, line 101 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdISsVZ3ozs90shLXD4:-MdISsVZ3ozs90shLXD5:b90t1r0) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/hive/hive_test.go#L101)):*
> ```Go
> 	lastRec := rec[len(rec)-1]
> 
> 	if lastRec.Err() != nil {
> ```

how is it that the condition flips here?
___
*[pkg/ratelimit/ratelimit.go, line 1 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdIaGGj5TvQqC3dlzLJ:-MdIaGGj5TvQqC3dlzLK:bnf5whv) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/ratelimit/ratelimit.go#L1)):*
> ```Go
> package ratelimit
> ```

copyright missing, adding a top-level package comment would also be nice :+1: 
___
*[pkg/ratelimit/ratelimit.go, line 14 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdIWlIbEqtKSdIxFpV-:-MdIWlIbEqtKSdIxFpV0:b-5qfox3) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/ratelimit/ratelimit.go#L14)):*
> ```Go
> 
> type Limiter struct {
> 	mux     sync.Mutex
> ```

Nit, mux usually stands for a muxer while mtx would be the choice for mutex
___
*[pkg/ratelimit/ratelimit.go, line 28 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdI_lK041CDwcJB8h_f:-MdI_lK041CDwcJB8h_g:bcbcwby) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/ratelimit/ratelimit.go#L28)):*
> ```Go
> }
> 
> func (l *Limiter) Allow(key string, count int) error {
> ```

not sure if an error is needed in this context. maybe just a boolean would be enough and then you can just `return limiter.AllowN()`
___
*[pkg/ratelimit/ratelimit.go, line 46 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdIaQr_2WnfunAqaXYo:-MdIaQr_2WnfunAqaXYp:b-mox7y7) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/ratelimit/ratelimit.go#L46)):*
> ```Go
> }
> 
> func (l *Limiter) Clear(key string) {
> ```

documenting the exported methods would be nice

**Review by acud — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2235)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @esadakar and @janos)

___
*[pkg/hive/hive.go, line 207 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdIb1unDEWtT0UaYzN2:-MdIb1unDEWtT0UaYzN3:bi0j7r9) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/hive/hive.go#L207)):*
> ```Go
> 
> func (s *Service) disconnect(peer p2p.Peer) error {
> 	s.inLimiter.Clear(peer.Address.ByteString())
> ```

nitpicking, since both rate limiters are separated this is not an atomic operation and a data race is possible. it would be advisable to have a mutex in the hive struct for this purpose

**Comment by aloknerurkar** [comment]
___
*[pkg/hive/hive.go, line 164 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdM0Jn8DdcK_y9-nAxw:-MdM0Jn8DdcK_y9-nAxx:b8jpbve) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/hive/hive.go#L164)):*
> ```Go
> 	s.metrics.PeersHandlerPeers.Add(float64(len(peersReq.Peers)))
> 
> 	if err := s.inLimiter.Allow(peer.Address.ByteString(), len(peersReq.Peers)); err != nil {
> ```

So I am still not clear on the hive protocol. We are limiting the no of peers we send in the messages and not the actual requests we are sending.. is that correct?

**Review by esadakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2235)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @acud, @aloknerurkar, and @janos)

___
*[pkg/hive/hive.go, line 164 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdM0Jn8DdcK_y9-nAxw:-MdMFhgR7nMv1jiLJ1AP:b-v45qih) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/hive/hive.go#L164)):*
<details><summary><i>Previously, aloknerurkar wrote…</i></summary><blockquote>

So I am still not clear on the hive protocol. We are limiting the no of peers we send in the messages and not the actual requests we are sending.. is that correct?
</blockquote></details>

Each request carries a max of 30 peers. The sender rate limits himself as well the receiver. Ultimately, the number of requests are minimized. 
___
*[pkg/hive/hive.go, line 207 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdIb1unDEWtT0UaYzN2:-MdMFgZ87GTd4iC3pZYM:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/hive/hive.go#L207)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

nitpicking, since both rate limiters are separated this is not an atomic operation and a data race is possible. it would be advisable to have a mutex in the hive struct for this purpose 
</blockquote></details>

Done.
___
*[pkg/hive/hive_test.go, line 101 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdISsVZ3ozs90shLXD4:-MdMF7ej7p2h7PHs7rhM:bypde4v) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/hive/hive_test.go#L101)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

how is it that the condition flips here?
</blockquote></details>

The `outLimiter` limit the number of requests so the receiver should never send back an `rate limit exceeded error` .
___
*[pkg/ratelimit/ratelimit.go, line 1 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdIaGGj5TvQqC3dlzLJ:-MdMFOxmA7u88mDQunK0:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/ratelimit/ratelimit.go#L1)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

copyright missing, adding a top-level package comment would also be nice :+1: 
</blockquote></details>

Done.
___
*[pkg/ratelimit/ratelimit.go, line 28 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdI_lK041CDwcJB8h_f:-MdMFcyo0LtGuk11GEDJ:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/ratelimit/ratelimit.go#L28)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

not sure if an error is needed in this context. maybe just a boolean would be enough and then you can just `return limiter.AllowN()`
</blockquote></details>

Done.
___
*[pkg/ratelimit/ratelimit.go, line 46 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdIaQr_2WnfunAqaXYo:-MdMFdqc5zXGFxLomHHh:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/ratelimit/ratelimit.go#L46)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

documenting the exported methods would be nice
</blockquote></details>

Done.

**Review by janos — APPROVED** [review]
👍

**Review by acud — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2235)* status: all files reviewed, 4 unresolved discussions (waiting on @acud, @aloknerurkar, and @esadakar)

___
*[pkg/ratelimit/ratelimit.go, line 1 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdIaGGj5TvQqC3dlzLJ:-MdMXwyh65l5wrKVUTU-:b3bw7zy) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/ratelimit/ratelimit.go#L1)):*
<details><summary><i>Previously, esadakar (Esad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think that the package comment has to be right above the `package` keyword, without a whitespace
___
*[pkg/ratelimit/ratelimit.go, line 19 at r2](https://reviewable.io/reviews/ethersphere/bee/2235#-MdMYDH70eWX0R2bLh2E:-MdMYDH70eWX0R2bLh2F:b-4hiipo) ([raw file](https://github.com/ethersphere/bee/blob/c8281f93444c2e582e2e958c71045f160c151ea7/pkg/ratelimit/ratelimit.go#L19)):*
> ```Go
> )
> 
> var ErrRateLimitExceeded = errors.New("rate limit exceeded")
> ```

this is not used anymore

**Review by esadakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2235)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @acud and @aloknerurkar)

___
*[pkg/ratelimit/ratelimit.go, line 1 at r1](https://reviewable.io/reviews/ethersphere/bee/2235#-MdIaGGj5TvQqC3dlzLJ:-MdMtK6X2yipa5rUpVBY:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/6dea02bdee586764573ed6729337674ba37536a9/pkg/ratelimit/ratelimit.go#L1)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

I think that the package comment has to be right above the `package` keyword, without a whitespace
</blockquote></details>

Done.
___
*[pkg/ratelimit/ratelimit.go, line 19 at r2](https://reviewable.io/reviews/ethersphere/bee/2235#-MdMYDH70eWX0R2bLh2E:-MdMtKX126s60_mcP481:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/c8281f93444c2e582e2e958c71045f160c151ea7/pkg/ratelimit/ratelimit.go#L19)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

this is not used anymore
</blockquote></details>

Done.

**Review by acud — APPROVED** [review]
Thanks a million :)

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2235#-:-MdMxPR40cg8Tc6qoVE2:b-mlvf0s)* status: all files reviewed, 1 unresolved discussion (waiting on @aloknerurkar)

**Pull request merged**
