### PR TITLE
chore: update go-ethereum

### PR DESCRIPTION
**Pull request by ralph-pichler**
* update to go-ethereum `v1.10.3` (last version which works with clef for non-london txs, see ethereum/go-ethereum#23273)
* migrate some swap keys to a readable format
* make hex encoding in keys explicit as string formatting might change (and add explicit tests for this)
* accept eip-2930 txs in handshake

This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2342)

### CODE REVIEW

**Review by mrekucci — APPROVED** [review]
> Reviewed 10 of 12 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2342)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud)

___
*[pkg/transaction/backendsimulation/backend.go, line 163 at r2](https://reviewable.io/reviews/ethersphere/bee/2342#-MfbE99MDsUi6mkbgrMn:-MfbE99MDsUi6mkbgrMo:bnux12m) ([raw file](https://github.com/ethersphere/bee/blob/260908703f5ea3f26c92322b595c6fa7079714b0/pkg/transaction/backendsimulation/backend.go#L163)):*
> ```Go
> }
> 
> func (m *simulatedBackend) SuggestGasTipCap(ctx context.Context) (*big.Int, error) {
> ```

Since the `ctx` isn't used I'd suggest changing the name to `_` in order to explicitly signal that.

**Review by acud — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2342)* status: all files reviewed, 2 unresolved discussions (waiting on @ralph-pichler)

___
*[go.sum, line 794 at r2](https://reviewable.io/reviews/ethersphere/bee/2342#-MfbJYFx2ZwWjisog_yP:-MfbJYFx2ZwWjisog_yQ:b93tjhv) ([raw file](https://github.com/ethersphere/bee/blob/260908703f5ea3f26c92322b595c6fa7079714b0/go.sum#L794)):*
> ```
> github.com/mattn/go-runewidth v0.0.9 h1:Lm995f3rfxdpd6TSmuVCHVb/QhupuXlYr8sCI/QdE+0=
> github.com/mattn/go-runewidth v0.0.9/go.mod h1:H031xJmbD/WCDINGzjvQ9THkh0rPKHF+m2gUSrubnMI=
> github.com/mattn/go-sqlite3 v1.11.0/go.mod h1:FPy6KqzDD04eiIsT53CuJW3U88zkxoIYsOqkbpncsNc=
> ```

?? i wonder where is this coming from? did you `go mod tidy`?
___
*[pkg/statestore/leveldb/migration.go, line 138 at r2](https://reviewable.io/reviews/ethersphere/bee/2342#-MfbNnVZEgbELRNRwomc:-MfbNnVZEgbELRNRwomd:bx1v80l) ([raw file](https://github.com/ethersphere/bee/blob/260908703f5ea3f26c92322b595c6fa7079714b0/pkg/statestore/leveldb/migration.go#L138)):*
> ```Go
> 			if err = s.Put(fixed, chequebookAddress); err != nil {
> 				return err
> 			}
> ```

what about `s.Delete(key)`?

**Review by ralph-pichler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2342)* status: all files reviewed, 2 unresolved discussions (waiting on @acud)

___
*[go.sum, line 794 at r2](https://reviewable.io/reviews/ethersphere/bee/2342#-MfbJYFx2ZwWjisog_yP:-MfbRvZc5fJiHYaYSdyl:b-7cy2c2) ([raw file](https://github.com/ethersphere/bee/blob/260908703f5ea3f26c92322b595c6fa7079714b0/go.sum#L794)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

?? i wonder where is this coming from? did you `go mod tidy`?
</blockquote></details>

yes. both go-ethereum and go-ens have this in their go.sum also, so probably one of their dependencies introduced this. 
___
*[pkg/statestore/leveldb/migration.go, line 138 at r2](https://reviewable.io/reviews/ethersphere/bee/2342#-MfbNnVZEgbELRNRwomc:-MfbTYWS3o889xLWHGZ_:b-7tfmjp) ([raw file](https://github.com/ethersphere/bee/blob/260908703f5ea3f26c92322b595c6fa7079714b0/pkg/statestore/leveldb/migration.go#L138)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

what about `s.Delete(key)`?
</blockquote></details>

added
___
*[pkg/transaction/backendsimulation/backend.go, line 163 at r2](https://reviewable.io/reviews/ethersphere/bee/2342#-MfbE99MDsUi6mkbgrMn:-MfbTsyYBNPQ4EMEm5AV:bbpyr54) ([raw file](https://github.com/ethersphere/bee/blob/260908703f5ea3f26c92322b595c6fa7079714b0/pkg/transaction/backendsimulation/backend.go#L163)):*
<details><summary><i>Previously, mrekucci wrote…</i></summary><blockquote>

Since the `ctx` isn't used I'd suggest changing the name to `_` in order to explicitly signal that.
</blockquote></details>

deleted as it was no longer needed after downgrade

**Review by acud — APPROVED** [review]
:lgtm:

> Reviewed 1 of 12 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2342#-:-Mfbr3xR5a36EsWNWcN_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ralph-pichler)

**Pull request merged**
