### PR TITLE
chore: simplyfy formatting for byte slice representing eth types

### PR DESCRIPTION
**Pull request by vladopajic**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md)
- [x] My change requires a documentation update and I have done it
- [x] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues

### Description

`Hash` and `Address` types already implement `Stringer` interface so manual bytes slice formatting is not needed. 

Part of https://github.com/ethersphere/bee/issues/3157

- - -
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/3217)

### CODE REVIEW

**Comment by mrekucci** [comment]
Thanks for the PR. Can you make all the changes related to the #3157 in one PR (maybe move this changes to #3216), so if we decide to revert all changes, it will be in one go.

**Comment by vladopajic** [comment]
Usually it's better to have smaller PRs because they are easier to review and maintain. Even for reverting code this way can give you finer granularity.

**Comment by mrekucci** [comment]
> Usually it's better to have smaller PRs because they are easier to review and maintain. Even for reverting code this way can give you finer granularity.

For the purpose of review, we usually do separate commits instead of doing it in separate PRs, that way the commits can also be reviewed separately.

**Comment by vladopajic** [comment]
Anyway, closing this PR in favor or #3216

**Pull request closed without merging**
