### PR TITLE
fix(pss): fix trojan mining

### PR DESCRIPTION
**Pull request by zelig**
PR #2140 was merged with an incorrect bit.w

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2287)

### CODE REVIEW

**Comment by acud** [comment]
https://github.com/ethersphere/bee/pull/2287/checks?check_run_id=2981967728 data race detected

**Comment by zelig** [comment]
> https://github.com/ethersphere/bee/pull/2287/checks?check_run_id=2981967728 data race detected

addressed

**Review by acud — APPROVED** [review]

**Comment by acud** [comment]
@zelig there has been no changes to the PR in terms of synchronization, how was the data race solved? maybe good not to squash commits for such changes

**Comment by zelig** [comment]
> @zelig there has been no changes to the PR in terms of synchronization, how was the data race solved? maybe good not to squash commits for such changes

actually a good lesson why named return params are evil.
this line https://github.com/ethersphere/bee/pull/2287/files#diff-8fbb0a5de11b7fd685c32244eddae4545b09f56c82050c57902c08a1abfa2fe9R251
is racy with the assignment on line 245 if err is a named param.

**Review by mrekucci — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2287)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zelig)

**Comment by acud** [comment]
> > @zelig there has been no changes to the PR in terms of synchronization, how was the data race solved? maybe good not to squash commits for such changes
> 
> actually a good lesson why named return params are evil.
> this line https://github.com/ethersphere/bee/pull/2287/files#diff-8fbb0a5de11b7fd685c32244eddae4545b09f56c82050c57902c08a1abfa2fe9R251
> is racy with the assignment on line 245 if err is a named param.

oh wow... nice :clap: yeah named params should be avoided in general

**Pull request merged**
