### PR TITLE
chore: fix typo

### PR DESCRIPTION
**Pull request by chuwt**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2320)

### CODE REVIEW

**Comment by mrekucci** [comment]
@chuwt thanks for the PR!

**Review by mrekucci — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2320)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chuwt)

**Comment by chuwt** [comment]
@mrekucci for better bee🐝

**Review by acud — APPROVED** [review]
Thanks @chuwt !

**Pull request merged**
