### PR TITLE
fix: start syncing at a later block

### PR DESCRIPTION
**Pull request by ralph-pichler**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1745)

### CODE REVIEW

**Review by zelig — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1745)* status: all files reviewed, 2 unresolved discussions (waiting on @ralph-pichler)

___
*[pkg/postage/batchservice/batchservice.go, line 113 at r1](https://reviewable.io/reviews/ethersphere/bee/1745#-M_x5aav-hwwDPsDHskS:-M_x5aav-hwwDPsDHskT:b-fcwyec) ([raw file](https://github.com/ethersphere/bee/blob/2fc8e187d256e6d7bc6dcb4b89844d5ff6a6fcb7/pkg/postage/batchservice/batchservice.go#L113)):*
> ```Go
> func (svc *batchService) Start(startBlock uint64) <-chan struct{} {
> 	cs := svc.storer.GetChainState()
> 	if cs.Block > startBlock {
> ```

I think this should be `if cs.Block >= startBlock` or better have 
```
if cs.Block > startBlock {
   startBlock = cs.Block
}
return svc.listener.Listen(startBlock + 1, svc)
```
___
*[pkg/postage/listener/listener.go, line 286 at r1](https://reviewable.io/reviews/ethersphere/bee/1745#-M_x62i9EDZFPvVweAcL:-M_x62i9EDZFPvVweAcM:bnikuq0) ([raw file](https://github.com/ethersphere/bee/blob/2fc8e187d256e6d7bc6dcb4b89844d5ff6a6fcb7/pkg/postage/listener/listener.go#L286)):*
> ```Go
> 		// goerli
> 		return common.HexToAddress("0xF7a041E7e2B79ccA1975852Eb6D4c6cE52986b4a"), common.HexToAddress("0x1044534090de6f4014ece6d036C699130Bd5Df43"),
> 			4247101, true
> ```

shall we have const-s for all 3 values? like `GoerliPostageContractAddr` and `GoerliPriceOracleAddr` and `GoerliStartBlock`

**Review by acud — APPROVED** [review]

**Review by ralph-pichler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1745)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @zelig)

___
*[pkg/postage/batchservice/batchservice.go, line 113 at r1](https://reviewable.io/reviews/ethersphere/bee/1745#-M_x5aav-hwwDPsDHskS:-M_yXDcG58NGMcidUg6E:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/2fc8e187d256e6d7bc6dcb4b89844d5ff6a6fcb7/pkg/postage/batchservice/batchservice.go#L113)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

I think this should be `if cs.Block >= startBlock` or better have 
```
if cs.Block > startBlock {
   startBlock = cs.Block
}
return svc.listener.Listen(startBlock + 1, svc)
```

</blockquote></details>

Done.
___
*[pkg/postage/listener/listener.go, line 286 at r1](https://reviewable.io/reviews/ethersphere/bee/1745#-M_x62i9EDZFPvVweAcL:-M_yXAfO7APWwvPBDHGM:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/2fc8e187d256e6d7bc6dcb4b89844d5ff6a6fcb7/pkg/postage/listener/listener.go#L286)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

shall we have const-s for all 3 values? like `GoerliPostageContractAddr` and `GoerliPriceOracleAddr` and `GoerliStartBlock` 
</blockquote></details>

Done.

**Review by mrekucci — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1745)* status: all files reviewed, 3 unresolved discussions (waiting on @ralph-pichler and @zelig)

___
*[pkg/postage/listener/listener_test.go, line 282 at r2](https://reviewable.io/reviews/ethersphere/bee/1745#-M_ym__VBb_2mxGjBSaH:-M_ym__VBb_2mxGjBSaI:b7cmq2a) ([raw file](https://github.com/ethersphere/bee/blob/98947cec4132f0bf583d9fd3e14aa72439f10fe7/pkg/postage/listener/listener_test.go#L282)):*
> ```Go
> }
> 
> func (u *updater) Start(block uint64) <-chan struct{} { return nil }
> ```

`block` isn't used anywhere in the body so this should be indicated by `_`
___
*[pkg/settlement/swap/transaction/transaction.go, line 201 at r2](https://reviewable.io/reviews/ethersphere/bee/1745#-M_ynxiP2ArY8_bs5h1Y:-M_ynxiP2ArY8_bs5h1Z:bwsi6ya) ([raw file](https://github.com/ethersphere/bee/blob/98947cec4132f0bf583d9fd3e14aa72439f10fe7/pkg/settlement/swap/transaction/transaction.go#L201)):*
> ```Go
> 	}
> 
> 	gasPrice = new(big.Int).Mul(gasPrice, big.NewInt(10))
> ```

No need to create a new instance of `big.Int`; `gasPrice = gasPrice.Mul(gasPrice, big.NewInt(10))` will do the same. Also the tests in the `transaction_test.go` need to be adjusted accordingly.

**Review by ralph-pichler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1745)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @mrekucci and @zelig)

___
*[pkg/postage/listener/listener_test.go, line 282 at r2](https://reviewable.io/reviews/ethersphere/bee/1745#-M_ym__VBb_2mxGjBSaH:-M_yrDQ-E3rQBHDlEBtY:bb7f2mf) ([raw file](https://github.com/ethersphere/bee/blob/98947cec4132f0bf583d9fd3e14aa72439f10fe7/pkg/postage/listener/listener_test.go#L282)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

`block` isn't used anywhere in the body so this should be indicated by `_`
</blockquote></details>

done
___
*[pkg/settlement/swap/transaction/transaction.go, line 201 at r2](https://reviewable.io/reviews/ethersphere/bee/1745#-M_ynxiP2ArY8_bs5h1Y:-M_yrK_587PEoAH_vbqG:bv2t56z) ([raw file](https://github.com/ethersphere/bee/blob/98947cec4132f0bf583d9fd3e14aa72439f10fe7/pkg/settlement/swap/transaction/transaction.go#L201)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

No need to create a new instance of `big.Int`; `gasPrice = gasPrice.Mul(gasPrice, big.NewInt(10))` will do the same. Also the tests in the `transaction_test.go` need to be adjusted accordingly.
</blockquote></details>

this should not have been in this PR in the first place. removed.

**Review by mrekucci — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1745#-:-M_z-goq2ejraktcKlWF:bnfp4nl)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @mrekucci and @zelig)

**Pull request merged**
