### PR TITLE
fix(kademlia): inspect peer metrics snapshot in a safe manner

### PR DESCRIPTION
**Pull request by mrekucci**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1804)

### CODE REVIEW

**Review by acud — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1804#-:-MaD9vleBcbtOeUY3pwd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrekucci)

**Review by anatollupacescu — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1804)* status: all files reviewed, 2 unresolved discussions (waiting on @esadakar and @mrekucci)

___
*[pkg/topology/kademlia/kademlia.go, line 696 at r2](https://reviewable.io/reviews/ethersphere/bee/1804#-MaDJ-XVCWNTRZ-L_fTU:-MaDJ-XVCWNTRZ-L_fTV:brd2uc6) ([raw file](https://github.com/ethersphere/bee/blob/6479a7ab3ff01891a8e891759cc512a02f521302/pkg/topology/kademlia/kademlia.go#L696)):*
> ```Go
> 		if err := k.collector.Inspect(peer, func(ss *metrics.Snapshot) {
> 			quickPrune := ss == nil ||
> 				(ss.LastSeenTimestamp == 0 && ss.SessionConnectionRetry <= 1)
> ```

can this be broken down in a few lines? nothing wrong with it per se, but it takes a second look to grasp it, I'm just wondering if there's a simpler version of it.
___
*[pkg/topology/kademlia/internal/metrics/metrics.go, line 273 at r2](https://reviewable.io/reviews/ethersphere/bee/1804#-MaDIMaU2C9MzDbD8h6W:-MaDIMaU2C9MzDbD8h6X:b-ngyovd) ([raw file](https://github.com/ethersphere/bee/blob/6479a7ab3ff01891a8e891759cc512a02f521302/pkg/topology/kademlia/internal/metrics/metrics.go#L273)):*
> ```Go
> 		return err
> 	}
> 	fn(sss[addr.String()])
> ```

minor: can we rename this `sss` var to something more meaningful? the one in the argument is ok

**Review by anatollupacescu — APPROVED** [review]

**Review by janos — APPROVED** [review]

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1804)* status: all files reviewed, 1 unresolved discussion (waiting on @anatollupacescu and @esadakar)

___
*[pkg/topology/kademlia/kademlia.go, line 696 at r2](https://reviewable.io/reviews/ethersphere/bee/1804#-MaDJ-XVCWNTRZ-L_fTU:-MaDisAZ6-_rfiosEbh9:bs7wuot) ([raw file](https://github.com/ethersphere/bee/blob/6479a7ab3ff01891a8e891759cc512a02f521302/pkg/topology/kademlia/kademlia.go#L696)):*
<details><summary><i>Previously, anatollupacescu (Anatolie Lupacescu) wrote…</i></summary><blockquote>

can this be broken down in a few lines? nothing wrong with it per se, but it takes a second look to grasp it, I'm just wondering if there's a simpler version of it.
</blockquote></details>

Done.

**Review by anatollupacescu — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1804#-:-MaDmXL13xoScd6YV9x3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @esadakar)

**Pull request merged**
