### PR TITLE
kademlia, addresbook: extend information kept about peers

### PR DESCRIPTION
**Pull request by mrekucci**
#1643

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1658)

### CODE REVIEW

**Comment by mrekucci** [comment]
Output example:

```json
{
   "bin_0":{
      "population":1,
      "connected":1,
      "disconnectedPeers":null,
      "connectedPeers":[
         {
            "address":"5b8e8a33dc10696231500e514a699ae1c5797ef9bd5945665aa5ed0a6aa3b99b",
            "metrics":{
               "lastSeen":"13 May 21 14:48 UTC",
               "connectionTotalDuration":"1m28s",
               "sessionConnectionRetry":0,
               "sessionConnectionDuration":"1m28s",
               "sessionConnectionDirection":"inbound"
            }
         }
      ]
   },
   "bin_1":{
      "population":1,
      "connected":1,
      "disconnectedPeers":null,
      "connectedPeers":[
         {
            "address":"add72d5cd06739fe4ab9adb7b670d31110865b7a68938e26d5d7cd73bcd18081",
            "metrics":{
               "lastSeen":"13 May 21 14:48 UTC",
               "connectionTotalDuration":"1m28s",
               "sessionConnectionRetry":0,
               "sessionConnectionDuration":"1m28s",
               "sessionConnectionDirection":"outbound"
            }
         }
      ]
   }
}
```

**Comment by ldeffenb** [comment]
Can't wait!  I've been wanting to add inbound vs outbound connection counts to my monBee since the beginning, but no API would reveal that information.

**Comment by acud** [comment]
> Any chance that the same info could be added to the /peers API so that I don't have to fetch the entire disconnected peers in /topology just to get it?

Not sure WDYM here @ldeffenb. The information should be visible also over disconnected peers in `topology`. Adding these metrics to `/peers` is a bit more difficult since `/peers` shows the number of p2p peers and this is a totally different abstraction. It is also not on our priority right now, as we try to have `kademlia` as our source of truth. Light nodes would not have this metric at this point, and this will indeed need to be added at some point soon.

**Review by acud — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1658)* status: all files reviewed, 4 unresolved discussions (waiting on @esadakar and @mrekucci)

___
*[pkg/topology/kademlia/kademlia.go, line 1121 at r1](https://reviewable.io/reviews/ethersphere/bee/1658#-M_fhtOC2goHLcRmFQvK:-M_fhtOC2goHLcRmFQvL:b-j2tx73) ([raw file](https://github.com/ethersphere/bee/blob/2ab8923a946616bddb6fb08a95ad47e59d373edd/pkg/topology/kademlia/kademlia.go#L1121)):*
> ```Go
> 	ss, err := k.collector.Snapshot(time.Now())
> 	if err != nil {
> 		k.logger.Debugf("kademlia: unable to take metrics snapshot: %v", err)
> ```

if `err != nil` might we panic on `Metrics: createMetricsSnapshotView(ss[addr.String()]),`?
___
*[pkg/topology/kademlia/kademlia.go, line 1151 at r1](https://reviewable.io/reviews/ethersphere/bee/1658#-M_fi4YT5LmxEhOS-NmV:-M_fi4YT5LmxEhOS-NmW:b-2guby3) ([raw file](https://github.com/ethersphere/bee/blob/2ab8923a946616bddb6fb08a95ad47e59d373edd/pkg/topology/kademlia/kademlia.go#L1151)):*
> ```Go
> 			&topology.PeerInfo{
> 				Address: addr,
> 				Metrics: createMetricsSnapshotView(ss[addr.String()]),
> ```

same here
___
*[pkg/topology/kademlia/kademlia_test.go, line 1054 at r1](https://reviewable.io/reviews/ethersphere/bee/1658#-M_fiCxJ8C3ZF6rjosaU:-M_fiCxJ8C3ZF6rjosaV:bby6s0g) ([raw file](https://github.com/ethersphere/bee/blob/2ab8923a946616bddb6fb08a95ad47e59d373edd/pkg/topology/kademlia/kademlia_test.go#L1054)):*
> ```Go
> 
> func newTestKademlia(t *testing.T, connCounter, failedConnCounter *int32, kadOpts kademlia.Options) (swarm.Address, *kademlia.Kad, addressbook.Interface, *mock.Discovery, beeCrypto.Signer) {
> 	metricsDB, err := shed.NewDB("", nil)
> ```

adding `t.Helper()` would help debugging failures better
___
*[pkg/topology/kademlia/internal/metrics/metrics.go, line 21 at r1](https://reviewable.io/reviews/ethersphere/bee/1658#-M_fiTbz2AzhRPs-0ban:-M_fiTbz2AzhRPs-0bao:bc1an0t) ([raw file](https://github.com/ethersphere/bee/blob/2ab8923a946616bddb6fb08a95ad47e59d373edd/pkg/topology/kademlia/internal/metrics/metrics.go#L21)):*
> ```Go
> // peerKeyPrefix represents the type for defining peer metrics prefix key
> // necessary for identification of the values stored in persistent store.
> type peerKeyPrefix string
> ```

do we need a type alias for `string`? there's no methods defined on this type. can you briefly outline the benefits here?

**Review by esadakar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1658)* status: all files reviewed, 5 unresolved discussions (waiting on @mrekucci)

___
*[pkg/topology/kademlia/internal/metrics/metrics.go, line 125 at r1](https://reviewable.io/reviews/ethersphere/bee/1658#-M_fo0kr045_fO00J9WO:-M_fo0kr045_fO00J9WP:b-b43n7b) ([raw file](https://github.com/ethersphere/bee/blob/2ab8923a946616bddb6fb08a95ad47e59d373edd/pkg/topology/kademlia/internal/metrics/metrics.go#L125)):*
> ```Go
> func IncSessionConnectionRetry() RecordOp {
> 	return func(cs *Counters) error {
> 		if cs.loggedIn {
> ```

if the connection retry count is meant to track attempts at connecting to the peer, this check will always return false since the peer is not connected/loggedIn yet.

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1658)* status: all files reviewed, 5 unresolved discussions (waiting on @acud and @esadakar)

___
*[pkg/topology/kademlia/kademlia.go, line 1121 at r1](https://reviewable.io/reviews/ethersphere/bee/1658#-M_fhtOC2goHLcRmFQvK:-M_tbrbEAXK8W4CID_fQ:b8gj3mm) ([raw file](https://github.com/ethersphere/bee/blob/2ab8923a946616bddb6fb08a95ad47e59d373edd/pkg/topology/kademlia/kademlia.go#L1121)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

if `err != nil` might we panic on `Metrics: createMetricsSnapshotView(ss[addr.String()]),`?
</blockquote></details>

Good catch, fixed!
___
*[pkg/topology/kademlia/kademlia.go, line 1151 at r1](https://reviewable.io/reviews/ethersphere/bee/1658#-M_fi4YT5LmxEhOS-NmV:-M_tbxtG-1-PNNrh5z17:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/2ab8923a946616bddb6fb08a95ad47e59d373edd/pkg/topology/kademlia/kademlia.go#L1151)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[pkg/topology/kademlia/kademlia_test.go, line 1054 at r1](https://reviewable.io/reviews/ethersphere/bee/1658#-M_fiCxJ8C3ZF6rjosaU:-M_tcB3i0UEDYNg6ohVy:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/2ab8923a946616bddb6fb08a95ad47e59d373edd/pkg/topology/kademlia/kademlia_test.go#L1054)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

adding `t.Helper()` would help debugging failures better
</blockquote></details>

Done.
___
*[pkg/topology/kademlia/internal/metrics/metrics.go, line 21 at r1](https://reviewable.io/reviews/ethersphere/bee/1658#-M_fiTbz2AzhRPs-0ban:-M_tce_G7Ak52Tq3BYO8:b-2hrjuz) ([raw file](https://github.com/ethersphere/bee/blob/2ab8923a946616bddb6fb08a95ad47e59d373edd/pkg/topology/kademlia/internal/metrics/metrics.go#L21)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

do we need a type alias for `string`? there's no methods defined on this type. can you briefly outline the benefits here?
</blockquote></details>

We don't, it was a leftover from previous iteration.
___
*[pkg/topology/kademlia/internal/metrics/metrics.go, line 125 at r1](https://reviewable.io/reviews/ethersphere/bee/1658#-M_fo0kr045_fO00J9WO:-M_tfIkgDgZNVx7kKrsE:b8gj3mm) ([raw file](https://github.com/ethersphere/bee/blob/2ab8923a946616bddb6fb08a95ad47e59d373edd/pkg/topology/kademlia/internal/metrics/metrics.go#L125)):*
<details><summary><i>Previously, esadakar (Esad Akar) wrote…</i></summary><blockquote>

if the connection retry count is meant to track attempts at connecting to the peer, this check will always return false since the peer is not connected/loggedIn yet.
</blockquote></details>

Good catch, fixed!

**Review by esadakar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1658)* status: 7 of 11 files reviewed, 5 unresolved discussions (waiting on @acud and @esadakar)

**Review by acud — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1658)* status: all files reviewed, 1 unresolved discussion (waiting on @esadakar)

**Review by esadakar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1658)* status: all files reviewed, 1 unresolved discussion (waiting on @esadakar)

**Review by esadakar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1658)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrekucci)

**Review by acud — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1658)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrekucci)

**Review by acud — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1658#-:-M_uvm7L-bHNZZfzmU3Z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrekucci)

**Review by esadakar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1658#-:-M_uy1Y29tjlvpSRKQl4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrekucci)

**Review by acud — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1658#-:-M_vJJtk1x4inX7-NLVr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrekucci)

**Pull request merged**
