### PR TITLE
refactor(openapi): swap EmptyNull with nullable

### PR DESCRIPTION
**Pull request by mrekucci**
Replaces user-defined type EmptyNull with the
nullable defined by the OpenAPI specification.

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1752)

### CODE REVIEW

**Review by acud — APPROVED** [review]

**Review by anatollupacescu — APPROVED** [review]

**Comment by AuHau** [comment]
Hmm, honestly I am not such a fan of this approach. This does not explain at all when the property is `null` at the behavior (empty array = null) is not obvious (at least for non-Golang dev). If you want to go this path I would suggest adding into all descriptions of these properties info about when it is null.

**Comment by mrekucci** [comment]
> Hmm, honestly I am not such a fan of this approach. This does not explain at all when the property is `null` and the behavior (empty array = null) is not obvious (at least for non-Golang dev). If you want to go this path I would suggest adding into all descriptions of these properties info about when it is null.

I'd disagree here since the specification is clear on that what the [`nullable`](https://github.com/OAI/OpenAPI-Specification/blob/main/proposals/003_Clarify-Nullable.md) express and the consumer should be aware of this specification. On top of that, the current description using the `EmptyNull` is not valid according to the https://editor.swagger.io/ it returns the following error:

```
Structural error at components.schemas.EmptyNull.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 143
```

**Comment by AuHau** [comment]
> I'd disagree here since the specification is clear on that what the nullable express and the consumer should be aware of this specification.

I am not saying that the user should not understand what `nullable` means. Sure, for some generic objects that have an attribute with a potential `null` value that in its context makes sense, why not. But coming from JS (and few other langs) backgrounds, I would 100% expect you to return an empty array instead of `null` for the case when there are no entries. Few others team members from Bee Geezs (JS) were also quite surprised by this.

> On top of that, the current description using the EmptyNull is not valid according to the editor.swagger.io it returns the following error:

Heh, my IDE then confused me about allowed values 😅 Then I agree with dropping my approach but, as mentioned before, I would add a textual description that "Returns `null` if there are no entries instead of empty array".

**Comment by mrekucci** [comment]
> > I'd disagree here since the specification is clear on that what the nullable express and the consumer should be aware of this specification.
> 
> I am not saying that the user should not understand what `nullable` means. Sure, for some generic objects that have an attribute with a potential `null` value that in its context makes sense, why not. But coming from JS (and few other langs) backgrounds, I would 100% expect you to return an empty array instead of `null` for the case when there are no entries. Few others team members from Bee Geezs (JS) were also quite surprised by this.
> 
> > On top of that, the current description using the EmptyNull is not valid according to the editor.swagger.io it returns the following error:
> 
> Heh, my IDE then confused me about allowed values 😅 Then I agree with dropping my approach but, as mentioned before, I would add a textual description that "Returns `null` if there are no entries instead of empty array".

I agree with returning an empty array instead of a null. That's best practice when designing an API. This PR doesn't address that, it just fixes the errors pointed out by the validator. Hopefully, the fix replacing the null values with the empty array will come soon, but some things need to be discussed before we make that change.

**Comment by AuHau** [comment]
Yeah agree, I am only trying to be more "dummy developer-friendly" and propose to explain when there can be null value as I don't think it is obvious...

**Pull request merged**
