### PR TITLE
feat: reupload to network

### PR DESCRIPTION
**Pull request by acud**
naive implementation of reupload to network

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1705)

### CODE REVIEW

**Review by aloknerurkar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1705)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @acud, @anatollupacescu, @mrekucci, and @zelig)

___
*[pkg/stewardess/stewardess.go, line 43 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dSTMz5VpqTrRG6DNu:-M_dSTMz5VpqTrRG6DNv:b75ucg1) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess.go#L43)):*
> ```Go
> // addresses and push every chunk individually to the network.
> // It assumes all chunks are available locally. It is therefore
> // advisable to pin the content locally before trying to reupload it.
> ```

Would it be better to enforce this using a timeout in Reupload?

**Review by zelig — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1705)* status: 7 of 10 files reviewed, 6 unresolved discussions (waiting on @acud, @anatollupacescu, and @mrekucci)

___
*[pkg/api/api.go, line 33 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dh4uy2NyOWnNS_Fh_:-M_dh4uy2NyOWnNS_Fha:b-cavo4i) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/api/api.go#L33)):*
> ```Go
> 	"github.com/ethersphere/bee/pkg/pss"
> 	"github.com/ethersphere/bee/pkg/resolver"
> 	"github.com/ethersphere/bee/pkg/stewardess"
> ```

please rename to steward
___
*[pkg/stewardess/stewardess.go, line 29 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_di1S-DpuB4egFR8sA:-M_di1S-DpuB4egFR8sB:b-6d66y6) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess.go#L29)):*
> ```Go
> }
> 
> type stew struct {
> ```

steward pls
___
*[pkg/stewardess/stewardess.go, line 53 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_diKiM6fCeUqTtlBnl:-M_diKiM6fCeUqTtlBnm:b-sp9bno) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess.go#L53)):*
> ```Go
> 		}
> 
> 		tokenPool <- struct{}{}
> ```

worker pls, the word token is too burdened in our field
___
*[pkg/traversal/traversal.go, line 31 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dj3X561AJ9fUShfdx:-M_dj3X561AJ9fUShfdy:bnkv2bl) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/traversal/traversal.go#L31)):*
> ```Go
> 
> // NewService is a convenient constructor for Service.
> func NewService(store storage.Storer) Traverser {
> ```

why not just New?
___
*[pkg/traversal/traversal_test.go, line 70 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_djFq124sDL2nz7Nx5:-M_djFq124sDL2nz7Nx6:b-msxels) ([raw file](https://github.com/ethersphere/bee/blob/f3cb3f2eddc38e77db83cf9b3bd1a05ff4e1b16c/pkg/traversal/traversal_test.go#L70)):*
> ```Go
> }
> 
> var _ Traverser = (*Service)(nil)
> ```

why remove this? just lowercase service

**Review by zelig — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1705)* status: 8 of 10 files reviewed, 8 unresolved discussions (waiting on @acud, @anatollupacescu, and @mrekucci)

___
*[pkg/api/bzz.go, line 516 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dkLOz9IP4yY16XL7q:-M_dkLOz9IP4yY16XL7r:b-fxs1z7) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/api/bzz.go#L516)):*
> ```Go
> 		return
> 	}
> 	err = s.stewardess.Reupload(r.Context(), address)
> ```

I am not sure this naive implementation is a good idea. The user expects the reupload to work like upload.
This call now only returns if all chunks are pushed and synced but no way to monitor progress. 
___
*[pkg/stewardess/stewardess.go, line 56 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_djabsDe8zufC9xkZc:-M_djabsDe8zufC9xkZd:bh2qhqf) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess.go#L56)):*
> ```Go
> 		eg.Go(func() error {
> 			defer func() { <-tokenPool }()
> 			_, err := s.push.PushChunkToClosest(ctx, c)
> ```

not sure i like it that we introduce a completely new mechanism for pushing to network than at upload
we should have a ModeSetPush which puts an existing chunk to the pushindex and then we wait on the tag.

**Review by mrekucci — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1705)* status: all files reviewed, 10 unresolved discussions (waiting on @acud and @anatollupacescu)

___
*[pkg/api/api.go, line 51 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dmGbd7KIeRCSKpe42:-M_dmGbd7KIeRCSKpe43:blodyme) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/api/api.go#L51)):*
> ```Go
> 	SwarmCollectionHeader     = "Swarm-Collection"
> 	SwarmPostageBatchIdHeader = "Swarm-Postage-Batch-Id"
> 	SwarmReuploadHeader       = "Swarm-Reupload"
> ```

This header constant isn't used anywhere. Shouldn't be used in the handler?
___
*[pkg/stewardess/stewardess.go, line 47 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dcXpDBAVKHsnBvd1n:-M_dcXpDBAVKHsnBvd1o:b-w4owi4) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess.go#L47)):*
> ```Go
> 	tokenPool := make(chan struct{}, parallelPush)
> 	eg, _ := errgroup.WithContext(ctx)
> 	f := func(addr swarm.Address) error {
> ```

`f` usually refers to a file, the convention for naming a function is usually `fn`.
___
*[pkg/stewardess/stewardess_test.go, line 33 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_ddJH9CxkSr9PxBLDp:-M_ddJHAEa8KQ5OT5KsN:b-w4owi4) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess_test.go#L33)):*
> ```Go
> 		traversedAddrs = make(map[string]struct{})
> 		mu             sync.Mutex
> 		f              = func(_ context.Context, ch swarm.Chunk) (*pushsync.Receipt, error) {
> ```

`f` usually refers to a file, the convention for naming a function is usually `fn`.

**Review by acud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1705)* status: 1 of 11 files reviewed, 10 unresolved discussions (waiting on @aloknerurkar, @anatollupacescu, @mrekucci, and @zelig)

___
*[pkg/api/api.go, line 33 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dh4uy2NyOWnNS_Fh_:-M_eljBREI11Hb039vkI:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/api/api.go#L33)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

please rename to steward
</blockquote></details>

Done.
___
*[pkg/api/api.go, line 51 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dmGbd7KIeRCSKpe42:-M_eiPbl1LoezksT5hyC:b-r73d4l) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/api/api.go#L51)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

This header constant isn't used anywhere. Shouldn't be used in the handler?
</blockquote></details>

nice catch :+1: actually, since i'm using a different verb, maybe this is not needed for now
___
*[pkg/api/bzz.go, line 516 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dkLOz9IP4yY16XL7q:-M_eu0yc-qKdFaUf-bBZ:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/api/bzz.go#L516)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

I am not sure this naive implementation is a good idea. The user expects the reupload to work like upload.
This call now only returns if all chunks are pushed and synced but no way to monitor progress. 
</blockquote></details>

Done.
___
*[pkg/traversal/traversal.go, line 31 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dj3X561AJ9fUShfdx:-M_enyVh3aPu8hGeoz6A:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/traversal/traversal.go#L31)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

why not just New?
</blockquote></details>

Done.
___
*[pkg/traversal/traversal_test.go, line 70 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_djFq124sDL2nz7Nx5:-M_ek7cS5-2I0SLsqTM2:bqor462) ([raw file](https://github.com/ethersphere/bee/blob/f3cb3f2eddc38e77db83cf9b3bd1a05ff4e1b16c/pkg/traversal/traversal_test.go#L70)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

why remove this? just lowercase service
</blockquote></details>

it is not exposed in this namespace :shrug: 
___
*[pkg/stewardess/stewardess.go, line 29 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_di1S-DpuB4egFR8sA:-M_eu-bF9qYoGsYEyvdW:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess.go#L29)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

steward pls
</blockquote></details>

Done.
___
*[pkg/stewardess/stewardess.go, line 43 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dSTMz5VpqTrRG6DNu:-M_eifmh00nALeDlwQjT:bxta8uw) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess.go#L43)):*
<details><summary><i>Previously, aloknerurkar (Alok Nerurkar) wrote…</i></summary><blockquote>

Would it be better to enforce this using a timeout in Reupload?
</blockquote></details>

enforce what? if the chunks are there - it will try to reupload. if not, it will error. not sure what a timeout will give here. also, you don't know how big the root is, so you would have the same timeout to reupload maybe a collection of 10 files of 10kb and 10 files of 10tb?
___
*[pkg/stewardess/stewardess.go, line 53 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_diKiM6fCeUqTtlBnl:-M_ene5k4ZZn4HbnrqAY:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess.go#L53)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

worker pls, the word token is too burdened in our field
</blockquote></details>

Done.
___
*[pkg/stewardess/stewardess.go, line 56 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_djabsDe8zufC9xkZc:-M_etzBi8VMtw25qwovM:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess.go#L56)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

not sure i like it that we introduce a completely new mechanism for pushing to network than at upload
we should have a ModeSetPush which puts an existing chunk to the pushindex and then we wait on the tag.

</blockquote></details>

Done.
___
*[pkg/stewardess/stewardess_test.go, line 33 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_ddJH9CxkSr9PxBLDp:-M_enmUZC-oM7IZW6dlM:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess_test.go#L33)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

`f` usually refers to a file, the convention for naming a function is usually `fn`.
</blockquote></details>

Done.

**Review by mrekucci — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1705#-:-M_f-6eID1FqoIZTRQwI:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @aloknerurkar, @anatollupacescu, and @zelig)

**Review by zelig — COMMENTED** [review]
> Reviewed 9 of 10 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1705)* status: all files reviewed, 2 unresolved discussions (waiting on @aloknerurkar, @anatollupacescu, and @zelig)

**Review by anatollupacescu — APPROVED** [review]

**Comment by aloknerurkar** [comment]
___
*[pkg/stewardess/stewardess.go, line 43 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dSTMz5VpqTrRG6DNu:-M_toSmD5G7ji4e594v0:b6khycg) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess.go#L43)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

enforce what? if the chunks are there - it will try to reupload. if not, it will error. not sure what a timeout will give here. also, you don't know how big the root is, so you would have the same timeout to reupload maybe a collection of 10 files of 10kb and 10 files of 10tb?
</blockquote></details>

I thought the getter will try to pull from the network if it doesn't find it locally. The comment says it assumes all chunks are available locally. If not this get operation will be too long right?

**Review by acud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1705)* status: all files reviewed, 2 unresolved discussions (waiting on @aloknerurkar and @zelig)

___
*[pkg/stewardess/stewardess.go, line 43 at r1](https://reviewable.io/reviews/ethersphere/bee/1705#-M_dSTMz5VpqTrRG6DNu:-M_tq6pC48qYnZM_QTT1:b-frnirl) ([raw file](https://github.com/ethersphere/bee/blob/0ed2e4134547c30f3b01ad31fda3d73c32735135/pkg/stewardess/stewardess.go#L43)):*
<details><summary><i>Previously, aloknerurkar (Alok Nerurkar) wrote…</i></summary><blockquote>

I thought the getter will try to pull from the network if it doesn't find it locally. The comment says it assumes all chunks are available locally. If not this get operation will be too long right?
</blockquote></details>

have a look at `node.go`, the service is injected with localstore, not netstore

**Pull request merged**
