### PR TITLE
fix: unable to boot in standalone

### PR DESCRIPTION
**Pull request by anatollupacescu**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1713)

### CODE REVIEW

**Review by mrekucci — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1713#-:-M_f8DmB23pkWTnbUggi:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @acud and @mrekucci)

___
*[pkg/node/node.go, line 801 at r1](https://reviewable.io/reviews/ethersphere/bee/1713#-M_f7Og6BbUDI_uo7y1x:-M_f7Og7ERY7mm2Of1cK:b-5ya6g2) ([raw file](https://github.com/ethersphere/bee/blob/fde9eb8969c2605d8c20ce5161800e72db576971/pkg/node/node.go#L801)):*
> ```Go
> func getTxHash(stateStore storage.StateStorer, logger logging.Logger, o Options) ([]byte, error) {
> 	if o.Standalone {
> 		return standaloneTxHash, nil
> ```

I'd just return `nil` or `[]byte{31: 0}` directly from here without having `var standaloneTxHash = []byte("00000000000000000000000000000000")`.

**Review by anatollupacescu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1713)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @acud and @mrekucci)

___
*[pkg/node/node.go, line 801 at r1](https://reviewable.io/reviews/ethersphere/bee/1713#-M_f7Og6BbUDI_uo7y1x:-M_f8NYLCXq1aQGV_RHj:bvnrpcm) ([raw file](https://github.com/ethersphere/bee/blob/fde9eb8969c2605d8c20ce5161800e72db576971/pkg/node/node.go#L801)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

I'd just return `nil` or `[]byte{31: 0}` directly from here without having `var standaloneTxHash = []byte("00000000000000000000000000000000")`.
</blockquote></details>

updated

**Review by mrekucci — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1713)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud)

**Review by acud — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1713#-:-M_f9PF42pRAWpl4mnVk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatollupacescu)

___
*[pkg/node/node.go, line 801 at r1](https://reviewable.io/reviews/ethersphere/bee/1713#-M_f7Og6BbUDI_uo7y1x:-M_f9KZO2buPi_gpastf:b-3migx5) ([raw file](https://github.com/ethersphere/bee/blob/fde9eb8969c2605d8c20ce5161800e72db576971/pkg/node/node.go#L801)):*
<details><summary><i>Previously, anatollupacescu (Anatolie Lupacescu) wrote…</i></summary><blockquote>

updated
</blockquote></details>

won't returning a `nil` cause a panic in the calling context?

**Review by acud — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1713#-:-M_tjCp1AhoEuzqf2j_Q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatollupacescu)

**Pull request merged**
