### PR TITLE
Using lower camel case for field names in http responses

### PR DESCRIPTION
**Pull request by anatollupacescu**
Using lowerCamelCase because that's the easiest to use from Javascript.

### CODE REVIEW

**Review by acud — APPROVED** [review]
great! thank you!
@agazso this would probably break a few things, but addresses the changes you've mentioned earlier about inconsistent naming

**Comment by agazso** [comment]
Thanks, this looks like a fix for #1078

**Comment by acud** [comment]
correct @agazso

**Review by janos — COMMENTED** [review]
Thanks. It would be good to have these changes reflected in the openapi/*.yaml files, as well.

**Review by agazso — APPROVED** [review]
👍

**Review by aloknerurkar — APPROVED** [review]

**Comment by AuHau** [comment]
FYI unfortunately this still did not address all the issues. For example https://github.com/ethersphere/bee/blob/master/openapi/SwarmCommon.yaml#L108 is still all lowercased.

**Pull request merged**
