### PR TITLE
feat: estimate expected lifetime of batches

### PR DESCRIPTION
**Pull request by mrekucci**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2336)

### CODE REVIEW

**Review by zelig — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2336)* status: all files reviewed, 6 unresolved discussions (waiting on @acud, @aloknerurkar, and @mrekucci)

___
*[pkg/debugapi/debugapi.go, line 60 at r1](https://reviewable.io/reviews/ethersphere/bee/2336#-MeqQwzK5LL1p6jNKLxh:-MeqQwzK5LL1p6jNKLxi:b1swstf) ([raw file](https://github.com/ethersphere/bee/blob/4d1c6671f8876a8fc18c09ac30874ebb885f8cdc/pkg/debugapi/debugapi.go#L60)):*
> ```Go
> 	metricsRegistry    *prometheus.Registry
> 	lightNodes         *lightnode.Container
> 	blockTime          uint64
> ```

better hold this in bigint to avoid casting(and allocating) later on every call
___
*[pkg/debugapi/postage.go, line 286 at r1](https://reviewable.io/reviews/ethersphere/bee/2336#-MeqHH4J1D7uwNZb2Nki:-MeqHH4J1D7uwNZb2Nkj:b-e0xlj2) ([raw file](https://github.com/ethersphere/bee/blob/4d1c6671f8876a8fc18c09ac30874ebb885f8cdc/pkg/debugapi/postage.go#L286)):*
> ```Go
> 
> // estimateBatchExpiration estimates batch expiration in seconds.
> func (s *Service) estimateBatchExpiration(id []byte) (uint64, error) {
> ```

this function actually estimates the time remaining until the batch expires.
I would not call it expiration cos that evokes a time, rather `timeToLive`
___
*[pkg/debugapi/postage.go, line 300 at r1](https://reviewable.io/reviews/ethersphere/bee/2336#-MeqJbjg2lQQzcNfH0fr:-MeqJbjg2lQQzcNfH0fs:bx5lq6g) ([raw file](https://github.com/ethersphere/bee/blob/4d1c6671f8876a8fc18c09ac30874ebb885f8cdc/pkg/debugapi/postage.go#L300)):*
> ```Go
> 	)
> 
> 	if pricePerBlock.Cmp(big.NewInt(0)) == 0 {
> ```

FTR the efficient zero check for bigint is `len(pricePerBlock.Bits()) == 0` 20 times faster even without spurious allocation 
___
*[pkg/debugapi/postage.go, line 305 at r1](https://reviewable.io/reviews/ethersphere/bee/2336#-MeqGUqQBYLV_1-J9ogw:-MeqGUqQBYLV_1-J9ogx:b-4vwvv4) ([raw file](https://github.com/ethersphere/bee/blob/4d1c6671f8876a8fc18c09ac30874ebb885f8cdc/pkg/debugapi/postage.go#L305)):*
> ```Go
> 
> 	ee := new(big.Int).Sub(normalizedBalance, cumulativePayout)
> 	ee = new(big.Int).Div(ee, pricePerBlock)
> ```

you save allocations with:

```
ee.Div(ee, pricePerBlock)
ee.Mul(ee,  big.NewInt(blockTime))
return ee.Uint64(), nil
```
___
*[pkg/debugapi/postage.go, line 306 at r1](https://reviewable.io/reviews/ethersphere/bee/2336#-MeqQHR7BMxttlc7RfLi:-MeqH-a_1KBVndYp8eWM:b2fslhe) ([raw file](https://github.com/ethersphere/bee/blob/4d1c6671f8876a8fc18c09ac30874ebb885f8cdc/pkg/debugapi/postage.go#L306)):*
> ```Go
> 	ee := new(big.Int).Sub(normalizedBalance, cumulativePayout)
> 	ee = new(big.Int).Div(ee, pricePerBlock)
> 	ee = new(big.Int).Mul(ee, big.NewInt(blockTime))
> ```

consider doing multiplication first for precision
___
*[pkg/debugapi/postage_test.go, line 220 at r1](https://reviewable.io/reviews/ethersphere/bee/2336#-MeqOLcR6qdyAjb8nUrX:-MeqOLcR6qdyAjb8nUrY:b3a20y6) ([raw file](https://github.com/ethersphere/bee/blob/4d1c6671f8876a8fc18c09ac30874ebb885f8cdc/pkg/debugapi/postage_test.go#L220)):*
> ```Go
> 					ImmutableFlag: si.ImmutableFlag(),
> 					Exists:        true,
> 					Expire:        14,
> ```

a comment would be nice how you get this: 
`((value-totalAmount)/pricePerBlock)*blockTime=((20-5)/2)*2`. 
Now this is of course 15, which shows that by doing division first on int you lose precision.

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2336)* status: all files reviewed, 6 unresolved discussions (waiting on @acud, @aloknerurkar, @mrekucci, and @zelig)

___
*[pkg/debugapi/debugapi.go, line 60 at r1](https://reviewable.io/reviews/ethersphere/bee/2336#-MeqQwzK5LL1p6jNKLxh:-MezHoBQBgIPVSag_8Vu:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/4d1c6671f8876a8fc18c09ac30874ebb885f8cdc/pkg/debugapi/debugapi.go#L60)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

better hold this in bigint to avoid casting(and allocating) later on every call
</blockquote></details>

Done.
___
*[pkg/debugapi/postage.go, line 286 at r1](https://reviewable.io/reviews/ethersphere/bee/2336#-MeqHH4J1D7uwNZb2Nki:-MezI5kI8tgKAsydS0Nf:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/4d1c6671f8876a8fc18c09ac30874ebb885f8cdc/pkg/debugapi/postage.go#L286)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

this function actually estimates the time remaining until the batch expires.
I would not call it expiration cos that evokes a time, rather `timeToLive`
</blockquote></details>

Done.
___
*[pkg/debugapi/postage.go, line 300 at r1](https://reviewable.io/reviews/ethersphere/bee/2336#-MeqJbjg2lQQzcNfH0fr:-MezVHFZ3w8ZbPtzm44B:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/4d1c6671f8876a8fc18c09ac30874ebb885f8cdc/pkg/debugapi/postage.go#L300)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

FTR the efficient zero check for bigint is `len(pricePerBlock.Bits()) == 0` 20 times faster even without spurious allocation 
</blockquote></details>

Done.
___
*[pkg/debugapi/postage.go, line 305 at r1](https://reviewable.io/reviews/ethersphere/bee/2336#-MeqGUqQBYLV_1-J9ogw:-MezVOqY3cwwcL0pvp0r:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/4d1c6671f8876a8fc18c09ac30874ebb885f8cdc/pkg/debugapi/postage.go#L305)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

you save allocations with:

```
ee.Div(ee, pricePerBlock)
ee.Mul(ee,  big.NewInt(blockTime))
return ee.Uint64(), nil
```
</blockquote></details>

Done.
___
*[pkg/debugapi/postage.go, line 306 at r1](https://reviewable.io/reviews/ethersphere/bee/2336#-MeqQHR7BMxttlc7RfLi:-MezVRqd1Fe-_MrKbcwq:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/4d1c6671f8876a8fc18c09ac30874ebb885f8cdc/pkg/debugapi/postage.go#L306)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

consider doing multiplication first for precision
</blockquote></details>

Done.

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2336)* status: 3 of 7 files reviewed, 6 unresolved discussions (waiting on @acud, @aloknerurkar, and @zelig)

___
*[pkg/debugapi/postage_test.go, line 220 at r1](https://reviewable.io/reviews/ethersphere/bee/2336#-MeqOLcR6qdyAjb8nUrX:-MezWmKn3YDA4aDpbiBd:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/4d1c6671f8876a8fc18c09ac30874ebb885f8cdc/pkg/debugapi/postage_test.go#L220)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

a comment would be nice how you get this: 
`((value-totalAmount)/pricePerBlock)*blockTime=((20-5)/2)*2`. 
Now this is of course 15, which shows that by doing division first on int you lose precision.
</blockquote></details>

Done.

**Review by zelig — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2336)* status: all files reviewed, 6 unresolved discussions (waiting on @acud, @aloknerurkar, and @zelig)

**Review by acud — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2336)* status: all files reviewed, 7 unresolved discussions (waiting on @aloknerurkar, @mrekucci, and @zelig)

___
*[pkg/debugapi/postage.go, line 136 at r2](https://reviewable.io/reviews/ethersphere/bee/2336#-Mf1cy3wBLMpbwfx_hNj:-Mf1cy3wBLMpbwfx_hNk:b-sv6oiv) ([raw file](https://github.com/ethersphere/bee/blob/af1c39ae9f4fac43dfd2472f46514073f65be391/pkg/debugapi/postage.go#L136)):*
> ```Go
> 		batchTTL, err := s.estimateBatchTTL(v.ID())
> 		if err != nil {
> 			s.logger.Errorf("get stamp issuer: estimate batch expiration: %v", err)
> ```

the sequence here should be:
```
Debugf()
Error(f)
```
This is the pattern we use in other files in the API packages. The Error line is meant to give general information to the user, and the debug line is meant to give more meaningful debugging information. If you could please amend it. There are other culprits in this same file

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2336)* status: all files reviewed, 7 unresolved discussions (waiting on @acud, @aloknerurkar, and @zelig)

___
*[pkg/debugapi/postage.go, line 136 at r2](https://reviewable.io/reviews/ethersphere/bee/2336#-Mf1cy3wBLMpbwfx_hNj:-Mf1t8xk9hU6goHKqISu:b-4q2baz) ([raw file](https://github.com/ethersphere/bee/blob/af1c39ae9f4fac43dfd2472f46514073f65be391/pkg/debugapi/postage.go#L136)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

the sequence here should be:
```
Debugf()
Error(f)
```
This is the pattern we use in other files in the API packages. The Error line is meant to give general information to the user, and the debug line is meant to give more meaningful debugging information. If you could please amend it. There are other culprits in this same file
</blockquote></details>

Yes, I copied it from the other place where it was already wrong. Also fixed in the original place.

**Review by acud — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2336)* status: all files reviewed, 6 unresolved discussions (waiting on @aloknerurkar and @zelig)

**Pull request merged**
