### PR TITLE
feat: cache on forwarding in retrieval

### PR DESCRIPTION
**Pull request by metacertain**
This PR introduces a configurable behaviour to run the node caching forwarded chunks for opportunistic later reuse

This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2234)

### CODE REVIEW

**Review by zelig — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2234)* status: all files reviewed, 3 unresolved discussions (waiting on @metacertain)

___
*[pkg/retrieval/retrieval.go, line 416 at r1](https://reviewable.io/reviews/ethersphere/bee/2234#-MdI-tbF1t4d0Psj9hqm:-MdI-tbF1t4d0Psj9hqn:b-aszis3) ([raw file](https://github.com/ethersphere/bee/blob/c36b24b2baf1ab53fdfeb0799a8856a0e6b0f17c/pkg/retrieval/retrieval.go#L416)):*
> ```Go
> 	addr := swarm.NewAddress(req.Addr)
> 
> 	stored := false
> ```

use 
`var forwarded bool`
___
*[pkg/retrieval/retrieval.go, line 424 at r1](https://reviewable.io/reviews/ethersphere/bee/2234#-MdI03Yg015c8t1tvisi:-MdI03Yg015c8t1tvisj:b-nfzc3v) ([raw file](https://github.com/ethersphere/bee/blob/c36b24b2baf1ab53fdfeb0799a8856a0e6b0f17c/pkg/retrieval/retrieval.go#L424)):*
> ```Go
> 			if err != nil {
> 				return fmt.Errorf("retrieve chunk: %w", err)
> 			}
> ```

forwarded=true 
and no need for else clause
___
*[pkg/retrieval/retrieval.go, line 437 at r1](https://reviewable.io/reviews/ethersphere/bee/2234#-MdI0BQL1v9HqHKGhgQC:-MdI0BQL1v9HqHKGhgQD:b-q5jeo7) ([raw file](https://github.com/ethersphere/bee/blob/c36b24b2baf1ab53fdfeb0799a8856a0e6b0f17c/pkg/retrieval/retrieval.go#L437)):*
> ```Go
> 	}
> 
> 	if s.caching && !stored {
> ```

if s.caching && forwarded {

**Comment by zelig** [comment]
this PR is missing description. 
I am not sure this should be a command line option. it is worth keeping no caching as a debug option for testing.

**Comment by acud** [comment]
@metacertain since we also have unit tests that test for forwarding, could we please tweak one of the tests to check that the forwarder also stored the chunk?

**Comment by metacertain** [comment]
> this PR is missing description.
> I am not sure this should be a command line option. it is worth keeping no caching as a debug option for testing.

request to make it cli flag driven came from @acud in order to be able to run CI without caching

**Comment by acud** [comment]
I think that CLI flag is fine for now. We should introduce build variables at some point and this can be a good candidate, alongside with other hocus pocus we do elsewhere

**Review by acud — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2234)* status: all files reviewed, 6 unresolved discussions (waiting on @metacertain)

___
*[pkg/recovery/repair_test.go, line 236 at r3](https://reviewable.io/reviews/ethersphere/bee/2234#-MdSBF9eEKFB0auJ55uv:-MdSBF9eEKFB0auJ55uw:baprw5f) ([raw file](https://github.com/ethersphere/bee/blob/35077623d143e2a6b298e80a0c4c8178545033db/pkg/recovery/repair_test.go#L236)):*
> ```Go
> 	}}
> 
> 	server := retrieval.New(swarm.ZeroAddress, mockStorer, nil, ps0, logger, serverMockAccounting, pricerMock, nil, true)
> ```

nit, i think that for unit tests we should generally have no forwarding enabled
___
*[pkg/retrieval/retrieval_test.go, line 64 at r3](https://reviewable.io/reviews/ethersphere/bee/2234#-MdSBkv84DasT2QVq4MX:-MdSBkv84DasT2QVq4MY:b-j6y6jq) ([raw file](https://github.com/ethersphere/bee/blob/35077623d143e2a6b298e80a0c4c8178545033db/pkg/retrieval/retrieval_test.go#L64)):*
> ```Go
> 
> 	// create the server that will handle the request and will serve the response
> 	server := retrieval.New(swarm.MustParseHexAddress("0034"), mockStorer, nil, nil, logger, serverMockAccounting, pricerMock, nil, true)
> ```

same here, tests that don't explicitly test for forwarding should have forwarding disabled as it might contaminate the test assumptions. same for the tests below too
___
*[pkg/retrieval/retrieval_test.go, line 318 at r3](https://reviewable.io/reviews/ethersphere/bee/2234#-MdSC0ex9CokeRkjUdsU:-MdSC0ex9CokeRkjUdsV:bdwm1e7) ([raw file](https://github.com/ethersphere/bee/blob/35077623d143e2a6b298e80a0c4c8178545033db/pkg/retrieval/retrieval_test.go#L318)):*
> ```Go
> 	}
> 
> 	server1 := retrieval.New(serverAddress1, serverStorer1, nil, noPeerSuggester, logger, accountingmock.NewAccounting(), pricerMock, nil, true)
> ```

same here, and below

**Review by zelig — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2234)* status: all files reviewed, 6 unresolved discussions (waiting on @metacertain)

**Review by acud — APPROVED** [review]

**Review by mrekucci — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2234)* status: all files reviewed, 7 unresolved discussions (waiting on @metacertain)

___
*[cmd/bee/cmd/cmd.go, line 249 at r5](https://reviewable.io/reviews/ethersphere/bee/2234#-MeZ5w3DEexXLlC8LLNA:-MeZ5w3DEexXLlC8LLNB:b-zho312) ([raw file](https://github.com/ethersphere/bee/blob/2aeac06ca9d94ddcb84fdfcd632f61ebe8f02f9f/cmd/bee/cmd/cmd.go#L249)):*
> ```Go
> 	cmd.Flags().Duration(optionWarmUpTime, time.Minute*20, "time to warmup the node before pull/push protocols can be kicked off.")
> 	cmd.Flags().Bool(optionNameMainNet, false, "triggers connect to main net bootnodes.")
> 	cmd.Flags().Bool(optionNameRetrievalCaching, true, "enable forwarded content caching")
> ```

Referring to the description of the boolean flag above, shouldn't we be consistent and use `enables` instead of `enable`?

**Review by acud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2234)* status: all files reviewed, 6 unresolved discussions (waiting on @metacertain and @mrekucci)

___
*[cmd/bee/cmd/cmd.go, line 249 at r5](https://reviewable.io/reviews/ethersphere/bee/2234#-MeZ5w3DEexXLlC8LLNA:-MedAVlKCq6137Vecmaj:bam8mgw) ([raw file](https://github.com/ethersphere/bee/blob/2aeac06ca9d94ddcb84fdfcd632f61ebe8f02f9f/cmd/bee/cmd/cmd.go#L249)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

Referring to the description of the boolean flag above, shouldn't we be consistent and use `enables` instead of `enable`?
</blockquote></details>

this isn't standardized across the other flags... you can scroll up and see. both are grammatically correct IMO so no biggie

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2234)* status: all files reviewed, 6 unresolved discussions (waiting on @acud and @metacertain)

___
*[cmd/bee/cmd/cmd.go, line 249 at r5](https://reviewable.io/reviews/ethersphere/bee/2234#-MeZ5w3DEexXLlC8LLNA:-MedFest-OxKjDAwmIaw:b40d9gx) ([raw file](https://github.com/ethersphere/bee/blob/2aeac06ca9d94ddcb84fdfcd632f61ebe8f02f9f/cmd/bee/cmd/cmd.go#L249)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

this isn't standardized across the other flags... you can scroll up and see. both are grammatically correct IMO so no biggie
</blockquote></details>

Yes, I noticed that. Don't we want to standardize that though?

**Review by zelig — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2234)* status: all files reviewed, 4 unresolved discussions (waiting on @acud and @metacertain)

**Pull request merged**
