### PR TITLE
Quick-fix unpinning error caused by a manifest serialization bug

### PR DESCRIPTION
**Pull request by mrekucci**
This quick-fix prevents the mantaray manifest IterateAddresses method
walker to fail when it encounters an empty address, otherwise, the unpin
traversal operation for the manifest fails.

### CODE REVIEW

**Comment by mrekucci** [comment]
The state returned by `DebugIndices()` before the unpinning:

```sh
map[string]int{"gcExcludeIndex":11, "gcIndex":0, "gcSize":0, "pinIndex":11, "pullIndex":11, "pushIndex":11, "retrievalAccessIndex":0, "retrievalDataIndex":11}
```

and after the unpinning:

```sh
map[string]int{"gcExcludeIndex":11, "gcIndex":0, "gcSize":0, "pinIndex":0, "pullIndex":11, "pushIndex":11, "retrievalAccessIndex":0, "retrievalDataIndex":11}
```

**Review by zelig — COMMENTED** [review]
should this not be fixed in the walk iterator within the mantaray subpkg?

**Review by acud — APPROVED** [review]
LGTM Thanks!

**Comment by mrekucci** [comment]
> should this not be fixed in the walk iterator within the mantaray subpkg?

From the responsibility perspective, I think it would make more sense, but this closure is passed to the mantaray subpackage functions/methods and the functions/methods are eighter calling the closure directly or passing it to another function/method so the call graph is not that simple, that's why fixing it here, relatively close to the source, is the best tradeoff in terms of clarity.

**Comment by acud** [comment]
agree with @mrekucci, let's not spend too much time on this. I'd like to get this through as is. We can make things pretty when we give enough time to sort out mantaray as a whole as previously discussed @zelig

**Review by esadakar — APPROVED** [review]

**Pull request merged**
