### PR TITLE
Update start.go

### PR DESCRIPTION
**Pull request by wendydv1989**
Back to the old friendly Bee

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2148)

### CODE REVIEW

**Review by ralph-pichler — APPROVED** [review]

**Comment by ralph-pichler** [comment]
commit message needs to be adjusted

**Review by zelig — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wendydv1989)

**Comment by cppfuns** [comment]
Hahaha, I think the 0.6 logo is still good-looking, the old version of the bee looks like a fly

**Comment by Eknir** [comment]
> Hahaha, I think the 0.6 logo looks more beautiful and cute. The old version of the bee looks like a fly @Eknir

So many people, so many preferences

**Pull request merged**
