### PR TITLE
bump version to 0.3.2

### PR DESCRIPTION
**Pull request by janos**
Set the next version in code.

### CODE REVIEW

**Comment by zbiljic** [comment]
@janos Should this PR maybe also update OpenAPI documentation files ?

**Comment by janos** [comment]
> @janos Should this PR maybe also update OpenAPI documentation files ?

I am not sure if we need to update that version if api is not changed. Maybe it is good to hear other opinions also.

**Review by vandot — APPROVED** [review]

**Review by svetomir — APPROVED** [review]

**Comment by acud** [comment]
> > @janos Should this PR maybe also update OpenAPI documentation files ?
> 
> I am not sure if we need to update that version if api is not changed. Maybe it is good to hear other opinions also.

i think we never really said anything about maintaining a separate version for the api. in which case we should just leave it alone for now, unless some changes arise. not sure if i really have an opinion here. would make sense to bump it just when it changes

**Comment by acud** [comment]
also, given that we make the same error of not bumping the version numbers - could we please prepare together a release checklist?

**Review by acud — APPROVED** [review]
Yassu

**Comment by janos** [comment]
Release checklist is needed. We should make it.

Let's update api version in specs when we agree on the checklist.

**Pull request merged**
