### PR TITLE
feat: unreserve on-demand

### PR DESCRIPTION
**Pull request by acud**
https://github.com/ethersphere/bee/issues/2040

This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071)

TODO: 
- ~~on batchstore reset we should delete all the fifo queue items~~ (already implicitly done by the `Reset` method)
- ~~retrieval protocol has to check postage stamp validity and force cache in case the stamp is invalid~~

### CODE REVIEW

**Review by zelig — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071)* status: all files reviewed, 10 unresolved discussions (waiting on @acud)

___
*[pkg/localstore/gc.go, line 47 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc15gXT1vLFiwwAvP4w:-Mc15gXT1vLFiwwAvP4x:b-wstkch) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/localstore/gc.go#L47)):*
> ```Go
> 	// not to overwhelm the cache with too many chunks which it will flush
> 	// anyway.
> 	reserveCollectionRatio = 0.5
> ```

this should be more like 10% max
___
*[pkg/localstore/gc_test.go, line 1017 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1Kf9-3cpBZ2uIAlNi:-Mc1Kf9-3cpBZ2uIAlNj:b17emq3) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/localstore/gc_test.go#L1017)):*
> ```Go
> 	})
> 	db.SetUnreserveFunc(unres)
> 	fmt.Println(1)
> ```

debug code
___
*[pkg/postage/batchstore/reserve.go, line 52 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1MoSX2wj_0VAE10tu:-Mc1MoSX2wj_0VAE10tv:bvk0zwo) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/postage/batchstore/reserve.go#L52)):*
> ```Go
> var Capacity = exp2(22)
> 
> const unreservePage = 50 // how many entries to ask for deletion
> ```

what is the purpose of this?
___
*[pkg/postage/batchstore/reserve.go, line 73 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1U_m1-MdTvVpq2ctu:-Mc1U_m1-MdTvVpq2ctv:brb8dec) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/postage/batchstore/reserve.go#L73)):*
> ```Go
> // dequeued by the localstore once the storage fills up.
> func (s *store) unreserve(b *postage.Batch, radius uint8) error {
> 	c, err := s.getQueueCardinality()
> ```

this need not be peristed in fact. just make sure its a value on s atomically incremented
___
*[pkg/postage/batchstore/reserve.go, line 88 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1Q7181aDRu6NmNjWt:-Mc1Q7181aDRu6NmNjWu:b-srxgez) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/postage/batchstore/reserve.go#L88)):*
> ```Go
> }
> 
> func (s *store) Unreserve() error {
> ```

not sure why this is not an actual iterator. Make it an iterator and you can 
- eliminate the page constant, 
- get rid of unreserveFunc and its settter
- take onset as a parameter, then you can move pruning to an async routine 
___
*[pkg/postage/batchstore/reserve.go, line 106 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1Ns870MMTsmC3Wi_R:-Mc1Ns870MMTsmC3Wi_S:b-8bqrgh) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/postage/batchstore/reserve.go#L106)):*
> ```Go
> 		entries[i] = string(key)
> 		i++
> 		if i == unreservePage {
> ```

return i==unreserePage, nil
___
*[pkg/postage/batchstore/reserve.go, line 114 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1RYmaAyD0H6TCgQPb:-Mc1RYmaAyD0H6TCgQPc:ba1ah5n) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/postage/batchstore/reserve.go#L114)):*
> ```Go
> 		return err
> 	}
> 	for _, v := range entries {
> ```

this better be asynchronous and done on demand 
___
*[pkg/postage/batchstore/reserve.go, line 366 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1WEDTEzLc3ArvpC_w:-Mc1WEDTEzLc3ArvpC_x:b-inz8ed) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/postage/batchstore/reserve.go#L366)):*
> ```Go
> }
> 
> func (s *store) getQueueCardinality() (val uint64, err error) {
> ```

just needs to be initialised as the the topmost index
___
*[pkg/postage/batchstore/reserve.go, line 375 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1WYGX0VHLO6bwqrfz:-Mc1WYGX0VHLO6bwqrg-:b-7jl281) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/postage/batchstore/reserve.go#L375)):*
> ```Go
> }
> 
> func (s *store) putQueueCardinality(val uint64) error {
> ```

same
___
*[pkg/postage/batchstore/reserve_test.go, line 839 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1Pps88Eb5N2RpcOcQ:-Mc1Pps88Eb5N2RpcOcR:b-xjf4k8) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/postage/batchstore/reserve_test.go#L839)):*
> ```Go
> }
> 
> func TestUnreserveItemSequence(t *testing.T) {
> ```

what is this testing. seems a bit complex

**Comment by zelig** [comment]
- mock batchstore now fails on interface (no Unreserve)
-  Unreserve function (hopefully iterator) can take onset and bucketDepth

TODO: 
- let r be radius part of latest unreserveItem picked up by localstore via iterator call
- r+1 to be saved as storage radius within reserveState to expose it through the API for price oracle?
- remember cursor sequence count (at constructor call initialise from the queue), so that  it is not taken from level db at every call

**Review by zelig — COMMENTED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071)* status: all files reviewed, 12 unresolved discussions (waiting on @acud)

___
*[pkg/postage/interface.go, line 37 at r2](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc4SEu94vWIcRcu0yOM:-Mc4SEu94vWIcRcu0yON:b-tgse0p) ([raw file](https://github.com/ethersphere/bee/blob/d87d4a205beb1e67d8e3e645bcbfe508542677a4/pkg/postage/interface.go#L37)):*
> ```Go
> 	GetReserveState() *ReserveState
> 	SetRadiusSetter(RadiusSetter)
> 	Unreserve(UnreserveIteratorFn) error
> ```

this should be a nother interface
___
*[pkg/postage/batchstore/reserve.go, line 71 at r2](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc4SPoY78jkqm1w7pIK:-Mc4SPoY78jkqm1w7pIL:b-3uejo0) ([raw file](https://github.com/ethersphere/bee/blob/d87d4a205beb1e67d8e3e645bcbfe508542677a4/pkg/postage/batchstore/reserve.go#L71)):*
> ```Go
> // dequeued by the localstore once the storage fills up.
> func (s *store) unreserve(b []byte, radius uint8) error {
> 	c, err := s.getQueueCardinality()
> ```

this can be optimised
___
*[pkg/postage/batchstore/mock/store.go, line 143 at r2](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc4SwSY3FSI73tEgLgE:-Mc4SwSY3FSI73tEgLgF:bdh9cqk) ([raw file](https://github.com/ethersphere/bee/blob/d87d4a205beb1e67d8e3e645bcbfe508542677a4/pkg/postage/batchstore/mock/store.go#L143)):*
> ```Go
> 	return rs
> }
> func (bs *BatchStore) Unreserve(_ postage.UnreserveIteratorFn) {
> ```

not needed if on a different interface

**Comment by zelig** [comment]
LGTM when tests pass

**Review by zelig — APPROVED** [review]
> Reviewed 6 of 8 files at r3, 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071)* status: all files reviewed, 17 unresolved discussions (waiting on @acud)

___
*[pkg/localstore/reserve_test.go, line 302 at r4](https://reviewable.io/reviews/ethersphere/bee/2071#-McGFFGY024--UUeyz2V:-McGFFGY024--UUeyz2W:bt7y0sj) ([raw file](https://github.com/ethersphere/bee/blob/628f756418258ee4c941a2d0a1aa5a5b8d7f228b/pkg/localstore/reserve_test.go#L302)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		mtx.Lock()
> ```

this lock is not needed right?
___
*[pkg/localstore/reserve_test.go, line 389 at r4](https://reviewable.io/reviews/ethersphere/bee/2071#-McGFXwv9YyoBBLFouh2:-McGFXwv9YyoBBLFouh3:bjxktlf) ([raw file](https://github.com/ethersphere/bee/blob/628f756418258ee4c941a2d0a1aa5a5b8d7f228b/pkg/localstore/reserve_test.go#L389)):*
> ```Go
> 
> 	unres := func(f postage.UnreserveIteratorFn) error {
> 		mtx.Lock()
> ```

why lock is needed
___
*[pkg/node/node.go, line 334 at r4](https://reviewable.io/reviews/ethersphere/bee/2071#-McGGlFZBMsV4fL7P8YG:-McGGlFZBMsV4fL7P8YH:bqs3s5x) ([raw file](https://github.com/ethersphere/bee/blob/628f756418258ee4c941a2d0a1aa5a5b8d7f228b/pkg/node/node.go#L334)):*
> ```Go
> 	b.p2pHalter = p2ps
> 
> 	var unreserveFn func([]byte, uint8) (uint64, error)
> ```

maybe comment here about this black magic going on to make reciprocal dependency painless
___
*[pkg/postage/batchstore/reserve.go, line 60 at r4](https://reviewable.io/reviews/ethersphere/bee/2071#-McGHYiND8tEtCzeZQdr:-McGHYiND8tEtCzeZQds:buai3dt) ([raw file](https://github.com/ethersphere/bee/blob/628f756418258ee4c941a2d0a1aa5a5b8d7f228b/pkg/postage/batchstore/reserve.go#L60)):*
> ```Go
> 	// would like to guarantee that all chunks are stored
> 	Radius        uint8 `json:"radius"`
> 	StorageRadius uint8 `json:"storageRadius"`
> ```

add comment: the current actual radius of eviction/storage
___
*[pkg/postage/batchstore/reserve.go, line 110 at r4](https://reviewable.io/reviews/ethersphere/bee/2071#-McGI6479YpCJ2P6R49t:-McGI6479YpCJ2P6R49u:bbgeagw) ([raw file](https://github.com/ethersphere/bee/blob/628f756418258ee4c941a2d0a1aa5a5b8d7f228b/pkg/postage/batchstore/reserve.go#L110)):*
> ```
> v.Radius != swarm.MaxPO+1
> ```
this condition is no longer needed

**Review by acud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071)* status: all files reviewed, 17 unresolved discussions (waiting on @acud and @zelig)

___
*[pkg/localstore/gc.go, line 47 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc15gXT1vLFiwwAvP4w:-Mc3JUDy5LkWdcWhR1GV:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/localstore/gc.go#L47)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

this should be more like 10% max
</blockquote></details>

Done.
___
*[pkg/localstore/gc_test.go, line 1017 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1Kf9-3cpBZ2uIAlNi:-Mc3JW0XD50uN0ev8rXm:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/localstore/gc_test.go#L1017)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

debug code
</blockquote></details>

Done.
___
*[pkg/localstore/reserve_test.go, line 302 at r4](https://reviewable.io/reviews/ethersphere/bee/2071#-McGFFGY024--UUeyz2V:-McIrC8c-sM4ExnqBY0W:bxagmds) ([raw file](https://github.com/ethersphere/bee/blob/628f756418258ee4c941a2d0a1aa5a5b8d7f228b/pkg/localstore/reserve_test.go#L302)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

this lock is not needed right?
</blockquote></details>

race detector
___
*[pkg/localstore/reserve_test.go, line 389 at r4](https://reviewable.io/reviews/ethersphere/bee/2071#-McGFXwv9YyoBBLFouh2:-McIrEyCEfVAX6-aDe12:bxagmds) ([raw file](https://github.com/ethersphere/bee/blob/628f756418258ee4c941a2d0a1aa5a5b8d7f228b/pkg/localstore/reserve_test.go#L389)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

why lock is needed
</blockquote></details>

race detector
___
*[pkg/postage/batchstore/reserve.go, line 106 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1Ns870MMTsmC3Wi_R:-McIrQXb63dKZjOxbzEi:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/postage/batchstore/reserve.go#L106)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

return i==unreserePage, nil
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 110 at r4](https://reviewable.io/reviews/ethersphere/bee/2071#-McGI6479YpCJ2P6R49t:-McIsq6h8eiIILRhCB-j:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/628f756418258ee4c941a2d0a1aa5a5b8d7f228b/pkg/postage/batchstore/reserve.go#L110)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

> ```
> v.Radius != swarm.MaxPO+1
> ```
this condition is no longer needed          
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve_test.go, line 839 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1Pps88Eb5N2RpcOcQ:-McIrLkQ2KETq0dtim3V:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/postage/batchstore/reserve_test.go#L839)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

what is this testing. seems a bit complex 
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/mock/store.go, line 143 at r2](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc4SwSY3FSI73tEgLgE:-McIt-7VDEA2u01moysI:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/d87d4a205beb1e67d8e3e645bcbfe508542677a4/pkg/postage/batchstore/mock/store.go#L143)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

not needed if on a different interface
</blockquote></details>

Done.

**Review by zelig — APPROVED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071)* status: all files reviewed, 12 unresolved discussions (waiting on @acud and @zelig)

___
*[pkg/postage/batchstore/reserve.go, line 110 at r4](https://reviewable.io/reviews/ethersphere/bee/2071#-McGI6479YpCJ2P6R49t:-McJwHCh1LyuctPun4uk:bl4e86s) ([raw file](https://github.com/ethersphere/bee/blob/628f756418258ee4c941a2d0a1aa5a5b8d7f228b/pkg/postage/batchstore/reserve.go#L110)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done

**Review by zelig — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071)* status: all files reviewed, 13 unresolved discussions (waiting on @acud and @zelig)

___
*[pkg/localstore/gc.go, line 47 at r6](https://reviewable.io/reviews/ethersphere/bee/2071#-McNJWlw3DimnuKkKTj_:-McNJWlw3DimnuKkKTja:bfr6jx8) ([raw file](https://github.com/ethersphere/bee/blob/ffdebc8958620bdc99a85627bd900ded45b8f1cc/pkg/localstore/gc.go#L47)):*
> ```Go
> 	// not to overwhelm the cache with too many chunks which it will flush
> 	// anyway.
> 	reserveCollectionRatio = 0.5
> ```

this wont work. as cache size is configurable, if it is twice the reserve size, we may end up with 100% of reserve purged in gc

**Review by zelig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071)* status: all files reviewed, 12 unresolved discussions (waiting on @acud and @zelig)

**Review by zelig — APPROVED** [review]

**Review by zelig — APPROVED** [review]
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071)* status: all files reviewed, 11 unresolved discussions (waiting on @acud and @zelig)

**Review by mrekucci — COMMENTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 14 files at r2, 2 of 8 files at r3, 3 of 12 files at r4, 2 of 5 files at r5, 3 of 4 files at r6, 2 of 3 files at r7, 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071)* status: all files reviewed, 13 unresolved discussions (waiting on @acud and @zelig)

___
*[pkg/localstore/mode_put.go, line 226 at r8](https://reviewable.io/reviews/ethersphere/bee/2071#-McP77EiC-GBp3js1bsj:-McP77EiC-GBp3js1bsk:b-o9s63r) ([raw file](https://github.com/ethersphere/bee/blob/a88971f54e09b7354c61f8711c5521c73972a47a/pkg/localstore/mode_put.go#L226)):*
> ```Go
> 			if !errors.Is(err, leveldb.ErrNotFound) {
> 				return false, 0, err
> 			}
> ```

The error is silentely ignored here, don't you want to at least log it?
___
*[pkg/localstore/mode_put.go, line 373 at r8](https://reviewable.io/reviews/ethersphere/bee/2071#-McP7VuwAHI6yIqQaX_P:-McP7VuwAHI6yIqQaX_Q:bqbbs9g) ([raw file](https://github.com/ethersphere/bee/blob/a88971f54e09b7354c61f8711c5521c73972a47a/pkg/localstore/mode_put.go#L373)):*
> ```Go
> 			if !errors.Is(err, leveldb.ErrNotFound) {
> 				return false, 0, err
> 			}
> ```

The same problem with error as above.
___
*[pkg/localstore/reserve.go, line 80 at r8](https://reviewable.io/reviews/ethersphere/bee/2071#-McP8u495pD0v_YiH4Ci:-McP8u4A9ZMNECGMso_f:b-d0ytog) ([raw file](https://github.com/ethersphere/bee/blob/a88971f54e09b7354c61f8711c5521c73972a47a/pkg/localstore/reserve.go#L80)):*
> ```Go
> 	}
> 
> 	if radius != swarm.MaxPO+1 {
> ```

Is this specific just for this one case, what about if `radius > swarm.MaxPO+1` or `radius < swarm.MaxPO+1`?
___
*[pkg/postage/batchstore/export_test.go, line 26 at r8](https://reviewable.io/reviews/ethersphere/bee/2071#-McPA_-cAF_LtyuBdDCt:-McPA_-cAF_LtyuBdDCu:b4j9o5u) ([raw file](https://github.com/ethersphere/bee/blob/a88971f54e09b7354c61f8711c5521c73972a47a/pkg/postage/batchstore/export_test.go#L26)):*
> ```Go
> }
> 
> func SetUnreserveFunc(s postage.Storer, f func([]byte, uint8) error) {
> ```

`f` -> `fn`.
___
*[pkg/postage/batchstore/reserve.go, line 128 at r8](https://reviewable.io/reviews/ethersphere/bee/2071#-McPBd5M0GKzcmgDmUqA:-McPBd5M0GKzcmgDmUqB:bkldr03) ([raw file](https://github.com/ethersphere/bee/blob/a88971f54e09b7354c61f8711c5521c73972a47a/pkg/postage/batchstore/reserve.go#L128)):*
> ```Go
> 		return false, nil
> 	})
> 	if err != nil {
> ```

Not need, just simple`return s.store.Iterate(...` will do.

**Review by acud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071)* status: all files reviewed, 13 unresolved discussions (waiting on @acud, @mrekucci, and @zelig)

___
*[pkg/localstore/mode_put.go, line 226 at r8](https://reviewable.io/reviews/ethersphere/bee/2071#-McP77EiC-GBp3js1bsj:-McPQBua4Ej1OcPqEjr3:b-oaypgw) ([raw file](https://github.com/ethersphere/bee/blob/a88971f54e09b7354c61f8711c5521c73972a47a/pkg/localstore/mode_put.go#L226)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

The error is silentely ignored here, don't you want to at least log it?
</blockquote></details>

no. if we don't find the item in the index then we store the chunk anyway. if we find the entry in the index we check whether the chunk falls within the radius which is stored in the index (the index keeps track of the minimum radius of chunks we'd like to keep for a certain batch. if the chunk PO is greater than that value then we keep it, if we dont know and the stamp is valid then we keep it and worst case get the eviction directive later through the batchstore iterator when reserve eviction is triggered)
___
*[pkg/localstore/mode_put.go, line 373 at r8](https://reviewable.io/reviews/ethersphere/bee/2071#-McP7VuwAHI6yIqQaX_P:-McPQgFi9wLp03dq1yq9:b-7fpjjf) ([raw file](https://github.com/ethersphere/bee/blob/a88971f54e09b7354c61f8711c5521c73972a47a/pkg/localstore/mode_put.go#L373)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

The same problem with error as above.
</blockquote></details>

see above ^^
___
*[pkg/localstore/reserve.go, line 80 at r8](https://reviewable.io/reviews/ethersphere/bee/2071#-McP8u495pD0v_YiH4Ci:-McPPunFBPrxbboUv2Hr:bta2szm) ([raw file](https://github.com/ethersphere/bee/blob/a88971f54e09b7354c61f8711c5521c73972a47a/pkg/localstore/reserve.go#L80)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

Is this specific just for this one case, what about if `radius > swarm.MaxPO+1` or `radius < swarm.MaxPO+1`?
</blockquote></details>

this is specific to one case only. in the case that `radius == swarm.MaxPO+1` we do not persist the entry in the postageRadiusIndex. It can never be bigger than `swarm.MaxPO+1`
___
*[pkg/postage/batchstore/reserve.go, line 73 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1U_m1-MdTvVpq2ctu:-McPPiagD2_060LwasKd:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/postage/batchstore/reserve.go#L73)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

this need not be peristed in fact. just make sure its a value on s atomically incremented
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 88 at r1](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc1Q7181aDRu6NmNjWt:-McPPhW12-EVidC16Khv:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/421ad0a7a1b47cd6c506b848f4e0202c33dad168/pkg/postage/batchstore/reserve.go#L88)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

not sure why this is not an actual iterator. Make it an iterator and you can 
- eliminate the page constant, 
- get rid of unreserveFunc and its settter
- take onset as a parameter, then you can move pruning to an async routine 
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 71 at r2](https://reviewable.io/reviews/ethersphere/bee/2071#-Mc4SPoY78jkqm1w7pIK:-McPPiBB9Q0uxMv3dl4C:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/d87d4a205beb1e67d8e3e645bcbfe508542677a4/pkg/postage/batchstore/reserve.go#L71)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

this can be optimised
</blockquote></details>

Done.
___
*[pkg/postage/batchstore/reserve.go, line 60 at r4](https://reviewable.io/reviews/ethersphere/bee/2071#-McGHYiND8tEtCzeZQdr:-McPPksA5bVBe4ZJD_7S:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/628f756418258ee4c941a2d0a1aa5a5b8d7f228b/pkg/postage/batchstore/reserve.go#L60)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

add comment: the current actual radius of eviction/storage
</blockquote></details>

Done.

**Review by mrekucci — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071#-:-McPYOQHBV86uzWh0YqU:bnfp4nl)* status: 17 of 19 files reviewed, 11 unresolved discussions (waiting on @acud, @mrekucci, and @zelig)

**Review by zelig — APPROVED** [review]
> Reviewed 2 of 5 files at r8, 12 of 12 files at r9.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2071)* status: all files reviewed, 9 unresolved discussions (waiting on @acud and @zelig)

___
*[pkg/localstore/localstore.go, line 210 at r9](https://reviewable.io/reviews/ethersphere/bee/2071#-McVrNtGCiI9c5aDY4PJ:-McVrNtGCiI9c5aDY4PK:b2nif8j) ([raw file](https://github.com/ethersphere/bee/blob/553385b80c965f84e1cde68cbc9112f33719b84b/pkg/localstore/localstore.go#L210)):*
> ```Go
> 
> 	db = &DB{
> 		stateStore:      ss,
> ```

why
___
*[pkg/node/node.go, line 359 at r9](https://reviewable.io/reviews/ethersphere/bee/2071#-McVr_ZdB1c3XAheeGMa:-McVr_ZdB1c3XAheeGMb:b3kre) ([raw file](https://github.com/ethersphere/bee/blob/553385b80c965f84e1cde68cbc9112f33719b84b/pkg/node/node.go#L359)):*
> ```Go
> 	}
> 
> 	fmt.Println("starting bee...")
> ```

?

**Pull request merged**
