### PR TITLE
Add notifier to topology driver in debug API

### PR DESCRIPTION
**Pull request by r0qs**
Fix https://github.com/ethersphere/bee/issues/1414

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1585)

### CODE REVIEW

**Comment by acud** [comment]
@r0qs thanks for the PR! I think that there could be a data race here, if we connect to the peer using the p2p dependency. If the peer disconnects quickly, the `Connected` notifier will still be called, resulting in a rouge peer in kademlia which will never be removed. A potentially favorable approach would be to not call the p2p dial method at all from the debug api, but rather add a flag that forces dialing to `AddPeer` in kademlia, forcing kademlia to both add the peer to the known peers list but to also immediately connect to it, resulting in a consistent state also if the peer disconnects, since the connect call is under lock, it will not propagate until the `connect` returns. WDYT?

**Comment by r0qs** [comment]
Hi @acud,

ah ok, I see now. Sorry for the misunderstanding of the flag approach. I'll revert the changes and apply the suggestions.

But how can I get the overlay address of the peer without attempt to dial? Or there is another way to get the overlay based on the multi-address?

**Comment by acud** [comment]
@r0qs can we have a rebase? happy to merge this once conflicts are out of the way

**Comment by acud** [comment]
closing due to inactivity

**Comment by r0qs** [comment]
Hey, sorry for the late reply. I did a rebase and open the PR again https://github.com/ethersphere/bee/pull/2093

**Pull request closed without merging**
