### PR TITLE
feat: add bucket data endpoint

### PR DESCRIPTION
**Pull request by acud**
This PR adds a debug api endpoint to print out extended debugging information in regards to a single batch, so that we can track collisions on particular buckets (and hopefully plot them to spot anomalies)

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2321)

### CODE REVIEW

**Review by mrekucci — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2321)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud)

___
*[openapi/SwarmCommon.yaml, line 360 at r1](https://reviewable.io/reviews/ethersphere/bee/2321#-MeAGQlb39RIddd3XQX1:-MeAGQlb39RIddd3XQX2:bw13h2h) ([raw file](https://github.com/ethersphere/bee/blob/95aea4306cc0b13a312e0254aca8223ae9417887/openapi/SwarmCommon.yaml#L360)):*
> ```YAML
>             $ref: "#/components/schemas/StampBucketData"
> ```

To many new lines; two of them can be removed.
___
*[pkg/debugapi/postage.go, line 143 at r1](https://reviewable.io/reviews/ethersphere/bee/2321#-MeAHGAA2s-a86_ObIp8:-MeAHGAA2s-a86_ObIp9:beffdrx) ([raw file](https://github.com/ethersphere/bee/blob/95aea4306cc0b13a312e0254aca8223ae9417887/pkg/debugapi/postage.go#L143)):*
> ```Go
> 
> 	idStr := mux.Vars(r)["id"]
> 	if idStr == "" || len(idStr) != 64 {
> ```

The `len(idStr) != 64` will also cover the case `idStr == ""`.
___
*[pkg/postage/stampissuer.go, line 148 at r1](https://reviewable.io/reviews/ethersphere/bee/2321#-MeAJIfN3lFsyVRVxwJ5:-MeAJIfN3lFsyVRVxwJ6:bsijjsi) ([raw file](https://github.com/ethersphere/bee/blob/95aea4306cc0b13a312e0254aca8223ae9417887/pkg/postage/stampissuer.go#L148)):*
> ```Go
> }
> 
> // BucketDepth the depth of collision Buckets uniformity.
> ```

In the comment the function name should be renamed: `BucketDepth` -> `BucketUpperBound`.

**Review by zelig — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2321)* status: all files reviewed, 4 unresolved discussions (waiting on @acud)

___
*[pkg/debugapi/postage.go, line 114 at r2](https://reviewable.io/reviews/ethersphere/bee/2321#-MeDn90n2dErXYTnHqT-:-MeDn90n2dErXYTnHqT0:bevhq9y) ([raw file](https://github.com/ethersphere/bee/blob/9e0b5cb308fd900653eff5f20a1f51fe2f257890/pkg/debugapi/postage.go#L114)):*
> ```Go
> 	BucketDepth      uint8        `json:"bucketDepth"`
> 	BucketUpperBound uint32       `json:"bucketUpperBound"`
> 	Buckets          []bucketData `json:"buckets"`
> ```

why need for this bucketdata struct, why not just display zero buckets as well in the lifetime of a stamp, its a very short period when some buckets are empty, so we wont save anything.
___
*[pkg/debugapi/postage.go, line 159 at r2](https://reviewable.io/reviews/ethersphere/bee/2321#-MeDoBCW0pmGhzUgYCR_:-MeDoBCW0pmGhzUgYCRa:b5ro7n1) ([raw file](https://github.com/ethersphere/bee/blob/9e0b5cb308fd900653eff5f20a1f51fe2f257890/pkg/debugapi/postage.go#L159)):*
> ```Go
> 		s.logger.Error("get stamp issuer: get issuer: %v", err)
> 		s.logger.Error("get stamp issuer: get issuer")
> 		jsonhttp.BadRequest(w, "cannot get issuer")
> ```

maybe a less cryptic error would be nice. something like this batch appears not to be locally owned/used.
___
*[pkg/debugapi/postage.go, line 171 at r2](https://reviewable.io/reviews/ethersphere/bee/2321#-MeDox0N1u_NMFJ5h7aj:-MeDox0N1u_NMFJ5h7ak:bbwqgc1) ([raw file](https://github.com/ethersphere/bee/blob/9e0b5cb308fd900653eff5f20a1f51fe2f257890/pkg/debugapi/postage.go#L171)):*
> ```Go
> 	}
> 
> 	for i, v := range b {
> ```

well if you create entries for the empy buckets too anyway, i really dont see why not just use a simple integer array ie. the `buckets` field of the issuer data directly.
___
*[pkg/postage/stampissuer.go, line 165 at r2](https://reviewable.io/reviews/ethersphere/bee/2321#-MeDon293b7UZfB5uyxS:-MeDon293b7UZfB5uyxT:b-1n0kxh) ([raw file](https://github.com/ethersphere/bee/blob/9e0b5cb308fd900653eff5f20a1f51fe2f257890/pkg/postage/stampissuer.go#L165)):*
> ```Go
> }
> 
> func (si *StampIssuer) Buckets() []uint32 {
> ```

this could just be directly given in the responseJson

**Review by acud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2321)* status: all files reviewed, 4 unresolved discussions (waiting on @zelig)

___
*[pkg/debugapi/postage.go, line 114 at r2](https://reviewable.io/reviews/ethersphere/bee/2321#-MeDn90n2dErXYTnHqT-:-MeO_VxB-fWafjWShtz2:bl47hkz) ([raw file](https://github.com/ethersphere/bee/blob/9e0b5cb308fd900653eff5f20a1f51fe2f257890/pkg/debugapi/postage.go#L114)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

why need for this bucketdata struct, why not just display zero buckets as well in the lifetime of a stamp, its a very short period when some buckets are empty, so we wont save anything.
</blockquote></details>

the idea was to have human readable output. if it's an array then it means you must have some sort of consumer code that can parse and process the output. since we don't have such code, and we rely mainly on manual testing, I wrote it like this.
___
*[pkg/debugapi/postage.go, line 159 at r2](https://reviewable.io/reviews/ethersphere/bee/2321#-MeDoBCW0pmGhzUgYCR_:-MeOa76W5dwMLXBEnGeZ:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9e0b5cb308fd900653eff5f20a1f51fe2f257890/pkg/debugapi/postage.go#L159)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

maybe a less cryptic error would be nice. something like this batch appears not to be locally owned/used.
</blockquote></details>

Done.
___
*[pkg/debugapi/postage.go, line 171 at r2](https://reviewable.io/reviews/ethersphere/bee/2321#-MeDox0N1u_NMFJ5h7aj:-MeOaAm264pa3i7bUcR4:b-br30rr) ([raw file](https://github.com/ethersphere/bee/blob/9e0b5cb308fd900653eff5f20a1f51fe2f257890/pkg/debugapi/postage.go#L171)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

well if you create entries for the empy buckets too anyway, i really dont see why not just use a simple integer array ie. the `buckets` field of the issuer data directly.
</blockquote></details>

human readable output
___
*[pkg/postage/stampissuer.go, line 165 at r2](https://reviewable.io/reviews/ethersphere/bee/2321#-MeDon293b7UZfB5uyxS:-MeOaGESCPyDbe12CNGN:b-o6r1xp) ([raw file](https://github.com/ethersphere/bee/blob/9e0b5cb308fd900653eff5f20a1f51fe2f257890/pkg/postage/stampissuer.go#L165)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

this could just be directly given in the responseJson
</blockquote></details>

don't understand

**Review by zelig — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2321)* status: all files reviewed, 4 unresolved discussions (waiting on @acud and @zelig)

___
*[pkg/debugapi/postage.go, line 171 at r2](https://reviewable.io/reviews/ethersphere/bee/2321#-MeDox0N1u_NMFJ5h7aj:-MeTB4TX5Q2CCz-sEoD8:b4sal0y) ([raw file](https://github.com/ethersphere/bee/blob/9e0b5cb308fd900653eff5f20a1f51fe2f257890/pkg/debugapi/postage.go#L171)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

human readable output
</blockquote></details>

human readability is totally fine but its a UX thing. a json array of collisions within a bucket (neighbourhood) i
















































































































































































































































































































































































































































































































































































































































































































































































































-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|||||||||||||||||||||||||||||||||||||||||||||||||||||||


<!-- Sent from Reviewable.io -->

**Review by acud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2321)* status: all files reviewed, 4 unresolved discussions (waiting on @zelig)

___
*[pkg/debugapi/postage.go, line 171 at r2](https://reviewable.io/reviews/ethersphere/bee/2321#-MeDox0N1u_NMFJ5h7aj:-MeU4Xa65MHjtJrQRy8_:b-2e7xjj) ([raw file](https://github.com/ethersphere/bee/blob/9e0b5cb308fd900653eff5f20a1f51fe2f257890/pkg/debugapi/postage.go#L171)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

human readability is totally fine but its a UX thing. a json array of collisions within a bucket (neighbourhood) i
















































































































































































































































































































































































































































































































































































































































































































































































































-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|||||||||||||||||||||||||||||||||||||||||||||||||||||||
</blockquote></details>

this abstracts too many details. what if we want to also be able to plot collision histograms? we'd have to create a separate endpoint then


<!-- Sent from Reviewable.io -->

**Review by zelig — APPROVED** [review]

**Pull request merged**
