### PR TITLE
Granular notifiers in protocol spec

### PR DESCRIPTION
**Pull request by pradovic**
- Added connect/disconnect notifiers per: https://github.com/ethersphere/bee/issues/653
- Removed `topology.Notifier` to remove p2p and toplogy dependency
- Reduced to single notifier as there is only one notifier needed for now, this is easy to expand to array if needed 
- Some code in libp2p  uses closePeer() instead of disconnect, as this is part of connection process and there is no need to signal disconnect in this case as the peer for not yet even added to peer registry.

Todo: more unit tests

### CODE REVIEW

**Review by janos — COMMENTED** [review]
As already stated in the description, unit tests for new notifiers would be good. Otherwise it looks good.

**Review by acud — COMMENTED** [review]
Looks good @pradovic. I'm not sure why the signature change in the notifiers is needed to `p2p.Peer`, where `p2p.Peer` in fact stores only overlay address. `swarm.Address` usage maintains clarity that only overlay is conveyed, whereas `p2p.Peer` might infer that other information that should maybe not be leaked to higher level components, such as underlay or other p2p info.

**Comment by pradovic** [comment]
> Looks good @pradovic. I'm not sure why the signature change in the notifiers is needed to `p2p.Peer`, where `p2p.Peer` in fact stores only overlay address. `swarm.Address` usage maintains clarity that only overlay is conveyed, whereas `p2p.Peer` might infer that other information that should maybe not be leaked to higher level components, such as underlay or other p2p info.

I saw that @janos proposal uses Peer, so I wanted to make it uniform. No other reason, but I guess it could be useful if we expand Peer with more info. On the other hand, the major change in `Notifier` interfaces was just reducing it to one + decouple it from topology.

**Comment by pradovic** [comment]
@janos I talked with @metacertain and he wanted to work on unit tests to get more familiar with this. So, I will wait for him to implement the tests and hlep him in the process, and we will add them as well.

**Comment by pradovic** [comment]
@janos Tests are done. I used a bit different approach than what was proposed in the task, just because of the simplicity and I think this is good enouth. LMNWYT :)

**Review by janos — APPROVED** [review]

**Comment by janos** [comment]
@pradovic yes, this is just enough for testing the functionality. 👍 Thanks.

**Review by ralph-pichler — APPROVED** [review]
LGTM

**Pull request merged**
