### PR TITLE
10 times gas price

### PR DESCRIPTION
**Pull request by Raven2105**
When I run bee start, it appears：

Error: init chain: dial eth client: websocket: bad handshake (HTTP status 401 Unauthorized)

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1874)

### CODE REVIEW

**Comment by ldeffenb** [comment]
Um, why?  And what does the startup error have to do with making every transaction cost 10 times as much as the chain estimates that it should?  Or worse, 10 times as much as the user specified they wanted to use?

**Comment by moremorefun** [comment]
We can add a configuration item, which is a file path, where the current gasPrice is stored. This should be more convenient than setting a fixed value.
Based on this processing, we can implement a separate script to automatically get more real-time gasPrice recommendations from etherscan.io or ethgasstation.info

**Review by Eknir — COMMENTED** [review]
This is not a change we can accept. You can pass in the gas-price as a header parameter in your request (https://docs.ethswarm.org/debug-api/#tag/Chequebook/paths/~1chequebook~1cashout~1{peer-id}/post)

**Comment by acud** [comment]
Closing this as gas price can already be adjusted

**Pull request closed without merging**
