### PR TITLE
feat(pusher): receipt depth metric

### PR DESCRIPTION
**Pull request by acud**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1977)

### CODE REVIEW

**Review by mrekucci — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1977#-:-MbGwZSg0N95WCywTbOG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @acud)

___
*[pkg/pusher/metrics.go, line 20 at r1](https://reviewable.io/reviews/ethersphere/bee/1977#-MbGvyXDEvTbGIdsYzQs:-MbGvyXE4EDNlzMRQQeD:b8qv8d8) ([raw file](https://github.com/ethersphere/bee/blob/abd51c6102eb70354bab1d466a5ded3574780bee/pkg/pusher/metrics.go#L20)):*
> ```Go
> 	ErrorTime        prometheus.Histogram
> 
> 	ReceiptDepth *prometheus.CounterVec
> ```

We don't use the other counters as pointers, is there a reason why this is a pointer?

**Review by acud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1977)* status: all files reviewed, 1 unresolved discussion (waiting on @mrekucci)

___
*[pkg/pusher/metrics.go, line 20 at r1](https://reviewable.io/reviews/ethersphere/bee/1977#-MbGvyXDEvTbGIdsYzQs:-MbHGumg87jnE_KA0lN0:bk31v4l) ([raw file](https://github.com/ethersphere/bee/blob/abd51c6102eb70354bab1d466a5ded3574780bee/pkg/pusher/metrics.go#L20)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

We don't use the other counters as pointers, is there a reason why this is a pointer?
</blockquote></details>

the `CounterVec` constructor returns a pointer, the other constructors return an instance

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1977)* status: all files reviewed, 1 unresolved discussion (waiting on @acud)

___
*[pkg/pusher/metrics.go, line 20 at r1](https://reviewable.io/reviews/ethersphere/bee/1977#-MbGvyXDEvTbGIdsYzQs:-MbHYyfa3Iy0RE1KhzJg:b-6xayos) ([raw file](https://github.com/ethersphere/bee/blob/abd51c6102eb70354bab1d466a5ded3574780bee/pkg/pusher/metrics.go#L20)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

the `CounterVec` constructor returns a pointer, the other constructors return an instance
</blockquote></details>

Maybe you can dereference it in the constructor as here: https://github.com/ethersphere/bee/blob/master/pkg/retrieval/metrics.go#L56

**Review by acud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1977)* status: all files reviewed, 1 unresolved discussion (waiting on @mrekucci)

___
*[pkg/pusher/metrics.go, line 20 at r1](https://reviewable.io/reviews/ethersphere/bee/1977#-MbGvyXDEvTbGIdsYzQs:-MbIBt9S3PD9p80KY8TX:b-aid5zn) ([raw file](https://github.com/ethersphere/bee/blob/abd51c6102eb70354bab1d466a5ded3574780bee/pkg/pusher/metrics.go#L20)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

Maybe you can dereference it in the constructor as here: https://github.com/ethersphere/bee/blob/master/pkg/retrieval/metrics.go#L56
</blockquote></details>

I am not sure why it was done there too :man_shrugging: Can you what are the benefits of dereferencing here? AFAIK if the underlying type has methods with a pointer receiver then dereferencing might mess that up.

**Review by aloknerurkar — APPROVED** [review]

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1977)* status: all files reviewed, 1 unresolved discussion (waiting on @acud)

___
*[pkg/pusher/metrics.go, line 20 at r1](https://reviewable.io/reviews/ethersphere/bee/1977#-MbGvyXDEvTbGIdsYzQs:-MbKwWdQDva-oLXvvWRn:b-rg1eeh) ([raw file](https://github.com/ethersphere/bee/blob/abd51c6102eb70354bab1d466a5ded3574780bee/pkg/pusher/metrics.go#L20)):*
The `CounterVec` type is just a wrapper of pointer to `*metricVec`. IMHO the `CounterVec` is a pointer because the package has some builder methods attached to it, e.g.: `CurryWith`.

> AFAIK if the underlying type has methods with a pointer receiver then dereferencing might mess that up.

According to the [spec](https://golang.org/ref/spec#Calls):

> If x is addressable and &x's method set contains m, x.m() is shorthand for (&x).m().

Specifying it as a pointer in the metrics struct may also indicate that we're (we intend to) changing its value, which is not happening. But in the end, it's not a big deal, this is just a suggestion :)

**Pull request merged**
