### PR TITLE
P1 - Include swarm shed package as it is

### PR DESCRIPTION
**Pull request by jmozah**
PR 1 of https://github.com/ethersphere/bee/issues/66

### CODE REVIEW

**Comment by jmozah** [comment]
@janos I fixed them. But the build is stalling again and again. I tried to do a "make lint"  does not show these lint errors in my local machine.. am i missing something?

**Comment by acud** [comment]
@jmozah please resolve merge conflicts

**Comment by janos** [comment]
The linter issue in CI is that it times out. I will create a new PR that will set a longer time for its timeout.

**Comment by janos** [comment]
@jmozah Could you review https://github.com/ethersphere/bee/pull/76 so that we can unblock this PR?

**Comment by janos** [comment]
Thanks @acud for merging #76. @jmozah Could you merge master to validate that this PR passes linting and tests?

**Pull request merged**
