### PR TITLE
api: integrate encryption pipeline

### PR DESCRIPTION
**Pull request by acud**
integrates the new encryption pipeline into the api and other dependencies

### CODE REVIEW

**Comment by janos** [comment]
There are some lint errors.

**Comment by acud** [comment]
> There are some lint errors.

yep sorry. fixed

**Review by janos — APPROVED** [review]

**Review by zelig — APPROVED** [review]
LGTM

**Comment by zelig** [comment]
we should prohibit encryption on non-private gateways.
the  old swarm does this, and so should bee imho

**Pull request merged**
