### PR TITLE
Simplify chunk pusher worker loop

### PR DESCRIPTION
**Pull request by zbiljic**
Remove main timer case for chunk pusher worker.
If the `chunk` channel is closed, just wait for retry interval and re-subscribe. The channel will usually be only closed on some internal error.

P.S.
Basically change from [branch/pusher-new](https://github.com/ethersphere/bee/compare/pusher-new).

related to #532

### CODE REVIEW

**Comment by acud** [comment]
@zbiljic is this ready for review?

**Comment by zbiljic** [comment]
@acud I was waiting for Beekeeper changes, as my changes for this cause intermittent failures in Beekeeper. This change introduces bigger delay in some cases.
If you've completed changes you were doing for Beekeeper, and it still fails, I will go and add modifications that account for this.

**Comment by acud** [comment]
Which tests were flaking on beekeeper? I am only working on the local pinning tests in beekeeper, not anything that relies on syncing

**Comment by zbiljic** [comment]
> Which tests were flaking on beekeeper? I am only working on the local pinning tests in beekeeper, not anything that relies on syncing

Different ones at random with this change (I remember manifest, and some pinning, probably global). And sometimes it all passes.
My mistake, as I understood from various mentions here and there, you were making some bigger overall changes to Beekeeper. I will then see to change these other on Beekeeper.

**Comment by Eknir** [comment]
Hi @zbiljic , what is the status of this PR, are you currently working on it, planning to continue?
Also, could you attach it to an issue? Thanks!

**Comment by zbiljic** [comment]
@Eknir It relates to the issue mentioned in the description.
The plan was to add this change, however, as mentioned, some Beekeeper tests are failed, due to some timeouts.

As far as the PR goes, if required it can be closed, and opened again at another time.

**Comment by Eknir** [comment]
Thanks @zbiljic! :)

**Pull request closed without merging**
