### PR TITLE
feat: elevate reserve limits

### PR DESCRIPTION
**Pull request by metacertain**
#### Motivation and context (Optional)
in order to counteract queue throttling effects of requests served with delays, increase reserve and disconnect limits from 
payment threshold,
(1 + tolerance%) * payment threshold

to

payment threshold + ("seconds since last refreshment sent" * "refreshment rate" )
(1 + tolerance%) * payment threshold + ("seconds since last refreshment received" * "refreshment rate")  

with "seconds since last refreshment" term capped at 2.

this intends to circumvent a situation where reserve is jammed by timing out requests, and no debt is formed, so no more requests could be queried regardless of refresh rate.

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2761)

### CODE REVIEW

**Review by mrekucci — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2761)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @metacertain)

___
*[pkg/accounting/accounting.go, line 106 at r1](https://reviewable.io/reviews/ethersphere/bee/2761#-Mx0gYjr0Fs5xWbHEaPQ:-Mx0gYjvCKexCtBfHCfs:b-alpm63) ([raw file](https://github.com/ethersphere/bee/blob/30b05d0236fd49425ec87c51923c14c929c2d6b5/pkg/accounting/accounting.go#L106)):*
> ```Go
> 	disconnectLimit                *big.Int   // individual disconnect threshold calculated from tolerance and payment threshold for peer
> 	refreshTimestamp               int64      // last time we attempted time-based settlement
> 	refreshReceivedTimestamp       int64      // last time we attempted time-based settlement
> ```

The description is the same as the description above.
___
*[pkg/accounting/accounting.go, line 270 at r1](https://reviewable.io/reviews/ethersphere/bee/2761#-Mx0h9Dm24AZwz3BC9w-:-Mx0h9Dm24AZwz3BC9w0:b-7w9h5u) ([raw file](https://github.com/ethersphere/bee/blob/30b05d0236fd49425ec87c51923c14c929c2d6b5/pkg/accounting/accounting.go#L270)):*
> ```Go
> 	}
> 
> 	timeElapsed := a.timeNow().Unix() - accountingPeer.refreshTimestamp
> ```

Consider using `time.Now()` for the `accountingPeer.refreshTimestamp` and then `time.Since(accountingPeer.refreshTimestamp)`.
___
*[pkg/accounting/accounting.go, line 336 at r1](https://reviewable.io/reviews/ethersphere/bee/2761#-Mx0htLo9AzrEN-O8mo3:-Mx0htLo9AzrEN-O8mo4:bkrwseo) ([raw file](https://github.com/ethersphere/bee/blob/30b05d0236fd49425ec87c51923c14c929c2d6b5/pkg/accounting/accounting.go#L336)):*
> ```Go
> 			err = c.accounting.settle(c.peer, c.accountingPeer)
> 			if err != nil {
> 				c.accounting.logger.Errorf("failed to settle with credited peer %v: %w", c.peer, err)
> ```

Don't use `%w` verb in the logger, it's only a valid verb in `fmt.Errorf` function.
___
*[pkg/accounting/accounting.go, line 379 at r1](https://reviewable.io/reviews/ethersphere/bee/2761#-Mx0iC9Z5Ci6aaQmmRze:-Mx0iC9Z5Ci6aaQmmRzf:bul0oml) ([raw file](https://github.com/ethersphere/bee/blob/30b05d0236fd49425ec87c51923c14c929c2d6b5/pkg/accounting/accounting.go#L379)):*
> ```Go
> 		err = c.accounting.settle(c.peer, c.accountingPeer)
> 		if err != nil {
> 			c.accounting.logger.Errorf("failed to settle with credited peer %v: %w", c.peer, err)
> ```

The same as above`%w` -> `%v`.

**Comment by metacertain** [comment]
> _[pkg/accounting/accounting.go, line 270 at r1](https://reviewable.io/reviews/ethersphere/bee/2761#-Mx0h9Dm24AZwz3BC9w-:-Mx0h9Dm24AZwz3BC9w0:b-7w9h5u) ([raw file](https://github.com/ethersphere/bee/blob/30b05d0236fd49425ec87c51923c14c929c2d6b5/pkg/accounting/accounting.go#L270)):_
> 
> > ```go
> > 	}
> > 
> > 	timeElapsed := a.timeNow().Unix() - accountingPeer.refreshTimestamp
> > ```
> 
> Consider using `time.Now()` for the `accountingPeer.refreshTimestamp` and then `time.Since(accountingPeer.refreshTimestamp)`.
> 

Applied the other comments.
This one is relevant as well, however because we use timestamps consistently in Unix(), it's probably better to keep it for now, as it will be a subject to a more refresh timestamp focused fix/update soon

**Review by mrekucci — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2761)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @notanatol, and @ralph-pichler)

**Comment by metacertain** [comment]
As part of #2904

**Pull request closed without merging**
