### PR TITLE
Added test cases for `NewOverlayFromEthereumAddress` 

### PR DESCRIPTION
**Pull request by Aviksaikat**
added 4 test cases under `TestNewOverlayFromEthereumAddress`  to test `NewOverlayFromEthereumAddress` of crypto library

### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [x] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Screenshots (if appropriate):
image

### CODE REVIEW

**Review by mrekucci — CHANGES_REQUESTED** [review]
Thank you for the nice PR. Would be great if you could rewrite it into table-test and also use standard Golang messages ("want: ...; got/have: ...").

**Comment by Aviksaikat** [comment]
Hi, sorry about that I don't have much knowledge of go testing standards. Can you share something to follow ?

**Comment by Aviksaikat** [comment]
Is it something like this?
```go
func TestNewOverlayFromEthereumAddress(t *testing.T) {
   t.Parallel()

   // Define the test cases
   testCases := []struct {
       ethAddress  string
       overlayNumber int
       hash         []byte
       expected     string
   }{
       {
           ethAddress:  "1815cac638d1525b47f848daf02b7953e4edd15c",
           overlayNumber: 1,
           hash:         common.HexToHash("0x1").Bytes(),
           expected:     "a38f7a814d4b249ae9d3821e9b898019c78ac9abe248fff171782c32a3849a17",
       },
       {
           ethAddress:  "1815cac638d1525b47f848daf02b7953e4edd15c",
           overlayNumber: 1,
           hash:         common.HexToHash("0x2").Bytes(),
           expected:     "c63c10b1728dfc463c64c264f71a621fe640196979375840be42dc496b702610",
       },
       {
           ethAddress:  "d26bc1715e933bd5f8fad16310042f13abc16159",
           overlayNumber: 2,
           hash:         common.HexToHash("0x1").Bytes(),
           expected:     "9f421f9149b8e31e238cfbdc6e5e833bacf1e42f77f60874d49291292858968e",
       },
       {
           ethAddress:  "ac485e3c63dcf9b4cda9f007628bb0b6fed1c063",
           overlayNumber: 1,
           hash:         common.HexToHash("0x0").Bytes(),
           expected:     "fe3a6d582c577404fb19df64a44e00d3a3b71230a8464c0dd34af3f0791b45f2",
       },
   }

   // Run the test cases
   for _, tc := range testCases {
       ethAddressBytes, err := hex.DecodeString(tc.ethAddress)
       if err != nil {
           t.Fatal(err)
       }

       newAddress, err := crypto.NewOverlayFromEthereumAddress(ethAddressBytes, tc.overlayNumber, tc.hash)
       if err != nil {
           t.Fatal(err)
       }

       if l := len(newAddress.Bytes()); l != 32 {
           t.Errorf("got address length %v, want %v", l, 32)
       }

       if newAddress.String() != tc.expected {
           t.Errorf("want: %s; got: %s", tc.expected, newAddress.String())
       }
   }
}
```

**Comment by notanatol** [comment]
can you also fix the commit message to something like `chore: add test for...`

**Comment by Aviksaikat** [comment]
Done

**Pull request closed without merging**
