### PR TITLE
feat: expose chain state through the debug API endpoint

### PR DESCRIPTION
**Pull request by mrekucci**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1756)

### CODE REVIEW

**Comment by mrekucci** [comment]
@agazso

**Review by anatollupacescu — APPROVED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1756)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @Eknir, and @esadakar)

**Comment by Eknir** [comment]
I think it would be best to return `/stamps/price/total` `/stamps/price/current` and `/stamps/price/block`.

**Comment by Eknir** [comment]
> > I think it would be best to return `/stamps/price/total` `/stamps/price/current` and `/stamps/price/block`.
> 
> That would require having 3 separate endpoints, one for each value. What is the use case for having it like that?
> If there is a use case for querying the chain state price data without postage batches, then I'd recommend having it under `/stamps/price` endpoint. @acud ?

I believe there is a usecase for querying chain state price date without postage batches (e.g. when I create a new batch and I want to figure out the current price to estimate what value to put). 
In my previous comment, I meant that `"price":{"block":4813080,"total":12,"current":1}}` is better than `"price":{"block":4813080,"totalAmount":12,"currentPrice":1}}`, as the latter has some duplication and is longer.

**Review by zelig — APPROVED** [review]
> Reviewed 12 of 12 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1756)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @Eknir, and @esadakar)

**Review by zelig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1756)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @acud, @Eknir, and @esadakar)

**Comment by acud** [comment]
I support @mrekucci here and I think that having it under one endpoint is better for various reasons and it would allow more information to be displayed to the user with less calls to the API. It would also be more informative for us for debugging purposes.

**Review by esadakar — APPROVED** [review]

**Review by acud — APPROVED** [review]
:lgtm:

> Reviewed 5 of 12 files at r1, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1756#-:-Ma37xjn7iMbYgM9mcJ_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eknir and @esadakar)

**Pull request merged**
