### PR TITLE
initial deb and rpm support

### PR DESCRIPTION
**Pull request by vandot**
@janos @acud couple of questions:
- should we enable service during installation (to start when machine is rebooted)?
- should we change the default API port from 8080 (its default for a lot of services)?

### CODE REVIEW

**Comment by janos** [comment]
@vandot I think that the service should start automatically and we have to set three (or at least two, if debug api is not enabled) ports that are not conflicting with anything else.

**Comment by vandot** [comment]
@janos that is true, but other two are not using that much popular port, good idea we can define/agree on port triplet, we can use something symbolic for swarm

**Comment by Eknir** [comment]
Hi @vandot , does there exist an issue for this PR?

If so, could you please attach this PR to that issue?

If not, could you open the issue and then attach it?

Thanks!

Use this button:

**Comment by vandot** [comment]
Packages will be created when we release new version, until then it is possible to test build locally.
Install latest `goreleaser` (submitted couple of PRs to support our build) and run `goreleaser release --skip-publish --rm-dist`

**Comment by vandot** [comment]
@janos @acud I rebased to master, in cli `git diff master` looks nice, not sure why here is listing all the files

**Comment by janos** [comment]
> @janos @acud I rebased to master, in cli `git diff master` looks nice, not sure why here is listing all the files
> this are changed/new files
> 
> ```
> .goreleaser.yml
> packaging/bee.service
> packaging/bee.yaml
> packaging/deb/postinst
> packaging/deb/postrm
> packaging/deb/preinst
> packaging/deb/prerm
> packaging/deb/templates
> packaging/default
> packaging/rpm/post
> packaging/rpm/pre
> packaging/rpm/preun
> ```

The rebase is not correct, it includes already applied commits. Please, rebase again or re-add new files/changes on the clean branch (maybe with the same name) if rebase is difficult.

**Comment by vandot** [comment]
@janos created new branch and new pr :man_shrugging: 
https://github.com/ethersphere/bee/pull/962

**Pull request closed without merging**
