### PR TITLE
suggest only downstream peers in retrieval forwarding

### PR DESCRIPTION
**Pull request by janos**
This PR changes how retrieval is suggesting peers. Currently it suggests up to 5 peers that are closes to the chunk that a node is connected to. It may happen that a peer in a list is an upstream peer and that retrieval forwards the request upstream. This can create a retrieval forwarding loop that is actually happening currently on the main cluster in a certain neighbourhood. Some chunks are constantly being requested between a few peers:

```
a568c505481bc9778bb45b67af0dd14ef023cffcc544fa181008ca7283b1029d
a6d31f12db9b09d9ab805b5b4ded8a5cfcb2f91d50671ff407b32c43ea9f0486
a376eeaf1c715a3df63ffcb0636bf83aadff77644a6404eca554d837965ed6df
a597fbe1f555dc5ff7c41c38227bbd099be0447c57cf3f055beee9242effd13f
a274a0608a0fc834847361431665cdeb327dd3ca7d7f8c350a9ab0ff695de995
b47a24f1020b1c080524380e08149386c76f1386c086eedd56bf2718cb9eb3b8
ab1bde4b8befa8d744e9285d98ded8ba217abb04af5ae175ba21de64f7ed2c29
```

and any other peer in that neighbourhood.

This PR restricts forwarding to only downstream peers.

Integration testing is done on this PR using CI https://github.com/ethersphere/bee/runs/1135530034.

fixes: #699

### CODE REVIEW

**Comment by ldeffenb** [comment]
One of my peers adbed98773abcd61450424f75fb6b591edb993100fe11fa9aab46604ac5c7f79 is currently connected to ab1bde4b8befa8d744e9285d98ded8ba217abb04af5ae175ba21de64f7ed2c29.  Is there a log level I can enable or something else that can show if I'm involved in a loop?  And is there a way to stop said loop in a neighborhood?

**Comment by janos** [comment]
@ldeffenb current detection of the loop are very frequent chunk retrieval failure log messages in trace log verbosity. This PR is addressing the correctness of the retrieval forwarding, but there will be more changes to make node more resilient to frequent retrieval requests, for any reason, to make the node more resilient. This type of rate limiter will be the part of hardening changes, which will be done in the future.

**Comment by ldeffenb** [comment]
> @ldeffenb  log messages in trace log verbosity

@janos What level of verbosity shows these failures?  I usually run level 3, but I don't recall seeing retrieval failures.

**Comment by ldeffenb** [comment]
I can confirm that my peer adbed98773abcd61450424f75fb6b591edb993100fe11fa9aab46604ac5c7f79 is involved in this neighborhood storm.  I assume there's nothing I can do to stop the looping at v0.2.0?

**Comment by janos** [comment]
Thanks for reporting @ldeffenb. Unfortunately, no, v0.2.0 is affected and we will be soon releasing a new beta version with this fix.

**Comment by ldeffenb** [comment]
@janos Is there a swarm running 0.3.0 (master) that I can join instead until the new beta is released?

**Comment by janos** [comment]
@ldeffenb we have one change on master that is breaking compatibility with the current release. We will have a new release in a week.

**Comment by ldeffenb** [comment]
@janos I know about the breaking change, just anxious to get my client back up without participating in the flooded neighborhood.  Counting down the days to beta!

**Review by zelig — APPROVED** [review]

**Review by acud — APPROVED** [review]
looks good @janos, thanks

**Pull request merged**
