### PR TITLE
chore: bump go ethereum version to 1.14.3 (#4661)

### PR DESCRIPTION
**Pull request by martinconic**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description
Bumps [github.com/ethereum/go-ethereum](https://github.com/ethereum/go-ethereum) from 1.13.4 to 1.13.15.

### CODE REVIEW

**Review by istae — APPROVED** [review]

**Review by janos — COMMENTED** [review]
Did you consider go-ethereum v1.14.3 for upgrade?

**Comment by martinconic** [comment]
> Did you consider go-ethereum v1.14.3 for upgrade?

Did not, should we?

**Comment by janos** [comment]
> > Did you consider go-ethereum v1.14.3 for upgrade?
> 
> Did not, should we?

Since the upgrade is happening, it may be good to have the latest minor release, if there are no breaking changes. With version v1.14.3 bee builds and unit tests are passing, but the behaviour should be validated in integration.

**Comment by martinconic** [comment]
> > > Did you consider go-ethereum v1.14.3 for upgrade?
> > 
> > 
> > Did not, should we?
> 
> Since the upgrade is happening, it may be good to have the latest minor release, if there are no breaking changes. With version v1.14.3 bee builds and unit tests are passing, but the behaviour should be validated in integration.

Nice, updated to v1.14.3

**Review by janos — APPROVED** [review]

**Review by acha-bill — APPROVED** [review]

**Pull request merged**
