### PR TITLE
refactor: kademlia quicker bin saturation

### PR DESCRIPTION
**Pull request by esadakar**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/1878)

### CODE REVIEW

**Review by ldeffenb — COMMENTED** [review]
This is making assumptions on both the behavior of the saturation function and the behavior of the depth calculations.

If the saturation function is changed in the future to make a more intelligent determination (for instance, to have more distant connections than closer connections), the NeighborhoodDepth check will cause it never to be invoked for lower bins.

And if the neighborhood depth calculation is ever changed to not require absolute saturation in lower bins, then those bins would still not fill because the depth will prevent them from being checked.

I like the idea behind this because it avoids individually considering all of the knownPeers within a saturated bin, which is really good for those of us with 200,000 knownPeers, over 1/2 of which are in bin0, but I'm concerned about the future impact of this assumed knowledge of the interaction between depth and bin saturation.

**Review by zelig — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1878)* status: all files reviewed, 1 unresolved discussion (waiting on @acud, @aloknerurkar, @anatollupacescu, @esadakar, @metacertain, and @mrekucci)

___
*[pkg/topology/kademlia/kademlia.go, line 42 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MaeCAUl9ERVqtlYTDBu:-MaeCAUl9ERVqtlYTDBv:bjytuah) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia.go#L42)):*
> ```Go
> 
> var (
> 	quickSaturation             = 4
> ```

`quickSaturationPeers` no?

**Review by mrekucci — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1878)* status: all files reviewed, 3 unresolved discussions (waiting on @acud, @aloknerurkar, @anatollupacescu, @esadakar, and @metacertain)

___
*[pkg/topology/kademlia/kademlia_test.go, line 272 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MaeRwwICO1l24D9piak:-MaeRwwICO1l24D9pial:bg6vucj) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia_test.go#L272)):*
> ```Go
> 		conns      int32 // how many connect calls were made to the p2p mock
> 		saturation = *kademlia.QuickSaturation
> 		// saturationVal     = false
> ```

I'd remove the unused code.
___
*[pkg/topology/kademlia/kademlia_test.go, line 294 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MaeQKNME-SkjwRpkANw:-MaeQKNN2RrUU1X4Djwf:bsdd6uu) ([raw file](https://github.com/ethersphere/bee/blob/17e187f07416bed287d107e59a50f6400f3fb485/pkg/topology/kademlia/kademlia_test.go#L294)):*
> ```Go
> 	saturationVal = true
> 
> 	// now since the bin is "saturated", no new connections should be made
> ```

Don't we want to also test if the bin is already saturated if new connections can be made (simular to previous one)?

**Review by acud — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1878)* status: all files reviewed, 6 unresolved discussions (waiting on @aloknerurkar, @anatollupacescu, @esadakar, @metacertain, @mrekucci, and @zelig)

___
*[pkg/topology/kademlia/kademlia.go, line 42 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MaeCAUl9ERVqtlYTDBu:-MagYULc6d6H8-EOXthP:b-8fx2u7) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia.go#L42)):*
<details><summary><i>Previously, zelig (Viktor Trón) wrote…</i></summary><blockquote>

`quickSaturationPeers` no?
</blockquote></details>

:+1: 
___
*[pkg/topology/kademlia/kademlia.go, line 298 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MagYf4uBgbvb0syn4jG:-MagYf4uBgbvb0syn4jH:bp122v1) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia.go#L298)):*
> ```Go
> 	_ = k.knownPeers.EachBinRev(func(addr swarm.Address, po uint8) (bool, bool, error) {
> 
> 		if po < k.NeighborhoodDepth() {
> ```

`NeighborhoodDepth()` acquires a mutex. Since we don't really care about depth changing while iterating on `connectNeighbors`, it might be better to just call it once before the iterator and check against that value while iterating
___
*[pkg/topology/kademlia/kademlia_test.go, line 272 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MaeRwwICO1l24D9piak:-MagZ0lbE_T0tSK_GOnJ:b32v57) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia_test.go#L272)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

I'd remove the unused code.
</blockquote></details>

+1
___
*[pkg/topology/kademlia/kademlia_test.go, line 285 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MagZ3iG5Nzyc2VOhmCU:-MagZ3iH35u6lDRmL6S5:bb7r2f0) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia_test.go#L285)):*
> ```Go
> 	defer kad.Close()
> 
> 	kad.SetRadius(6)
> ```

why?
___
*[pkg/topology/kademlia/kademlia_test.go, line 294 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MaeQKNME-SkjwRpkANw:-MagZCuN1xG07Bsn27R_:b32v57) ([raw file](https://github.com/ethersphere/bee/blob/17e187f07416bed287d107e59a50f6400f3fb485/pkg/topology/kademlia/kademlia_test.go#L294)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

Don't we want to also test if the bin is already saturated if new connections can be made (simular to previous one)?
</blockquote></details>

+1
___
*[pkg/topology/kademlia/kademlia_test.go, line 399 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MagZHQjEn_LZUrNVbx1:-MagZHQjEn_LZUrNVbx2:bb7r2f0) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia_test.go#L399)):*
> ```Go
> 	defer kad.Close()
> 
> 	kad.SetRadius(6)
> ```

why?

**Review by esadakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1878)* status: all files reviewed, 6 unresolved discussions (waiting on @acud, @aloknerurkar, @anatollupacescu, @metacertain, @mrekucci, and @zelig)

___
*[pkg/topology/kademlia/kademlia.go, line 42 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MaeCAUl9ERVqtlYTDBu:-MagcOV--e_B6JwMcSjV:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia.go#L42)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[pkg/topology/kademlia/kademlia.go, line 298 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MagYf4uBgbvb0syn4jG:-MagcPAT-gQlWSJN62Wf:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia.go#L298)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

`NeighborhoodDepth()` acquires a mutex. Since we don't really care about depth changing while iterating on `connectNeighbors`, it might be better to just call it once before the iterator and check against that value while iterating
</blockquote></details>

Done.
___
*[pkg/topology/kademlia/kademlia_test.go, line 272 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MaeRwwICO1l24D9piak:-MagcPrJ9IOIU4DUvsFM:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia_test.go#L272)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[pkg/topology/kademlia/kademlia_test.go, line 285 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MagZ3iG5Nzyc2VOhmCU:-MagbmF4DfDi3fxXrTyf:bjcdt3z) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia_test.go#L285)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

why?
</blockquote></details>

in recalcDepth we have a radius check that's interfering with the test
___
*[pkg/topology/kademlia/kademlia_test.go, line 294 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MaeQKNME-SkjwRpkANw:-Magd1FN2jGybbW_UjL5:b-bz4fvw) ([raw file](https://github.com/ethersphere/bee/blob/17e187f07416bed287d107e59a50f6400f3fb485/pkg/topology/kademlia/kademlia_test.go#L294)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Do you mean the check where no new connections should be made to bin 0 ? 
___
*[pkg/topology/kademlia/kademlia_test.go, line 399 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MagZHQjEn_LZUrNVbx1:-MagbeoWEWBiqGT9cnmW:bjcdt3z) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia_test.go#L399)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

why?
</blockquote></details>

in recalcDepth we have a radius check that's interfering with the test

**Review by mrekucci — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1878)* status: all files reviewed, 6 unresolved discussions (waiting on @acud, @aloknerurkar, @anatollupacescu, @esadakar, @metacertain, @mrekucci, and @zelig)

___
*[pkg/topology/kademlia/kademlia_test.go, line 294 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MaeQKNME-SkjwRpkANw:-Magez1P8KHYRaFjEWEq:bb77ufg) ([raw file](https://github.com/ethersphere/bee/blob/17e187f07416bed287d107e59a50f6400f3fb485/pkg/topology/kademlia/kademlia_test.go#L294)):*
<details><summary><i>Previously, esadakar (Esad Akar) wrote…</i></summary><blockquote>

Do you mean the check where no new connections should be made to bin 0 ? 
</blockquote></details>

Yes.

**Review by acud — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1878)* status: all files reviewed, 5 unresolved discussions (waiting on @acud, @aloknerurkar, @anatollupacescu, @esadakar, @metacertain, and @zelig)

___
*[pkg/topology/kademlia/kademlia.go, line 297 at r2](https://reviewable.io/reviews/ethersphere/bee/1878#-Mags4nb94Q7Jhw_Bmci:-Mags4ncCAaLXKSGrg_F:b-j5y6hb) ([raw file](https://github.com/ethersphere/bee/blob/9117d7fe5e048b5ac75b0ae91899ead724d137b0/pkg/topology/kademlia/kademlia.go#L297)):*
> ```Go
> 	// so we ignore the error returned from EachBinRev.
> 
> 	deth := k.NeighborhoodDepth()
> ```

depth :)
___
*[pkg/topology/kademlia/kademlia_test.go, line 285 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MagZ3iG5Nzyc2VOhmCU:-MagsGl66wxvBuz40MO1:b-jcxj0s) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia_test.go#L285)):*
<details><summary><i>Previously, esadakar (Esad Akar) wrote…</i></summary><blockquote>

in recalcDepth we have a radius check that's interfering with the test
</blockquote></details>

but how is it that it was not needed before? same for the other addition

**Review by esadakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1878)* status: all files reviewed, 5 unresolved discussions (waiting on @acud, @aloknerurkar, @anatollupacescu, @metacertain, @mrekucci, and @zelig)

___
*[pkg/topology/kademlia/kademlia.go, line 297 at r2](https://reviewable.io/reviews/ethersphere/bee/1878#-Mags4nb94Q7Jhw_Bmci:-MagyfIEBXUR-do6piJ3:b-sc6rql) ([raw file](https://github.com/ethersphere/bee/blob/9117d7fe5e048b5ac75b0ae91899ead724d137b0/pkg/topology/kademlia/kademlia.go#L297)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

depth :)
</blockquote></details>

adhd doesn't help :(
___
*[pkg/topology/kademlia/kademlia_test.go, line 285 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MagZ3iG5Nzyc2VOhmCU:-MagyjBgBV9EOZRWoaDm:b-hnp86h) ([raw file](https://github.com/ethersphere/bee/blob/d212366622a408751955932e1554b1bfb2b5a98d/pkg/topology/kademlia/kademlia_test.go#L285)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

but how is it that it was not needed before? same for the other addition
</blockquote></details>

because a custom saturationFunc was used before in the test so the radius was not taken into account
___
*[pkg/topology/kademlia/kademlia_test.go, line 294 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MaeQKNME-SkjwRpkANw:-MagqOcP1YX1RFOGXx38:b-14h8av) ([raw file](https://github.com/ethersphere/bee/blob/17e187f07416bed287d107e59a50f6400f3fb485/pkg/topology/kademlia/kademlia_test.go#L294)):*
> ```
> // here, we attempt to add to bin 0, but bin is saturated, so no peers are connected to
> ```
I thought I did that here?

**Review by esadakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1878)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @acud, @aloknerurkar, @anatollupacescu, @metacertain, @mrekucci, and @zelig)

___
*[pkg/topology/kademlia/kademlia.go, line 297 at r2](https://reviewable.io/reviews/ethersphere/bee/1878#-Mags4nb94Q7Jhw_Bmci:-MagzSQiD4UzwOPJYTYd:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/9117d7fe5e048b5ac75b0ae91899ead724d137b0/pkg/topology/kademlia/kademlia.go#L297)):*
<details><summary><i>Previously, esadakar (Esad Akar) wrote…</i></summary><blockquote>

adhd doesn't help :(
</blockquote></details>

Done.

**Review by mrekucci — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/1878#-:-Mah1ImZ9Ti9VXXssQNt:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @acud, @aloknerurkar, @anatollupacescu, @metacertain, and @zelig)

___
*[pkg/topology/kademlia/kademlia_test.go, line 294 at r1](https://reviewable.io/reviews/ethersphere/bee/1878#-MaeQKNME-SkjwRpkANw:-Mah0jTg-lxoxh0Ql8r-:bsi8v38) ([raw file](https://github.com/ethersphere/bee/blob/17e187f07416bed287d107e59a50f6400f3fb485/pkg/topology/kademlia/kademlia_test.go#L294)):*
<details><summary><i>Previously, esadakar (Esad Akar) wrote…</i></summary><blockquote>

> ```
> // here, we attempt to add to bin 0, but bin is saturated, so no peers are connected to
> ```
I thought I did that here?
</blockquote></details>

Sorry, my bad!

**Review by metacertain — APPROVED** [review]

**Pull request merged**
