### PR TITLE
feat: graceful node shutdown 

### PR DESCRIPTION
**Pull request by vladopajic**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description

As part of https://github.com/ethersphere/bee/issues/3960, this PR adds mechanism for gracefully halting bee node.

### CODE REVIEW

**Comment by mrekucci** [comment]
What is the benefit that outweighs the security risk of an adversary shutting down a node remotely via the HTTP API? Why can't this be done by just sending an OS signal to the running process?

**Comment by vladopajic** [comment]
> What is the benefit that outweighs the security risk of an adversary shutting down a node remotely via the HTTP API? Why can't this be done by just sending an OS signal to the running process?

If a malicious individual gains access to a Bee node's API, they would probably not be concerned about the `/shutdown` endpoint. Assuming this individual is malicious, their goal would be to maximize harm to the node, including its funds and data. They have better options than shutting down the node in a graceful manner. These options may include:

  - Purchasing stamps and attaching gibberish data to them.
  - Launching a DDoS attack on the node, leading to high memory usage and potential data corruption upon forceful termination by the operating system.
   - Unstaking funds from the node, causing financial losses and removing the node from participation in the Schelling game. The attacker may prefer to keep the node alive to deceive the node operator into thinking everything is normal.

Based on the above, it appears that the `/shutdown` endpoint does not introduce any new risks. Please correct me if I have missed anything.

Shutting down a node on `SIGTERM` has not been considered an ideal approach, in my biased opinion, as it can potentially cause harm. Assuming a node has this feature, the node operator may attempt to terminate the node. However, if the node needs to wait for the Schelling game to finish, the operator might forcefully terminate (kill) the node by repeating the termination command until it shuts down. The usage of `SIGTERM` can vary depending on the user/ programmer, but typically a program should aim to end execution as soon as possible, allowing enough time for graceful closure of resources.

**Comment by mrekucci** [comment]
> Based on the above, it appears that the `/shutdown` endpoint does not introduce any new risks. Please correct me if I have missed anything.

The potential attack vector is quite significant, if node operators do not properly secure their HTTP endpoints, then a simple script can potentially take down a large portion of the network.

> Shutting down a node on `SIGTERM` has not been considered an ideal approach, in my biased opinion, as it can potentially cause harm. Assuming a node has this feature, the node operator may attempt to terminate the node. However, if the node needs to wait for the Schelling game to finish, the operator might forcefully terminate (kill) the node by repeating the termination command until it shuts down. The usage of `SIGTERM` can vary depending on the user/ programmer, but typically a program should aim to end execution as soon as possible, allowing enough time for graceful closure of resources.

It can be mapped to another signal.

**Comment by istae** [comment]
I agree with @mrekucci here.
On top of that, the general recommendation to node operators is to not shutdown their nodes during reveal or claims phases, which is provided in the redistribution status endpoint already.

**Comment by aloknerurkar** [comment]
On top of this, even UX-wise this doesnt make sense. After doing a shutdown, the API is gone. So in order to start the node again the operator has to anyway access the CLI. Also, the risk of someone shutting down majority of the network is too big of a risk for no reward.

**Comment by vladopajic** [comment]
Got it. I will open new PR with implementation using OS signal.

**Pull request closed without merging**
