### PR TITLE
refactor(kademlia): add peers at start asynchronously

### PR DESCRIPTION
**Pull request by mrekucci**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2082)

### CODE REVIEW

**Comment by ldeffenb** [comment]
This may or may not work.  In my experience, the /topology Debug API also doesn't get an answer until the AddPeers call completes.  So there seems to be some locking going on inside there that may still prevent the Kademlia from making peer connection progress.

Give it a try sometime.  Start up a peer with a large (300,000+ population) address book and try to get :1635/topology.  It will sit there for a long time (15-30 minutes for my nodes) until it responds.  And as soon as it responds, the peer connections start happening.

**Review by acud — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2082)* status: all files reviewed, 2 unresolved discussions (waiting on @anatollupacescu, @esadakar, and @mrekucci)

___
*[pkg/p2p/libp2p/libp2p.go, line 275 at r1](https://reviewable.io/reviews/ethersphere/bee/2082#-McDd8E26IhabjlXrHAE:-McDd8E38Oiok4KDLjJ_:b-cua512) ([raw file](https://github.com/ethersphere/bee/blob/3b68e76cfd67738c5f1ac312faea0c13d97e335a/pkg/p2p/libp2p/libp2p.go#L275)):*
> ```Go
> 	select {
> 	case <-s.ready:
> 		go func() { _ = stream.Reset() }()
> ```

you would need to `return` after this, since this would just continue execution here
___
*[pkg/topology/kademlia/kademlia.go, line 585 at r1](https://reviewable.io/reviews/ethersphere/bee/2082#-McDdJx60ZOWvj6zTD_F:-McDdJx60ZOWvj6zTD_G:bqy4ur) ([raw file](https://github.com/ethersphere/bee/blob/3b68e76cfd67738c5f1ac312faea0c13d97e335a/pkg/topology/kademlia/kademlia.go#L585)):*
> ```Go
> 		addresses, err := k.addressBook.Overlays()
> 		if err != nil {
> 			panic(fmt.Errorf("addressbook overlays: %w", err))
> ```

I'm not sure that panicking is the right thing to do here, as it would cause a dirty shutdown. Logging the error and returning should be fine

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2082)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @acud, @anatollupacescu, and @esadakar)

___
*[pkg/topology/kademlia/kademlia.go, line 585 at r1](https://reviewable.io/reviews/ethersphere/bee/2082#-McDdJx60ZOWvj6zTD_F:-McF_EZ97pxYIBg33As1:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/3b68e76cfd67738c5f1ac312faea0c13d97e335a/pkg/topology/kademlia/kademlia.go#L585)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

I'm not sure that panicking is the right thing to do here, as it would cause a dirty shutdown. Logging the error and returning should be fine
</blockquote></details>

Done.
___
*[pkg/p2p/libp2p/libp2p.go, line 275 at r1](https://reviewable.io/reviews/ethersphere/bee/2082#-McDd8E26IhabjlXrHAE:-McFZmrG2aQvvgqKTy8K:b8suiow) ([raw file](https://github.com/ethersphere/bee/blob/3b68e76cfd67738c5f1ac312faea0c13d97e335a/pkg/p2p/libp2p/libp2p.go#L275)):*
<details><summary><i>Previously, acud (acud) wrote…</i></summary><blockquote>

you would need to `return` after this, since this would just continue execution here
</blockquote></details>

Getting rid of this since the nodes cannot connect to each other even with the `return` statement.

**Review by acud — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2082)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatollupacescu and @esadakar)

**Pull request merged**
