### PR TITLE
fix: recompute expected debt after time settlement

### PR DESCRIPTION
**Pull request by ralph-pichler**
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/2116)

### CODE REVIEW

**Review by metacertain — APPROVED** [review]

**Review by mrekucci — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ralph-pichler)

___
*[pkg/accounting/accounting.go, line 174 at r1](https://reviewable.io/reviews/ethersphere/bee/2116#-McO5Igh4FR0sgcZnna8:-McO5Igi0VwyvgmqkzDe:bn9cy5v) ([raw file](https://github.com/ethersphere/bee/blob/1cc802abe4e6ad6d61617f22b89939f27b95102a/pkg/accounting/accounting.go#L174)):*
> ```Go
> 
> 	currentBalance, err := a.Balance(peer)
> 	if err != nil {
> ```

There is no need to do the extra `err != nil` check 'cause `errors.Is` will take care about this.

**Review by ralph-pichler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ralph-pichler)

___
*[pkg/accounting/accounting.go, line 174 at r1](https://reviewable.io/reviews/ethersphere/bee/2116#-McO5Igh4FR0sgcZnna8:-McOORYE1-ejnZ281mSz:byuegmr) ([raw file](https://github.com/ethersphere/bee/blob/709bf490ad8ed8c3b431d5d3a836491f19e6b008/pkg/accounting/accounting.go#L174)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

There is no need to do the extra `err != nil` check 'cause `errors.Is` will take care about this.
</blockquote></details>

if i don't have this then `errors.Is` will return false as `nil` is not `ErrPeerNoBalance`, so the if will evaluate true and it will fail if there is no error.

**Review by mrekucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ralph-pichler)

___
*[pkg/accounting/accounting.go, line 174 at r1](https://reviewable.io/reviews/ethersphere/bee/2116#-McO5Igh4FR0sgcZnna8:-McOTp-72zqQBcOJU5_s:bwovd7m) ([raw file](https://github.com/ethersphere/bee/blob/709bf490ad8ed8c3b431d5d3a836491f19e6b008/pkg/accounting/accounting.go#L174)):*
<details><summary><i>Previously, ralph-pichler (Ralph Pichler) wrote…</i></summary><blockquote>

if i don't have this then `errors.Is` will return false as `nil` is not `ErrPeerNoBalance`, so the if will evaluate true and it will fail if there is no error.
</blockquote></details>

Ah yes, my mistake, I missed the `!`. Never the less there is no need for two `if`s, it can be simplified as `if err != nil && !errors.Is(err, ErrPeerNoBalance)...` since you don't have any statements below the second `if`.

**Review by ralph-pichler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2116)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mrekucci)

___
*[pkg/accounting/accounting.go, line 174 at r1](https://reviewable.io/reviews/ethersphere/bee/2116#-McO5Igh4FR0sgcZnna8:-McOWzDN6nkvfrPekUmY:b5x2e7m) ([raw file](https://github.com/ethersphere/bee/blob/709bf490ad8ed8c3b431d5d3a836491f19e6b008/pkg/accounting/accounting.go#L174)):*
<details><summary><i>Previously, mrekucci (Peter Mrekaj) wrote…</i></summary><blockquote>

Ah yes, my mistake, I missed the `!`. Never the less there is no need for two `if`s, it can be simplified as `if err != nil && !errors.Is(err, ErrPeerNoBalance)...` since you don't have any statements below the second `if`.
</blockquote></details>

combined them

**Review by mrekucci — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/2116#-:-McOZIwcAxEyRV2L7Ag4:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mrekucci)

**Pull request merged**
